/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AcceptInvitationDto,
  CancelInvitationDto,
  CreateApiKeyDto,
  CreateOrganizationDto,
  DeleteApiKeyDto,
  DeleteOrganizationDto,
  ErrorResponseDto,
  ForgotPasswordDto,
  GetSessionResponseDto,
  InviteMemberDto,
  RejectInvitationDto,
  RemoveMemberDto,
  ResetPasswordDto,
  SetActiveOrganizationDto,
  SignInDto,
  SignUpDto,
  UpdateApiKeyDto,
  UpdateMemberRoleDto,
  UpdateOrganizationDto,
  VerifyApiKeyDto,
} from '../models/index';
import {
    AcceptInvitationDtoFromJSON,
    AcceptInvitationDtoToJSON,
    CancelInvitationDtoFromJSON,
    CancelInvitationDtoToJSON,
    CreateApiKeyDtoFromJSON,
    CreateApiKeyDtoToJSON,
    CreateOrganizationDtoFromJSON,
    CreateOrganizationDtoToJSON,
    DeleteApiKeyDtoFromJSON,
    DeleteApiKeyDtoToJSON,
    DeleteOrganizationDtoFromJSON,
    DeleteOrganizationDtoToJSON,
    ErrorResponseDtoFromJSON,
    ErrorResponseDtoToJSON,
    ForgotPasswordDtoFromJSON,
    ForgotPasswordDtoToJSON,
    GetSessionResponseDtoFromJSON,
    GetSessionResponseDtoToJSON,
    InviteMemberDtoFromJSON,
    InviteMemberDtoToJSON,
    RejectInvitationDtoFromJSON,
    RejectInvitationDtoToJSON,
    RemoveMemberDtoFromJSON,
    RemoveMemberDtoToJSON,
    ResetPasswordDtoFromJSON,
    ResetPasswordDtoToJSON,
    SetActiveOrganizationDtoFromJSON,
    SetActiveOrganizationDtoToJSON,
    SignInDtoFromJSON,
    SignInDtoToJSON,
    SignUpDtoFromJSON,
    SignUpDtoToJSON,
    UpdateApiKeyDtoFromJSON,
    UpdateApiKeyDtoToJSON,
    UpdateMemberRoleDtoFromJSON,
    UpdateMemberRoleDtoToJSON,
    UpdateOrganizationDtoFromJSON,
    UpdateOrganizationDtoToJSON,
    VerifyApiKeyDtoFromJSON,
    VerifyApiKeyDtoToJSON,
} from '../models/index';

export interface AcceptInvitationRequest {
    acceptInvitationDto: AcceptInvitationDto;
}

export interface CancelInvitationRequest {
    cancelInvitationDto: CancelInvitationDto;
}

export interface CreateApiKeyRequest {
    createApiKeyDto: CreateApiKeyDto;
}

export interface CreateOrganizationRequest {
    createOrganizationDto: CreateOrganizationDto;
}

export interface DeleteApiKeyRequest {
    deleteApiKeyDto: DeleteApiKeyDto;
}

export interface DeleteOrganizationRequest {
    deleteOrganizationDto: DeleteOrganizationDto;
}

export interface ForgetPasswordRequest {
    forgotPasswordDto: ForgotPasswordDto;
}

export interface InviteMemberRequest {
    inviteMemberDto: InviteMemberDto;
}

export interface RejectInvitationRequest {
    rejectInvitationDto: RejectInvitationDto;
}

export interface RemoveMemberRequest {
    removeMemberDto: RemoveMemberDto;
}

export interface ResetPasswordRequest {
    resetPasswordDto: ResetPasswordDto;
}

export interface SetActiveOrganizationRequest {
    setActiveOrganizationDto: SetActiveOrganizationDto;
}

export interface SignInEmailRequest {
    signInDto: SignInDto;
}

export interface SignUpEmailRequest {
    signUpDto: SignUpDto;
}

export interface UpdateApiKeyRequest {
    updateApiKeyDto: UpdateApiKeyDto;
}

export interface UpdateMemberRoleRequest {
    updateMemberRoleDto: UpdateMemberRoleDto;
}

export interface UpdateOrganizationRequest {
    updateOrganizationDto: UpdateOrganizationDto;
}

export interface VerifyApiKeyRequest {
    verifyApiKeyDto: VerifyApiKeyDto;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Accept an invitation to an organization
     * Accept Invitation
     */
    async acceptInvitationRaw(requestParameters: AcceptInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['acceptInvitationDto'] == null) {
            throw new runtime.RequiredError(
                'acceptInvitationDto',
                'Required parameter "acceptInvitationDto" was null or undefined when calling acceptInvitation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/organization/accept-invitation`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AcceptInvitationDtoToJSON(requestParameters['acceptInvitationDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Accept an invitation to an organization
     * Accept Invitation
     */
    async acceptInvitation(acceptInvitationDto: AcceptInvitationDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.acceptInvitationRaw({ acceptInvitationDto: acceptInvitationDto }, initOverrides);
    }

    /**
     * Cancel an invitation to an organization
     * Cancel Invitation
     */
    async cancelInvitationRaw(requestParameters: CancelInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cancelInvitationDto'] == null) {
            throw new runtime.RequiredError(
                'cancelInvitationDto',
                'Required parameter "cancelInvitationDto" was null or undefined when calling cancelInvitation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/organization/cancel-invitation`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CancelInvitationDtoToJSON(requestParameters['cancelInvitationDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancel an invitation to an organization
     * Cancel Invitation
     */
    async cancelInvitation(cancelInvitationDto: CancelInvitationDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelInvitationRaw({ cancelInvitationDto: cancelInvitationDto }, initOverrides);
    }

    /**
     * Create a new API key
     * Create API Key
     */
    async createApiKeyRaw(requestParameters: CreateApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createApiKeyDto'] == null) {
            throw new runtime.RequiredError(
                'createApiKeyDto',
                'Required parameter "createApiKeyDto" was null or undefined when calling createApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/api-key/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateApiKeyDtoToJSON(requestParameters['createApiKeyDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new API key
     * Create API Key
     */
    async createApiKey(createApiKeyDto: CreateApiKeyDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createApiKeyRaw({ createApiKeyDto: createApiKeyDto }, initOverrides);
    }

    /**
     * Create a new organization
     * Create Organization
     */
    async createOrganizationRaw(requestParameters: CreateOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createOrganizationDto'] == null) {
            throw new runtime.RequiredError(
                'createOrganizationDto',
                'Required parameter "createOrganizationDto" was null or undefined when calling createOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/organization/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizationDtoToJSON(requestParameters['createOrganizationDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new organization
     * Create Organization
     */
    async createOrganization(createOrganizationDto: CreateOrganizationDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createOrganizationRaw({ createOrganizationDto: createOrganizationDto }, initOverrides);
    }

    /**
     * Delete an API key
     * Delete API Key
     */
    async deleteApiKeyRaw(requestParameters: DeleteApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['deleteApiKeyDto'] == null) {
            throw new runtime.RequiredError(
                'deleteApiKeyDto',
                'Required parameter "deleteApiKeyDto" was null or undefined when calling deleteApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/api-key/delete`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteApiKeyDtoToJSON(requestParameters['deleteApiKeyDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an API key
     * Delete API Key
     */
    async deleteApiKey(deleteApiKeyDto: DeleteApiKeyDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteApiKeyRaw({ deleteApiKeyDto: deleteApiKeyDto }, initOverrides);
    }

    /**
     * Delete an organization
     * Delete Organization
     */
    async deleteOrganizationRaw(requestParameters: DeleteOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['deleteOrganizationDto'] == null) {
            throw new runtime.RequiredError(
                'deleteOrganizationDto',
                'Required parameter "deleteOrganizationDto" was null or undefined when calling deleteOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/organization/delete`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteOrganizationDtoToJSON(requestParameters['deleteOrganizationDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an organization
     * Delete Organization
     */
    async deleteOrganization(deleteOrganizationDto: DeleteOrganizationDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOrganizationRaw({ deleteOrganizationDto: deleteOrganizationDto }, initOverrides);
    }

    /**
     * Send a password reset email to the user
     * Forget Password
     */
    async forgetPasswordRaw(requestParameters: ForgetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['forgotPasswordDto'] == null) {
            throw new runtime.RequiredError(
                'forgotPasswordDto',
                'Required parameter "forgotPasswordDto" was null or undefined when calling forgetPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/canary/authentication/forget-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ForgotPasswordDtoToJSON(requestParameters['forgotPasswordDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Send a password reset email to the user
     * Forget Password
     */
    async forgetPassword(forgotPasswordDto: ForgotPasswordDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.forgetPasswordRaw({ forgotPasswordDto: forgotPasswordDto }, initOverrides);
    }

    /**
     * Retrieve the current user session
     * Get Session
     */
    async getSessionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSessionResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/get-session`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSessionResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieve the current user session
     * Get Session
     */
    async getSession(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSessionResponseDto> {
        const response = await this.getSessionRaw(initOverrides);
        return await response.value();
    }

    /**
     * Invite a user to an organization
     * Invite Member
     */
    async inviteMemberRaw(requestParameters: InviteMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['inviteMemberDto'] == null) {
            throw new runtime.RequiredError(
                'inviteMemberDto',
                'Required parameter "inviteMemberDto" was null or undefined when calling inviteMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/organization/invite-member`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InviteMemberDtoToJSON(requestParameters['inviteMemberDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Invite a user to an organization
     * Invite Member
     */
    async inviteMember(inviteMemberDto: InviteMemberDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.inviteMemberRaw({ inviteMemberDto: inviteMemberDto }, initOverrides);
    }

    /**
     * List all API keys for the current user
     * List API Keys
     */
    async listApiKeysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/api-key/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List all API keys for the current user
     * List API Keys
     */
    async listApiKeys(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.listApiKeysRaw(initOverrides);
    }

    /**
     * List all organizations for the current user
     * List Organizations
     */
    async listOrganizationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/organization/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List all organizations for the current user
     * List Organizations
     */
    async listOrganizations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.listOrganizationsRaw(initOverrides);
    }

    /**
     * Reject an invitation to an organization
     * Reject Invitation
     */
    async rejectInvitationRaw(requestParameters: RejectInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['rejectInvitationDto'] == null) {
            throw new runtime.RequiredError(
                'rejectInvitationDto',
                'Required parameter "rejectInvitationDto" was null or undefined when calling rejectInvitation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/organization/reject-invitation`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RejectInvitationDtoToJSON(requestParameters['rejectInvitationDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reject an invitation to an organization
     * Reject Invitation
     */
    async rejectInvitation(rejectInvitationDto: RejectInvitationDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rejectInvitationRaw({ rejectInvitationDto: rejectInvitationDto }, initOverrides);
    }

    /**
     * Remove a member from an organization
     * Remove Member
     */
    async removeMemberRaw(requestParameters: RemoveMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['removeMemberDto'] == null) {
            throw new runtime.RequiredError(
                'removeMemberDto',
                'Required parameter "removeMemberDto" was null or undefined when calling removeMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/organization/remove-member`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RemoveMemberDtoToJSON(requestParameters['removeMemberDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a member from an organization
     * Remove Member
     */
    async removeMember(removeMemberDto: RemoveMemberDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeMemberRaw({ removeMemberDto: removeMemberDto }, initOverrides);
    }

    /**
     * Reset the user\'s password using a token
     * Reset Password
     */
    async resetPasswordRaw(requestParameters: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['resetPasswordDto'] == null) {
            throw new runtime.RequiredError(
                'resetPasswordDto',
                'Required parameter "resetPasswordDto" was null or undefined when calling resetPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/canary/authentication/reset-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetPasswordDtoToJSON(requestParameters['resetPasswordDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reset the user\'s password using a token
     * Reset Password
     */
    async resetPassword(resetPasswordDto: ResetPasswordDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.resetPasswordRaw({ resetPasswordDto: resetPasswordDto }, initOverrides);
    }

    /**
     * Set the active organization for the current session
     * Set Active Organization
     */
    async setActiveOrganizationRaw(requestParameters: SetActiveOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['setActiveOrganizationDto'] == null) {
            throw new runtime.RequiredError(
                'setActiveOrganizationDto',
                'Required parameter "setActiveOrganizationDto" was null or undefined when calling setActiveOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/organization/set-active`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetActiveOrganizationDtoToJSON(requestParameters['setActiveOrganizationDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Set the active organization for the current session
     * Set Active Organization
     */
    async setActiveOrganization(setActiveOrganizationDto: SetActiveOrganizationDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setActiveOrganizationRaw({ setActiveOrganizationDto: setActiveOrganizationDto }, initOverrides);
    }

    /**
     * Authenticate a user using email and password
     * Sign in with email
     */
    async signInEmailRaw(requestParameters: SignInEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['signInDto'] == null) {
            throw new runtime.RequiredError(
                'signInDto',
                'Required parameter "signInDto" was null or undefined when calling signInEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/canary/authentication/sign-in/email`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignInDtoToJSON(requestParameters['signInDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Authenticate a user using email and password
     * Sign in with email
     */
    async signInEmail(signInDto: SignInDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.signInEmailRaw({ signInDto: signInDto }, initOverrides);
    }

    /**
     * Sign out the current user and invalidate the session
     * Sign out
     */
    async signOutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/sign-out`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Sign out the current user and invalidate the session
     * Sign out
     */
    async signOut(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.signOutRaw(initOverrides);
    }

    /**
     * Create a new user account using email and password
     * Sign up with email
     */
    async signUpEmailRaw(requestParameters: SignUpEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['signUpDto'] == null) {
            throw new runtime.RequiredError(
                'signUpDto',
                'Required parameter "signUpDto" was null or undefined when calling signUpEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/canary/authentication/sign-up/email`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignUpDtoToJSON(requestParameters['signUpDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new user account using email and password
     * Sign up with email
     */
    async signUpEmail(signUpDto: SignUpDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.signUpEmailRaw({ signUpDto: signUpDto }, initOverrides);
    }

    /**
     * Update an API key
     * Update API Key
     */
    async updateApiKeyRaw(requestParameters: UpdateApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['updateApiKeyDto'] == null) {
            throw new runtime.RequiredError(
                'updateApiKeyDto',
                'Required parameter "updateApiKeyDto" was null or undefined when calling updateApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/api-key/update`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateApiKeyDtoToJSON(requestParameters['updateApiKeyDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update an API key
     * Update API Key
     */
    async updateApiKey(updateApiKeyDto: UpdateApiKeyDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateApiKeyRaw({ updateApiKeyDto: updateApiKeyDto }, initOverrides);
    }

    /**
     * Update a member\'s role in an organization
     * Update Member Role
     */
    async updateMemberRoleRaw(requestParameters: UpdateMemberRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['updateMemberRoleDto'] == null) {
            throw new runtime.RequiredError(
                'updateMemberRoleDto',
                'Required parameter "updateMemberRoleDto" was null or undefined when calling updateMemberRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/organization/update-member-role`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMemberRoleDtoToJSON(requestParameters['updateMemberRoleDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update a member\'s role in an organization
     * Update Member Role
     */
    async updateMemberRole(updateMemberRoleDto: UpdateMemberRoleDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateMemberRoleRaw({ updateMemberRoleDto: updateMemberRoleDto }, initOverrides);
    }

    /**
     * Update an organization\'s details
     * Update Organization
     */
    async updateOrganizationRaw(requestParameters: UpdateOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['updateOrganizationDto'] == null) {
            throw new runtime.RequiredError(
                'updateOrganizationDto',
                'Required parameter "updateOrganizationDto" was null or undefined when calling updateOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/authentication/organization/update`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrganizationDtoToJSON(requestParameters['updateOrganizationDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update an organization\'s details
     * Update Organization
     */
    async updateOrganization(updateOrganizationDto: UpdateOrganizationDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateOrganizationRaw({ updateOrganizationDto: updateOrganizationDto }, initOverrides);
    }

    /**
     * Verify an API key
     * Verify API Key
     */
    async verifyApiKeyRaw(requestParameters: VerifyApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['verifyApiKeyDto'] == null) {
            throw new runtime.RequiredError(
                'verifyApiKeyDto',
                'Required parameter "verifyApiKeyDto" was null or undefined when calling verifyApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/canary/authentication/api-key/verify`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyApiKeyDtoToJSON(requestParameters['verifyApiKeyDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Verify an API key
     * Verify API Key
     */
    async verifyApiKey(verifyApiKeyDto: VerifyApiKeyDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.verifyApiKeyRaw({ verifyApiKeyDto: verifyApiKeyDto }, initOverrides);
    }

}
