/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BalanceHistoryResponseDto,
  ErrorResponseDto,
  MerchantBalanceResponseDto,
} from '../models/index';
import {
    BalanceHistoryResponseDtoFromJSON,
    BalanceHistoryResponseDtoToJSON,
    ErrorResponseDtoFromJSON,
    ErrorResponseDtoToJSON,
    MerchantBalanceResponseDtoFromJSON,
    MerchantBalanceResponseDtoToJSON,
} from '../models/index';

export interface GetBalanceHistoryRequest {
    merchantId: string;
    limit?: number;
    offset?: number;
    startDate?: string;
    endDate?: string;
    transactionType?: string;
}

export interface GetMerchantBalanceRequest {
    merchantId: string;
}

/**
 * 
 */
export class BalanceApi extends runtime.BaseAPI {

    /**
     * A full ledger of all transactions, fees, and payouts for the merchant\'s master account.
     * List Merchant Balance History
     */
    async getBalanceHistoryRaw(requestParameters: GetBalanceHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BalanceHistoryResponseDto>> {
        if (requestParameters['merchantId'] == null) {
            throw new runtime.RequiredError(
                'merchantId',
                'Required parameter "merchantId" was null or undefined when calling getBalanceHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['merchantId'] != null) {
            queryParameters['merchantId'] = requestParameters['merchantId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = requestParameters['startDate'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = requestParameters['endDate'];
        }

        if (requestParameters['transactionType'] != null) {
            queryParameters['transactionType'] = requestParameters['transactionType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/balance/history`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BalanceHistoryResponseDtoFromJSON(jsonValue));
    }

    /**
     * A full ledger of all transactions, fees, and payouts for the merchant\'s master account.
     * List Merchant Balance History
     */
    async getBalanceHistory(merchantId: string, limit?: number, offset?: number, startDate?: string, endDate?: string, transactionType?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BalanceHistoryResponseDto> {
        const response = await this.getBalanceHistoryRaw({ merchantId: merchantId, limit: limit, offset: offset, startDate: startDate, endDate: endDate, transactionType: transactionType }, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the merchant\'s own master balance (their earnings) available for payouts.
     * Get Merchant Balance
     */
    async getMerchantBalanceRaw(requestParameters: GetMerchantBalanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MerchantBalanceResponseDto>> {
        if (requestParameters['merchantId'] == null) {
            throw new runtime.RequiredError(
                'merchantId',
                'Required parameter "merchantId" was null or undefined when calling getMerchantBalance().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['merchantId'] != null) {
            queryParameters['merchantId'] = requestParameters['merchantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/balance`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MerchantBalanceResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieves the merchant\'s own master balance (their earnings) available for payouts.
     * Get Merchant Balance
     */
    async getMerchantBalance(merchantId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MerchantBalanceResponseDto> {
        const response = await this.getMerchantBalanceRaw({ merchantId: merchantId }, initOverrides);
        return await response.value();
    }

}
