/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.1
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequestResponseDto,
  CreateOrganizationComplianceDto,
  InternalServerErrorResponseDto,
  ListOrganizationComplianceResponseDto,
  NotFoundResponseDto,
  OrganizationComplianceResponseDto,
  UnauthorizedResponseDto,
  UpdateOrganizationComplianceDto,
} from '../models/index';
import {
    BadRequestResponseDtoFromJSON,
    BadRequestResponseDtoToJSON,
    CreateOrganizationComplianceDtoFromJSON,
    CreateOrganizationComplianceDtoToJSON,
    InternalServerErrorResponseDtoFromJSON,
    InternalServerErrorResponseDtoToJSON,
    ListOrganizationComplianceResponseDtoFromJSON,
    ListOrganizationComplianceResponseDtoToJSON,
    NotFoundResponseDtoFromJSON,
    NotFoundResponseDtoToJSON,
    OrganizationComplianceResponseDtoFromJSON,
    OrganizationComplianceResponseDtoToJSON,
    UnauthorizedResponseDtoFromJSON,
    UnauthorizedResponseDtoToJSON,
    UpdateOrganizationComplianceDtoFromJSON,
    UpdateOrganizationComplianceDtoToJSON,
} from '../models/index';

export interface CreateComplianceRequest {
    createOrganizationComplianceDto: CreateOrganizationComplianceDto;
}

export interface ListComplianceRequest {
    limit?: number;
    offset?: number;
    filter?: string;
    sort?: string;
    order?: string;
}

export interface UpdateComplianceRequest {
    id: string;
    updateOrganizationComplianceDto: UpdateOrganizationComplianceDto;
}

/**
 * 
 */
export class ComplianceApi extends runtime.BaseAPI {

    /**
     * Create Compliance info
     */
    async createComplianceRaw(requestParameters: CreateComplianceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationComplianceResponseDto>> {
        if (requestParameters['createOrganizationComplianceDto'] == null) {
            throw new runtime.RequiredError(
                'createOrganizationComplianceDto',
                'Required parameter "createOrganizationComplianceDto" was null or undefined when calling createCompliance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/compliance`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizationComplianceDtoToJSON(requestParameters['createOrganizationComplianceDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationComplianceResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create Compliance info
     */
    async createCompliance(createOrganizationComplianceDto: CreateOrganizationComplianceDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationComplianceResponseDto> {
        const response = await this.createComplianceRaw({ createOrganizationComplianceDto: createOrganizationComplianceDto }, initOverrides);
        return await response.value();
    }

    /**
     * List Compliance info for organization
     */
    async listComplianceRaw(requestParameters: ListComplianceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListOrganizationComplianceResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/compliance`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListOrganizationComplianceResponseDtoFromJSON(jsonValue));
    }

    /**
     * List Compliance info for organization
     */
    async listCompliance(limit?: number, offset?: number, filter?: string, sort?: string, order?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListOrganizationComplianceResponseDto> {
        const response = await this.listComplianceRaw({ limit: limit, offset: offset, filter: filter, sort: sort, order: order }, initOverrides);
        return await response.value();
    }

    /**
     * Update Compliance info
     */
    async updateComplianceRaw(requestParameters: UpdateComplianceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCompliance().'
            );
        }

        if (requestParameters['updateOrganizationComplianceDto'] == null) {
            throw new runtime.RequiredError(
                'updateOrganizationComplianceDto',
                'Required parameter "updateOrganizationComplianceDto" was null or undefined when calling updateCompliance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/compliance/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrganizationComplianceDtoToJSON(requestParameters['updateOrganizationComplianceDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Compliance info
     */
    async updateCompliance(id: string, updateOrganizationComplianceDto: UpdateOrganizationComplianceDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateComplianceRaw({ id: id, updateOrganizationComplianceDto: updateOrganizationComplianceDto }, initOverrides);
    }

}
