/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePaymentIntentDto,
  ErrorResponseDto,
  ListPaymentIntentsResponseDto,
  PaymentIntentResponseDto,
} from '../models/index';
import {
    CreatePaymentIntentDtoFromJSON,
    CreatePaymentIntentDtoToJSON,
    ErrorResponseDtoFromJSON,
    ErrorResponseDtoToJSON,
    ListPaymentIntentsResponseDtoFromJSON,
    ListPaymentIntentsResponseDtoToJSON,
    PaymentIntentResponseDtoFromJSON,
    PaymentIntentResponseDtoToJSON,
} from '../models/index';

export interface CancelPaymentIntentRequest {
    id: string;
}

export interface ConfirmPaymentIntentRequest {
    id: string;
}

export interface CreatePaymentIntentRequest {
    createPaymentIntentDto: CreatePaymentIntentDto;
}

export interface ListPaymentIntentsRequest {
    merchantId?: string;
    limit?: number;
    offset?: number;
    status?: ListPaymentIntentsStatusEnum;
}

export interface RetrievePaymentIntentRequest {
    id: string;
}

/**
 * 
 */
export class PaymentIntentsApi extends runtime.BaseAPI {

    /**
     * Cancels a payment intent that has not yet succeeded or failed.
     * Cancel Payment Intent
     */
    async cancelPaymentIntentRaw(requestParameters: CancelPaymentIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentIntentResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelPaymentIntent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/payment-intents/{id}/cancel`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentIntentResponseDtoFromJSON(jsonValue));
    }

    /**
     * Cancels a payment intent that has not yet succeeded or failed.
     * Cancel Payment Intent
     */
    async cancelPaymentIntent(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentIntentResponseDto> {
        const response = await this.cancelPaymentIntentRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Confirms a payment intent that requires confirmation. This initiates the actual payment processing.
     * Confirm Payment Intent
     */
    async confirmPaymentIntentRaw(requestParameters: ConfirmPaymentIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentIntentResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling confirmPaymentIntent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/payment-intents/{id}/confirm`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentIntentResponseDtoFromJSON(jsonValue));
    }

    /**
     * Confirms a payment intent that requires confirmation. This initiates the actual payment processing.
     * Confirm Payment Intent
     */
    async confirmPaymentIntent(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentIntentResponseDto> {
        const response = await this.confirmPaymentIntentRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Creates a payment intent for off-session charges. Used for subscriptions, recurring billing, or server-to-server payments with saved cards.
     * Create Payment Intent
     */
    async createPaymentIntentRaw(requestParameters: CreatePaymentIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentIntentResponseDto>> {
        if (requestParameters['createPaymentIntentDto'] == null) {
            throw new runtime.RequiredError(
                'createPaymentIntentDto',
                'Required parameter "createPaymentIntentDto" was null or undefined when calling createPaymentIntent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/payment-intents`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePaymentIntentDtoToJSON(requestParameters['createPaymentIntentDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentIntentResponseDtoFromJSON(jsonValue));
    }

    /**
     * Creates a payment intent for off-session charges. Used for subscriptions, recurring billing, or server-to-server payments with saved cards.
     * Create Payment Intent
     */
    async createPaymentIntent(createPaymentIntentDto: CreatePaymentIntentDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentIntentResponseDto> {
        const response = await this.createPaymentIntentRaw({ createPaymentIntentDto: createPaymentIntentDto }, initOverrides);
        return await response.value();
    }

    /**
     * Lists payment intents for a specific merchant with pagination and filtering.
     * List Payment Intents
     */
    async listPaymentIntentsRaw(requestParameters: ListPaymentIntentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPaymentIntentsResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['merchantId'] != null) {
            queryParameters['merchantId'] = requestParameters['merchantId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/payment-intents`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPaymentIntentsResponseDtoFromJSON(jsonValue));
    }

    /**
     * Lists payment intents for a specific merchant with pagination and filtering.
     * List Payment Intents
     */
    async listPaymentIntents(merchantId?: string, limit?: number, offset?: number, status?: ListPaymentIntentsStatusEnum, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPaymentIntentsResponseDto> {
        const response = await this.listPaymentIntentsRaw({ merchantId: merchantId, limit: limit, offset: offset, status: status }, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the current state of a specific payment intent.
     * Retrieve Payment Intent
     */
    async retrievePaymentIntentRaw(requestParameters: RetrievePaymentIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentIntentResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling retrievePaymentIntent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/payment-intents/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentIntentResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieves the current state of a specific payment intent.
     * Retrieve Payment Intent
     */
    async retrievePaymentIntent(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentIntentResponseDto> {
        const response = await this.retrievePaymentIntentRaw({ id: id }, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListPaymentIntentsStatusEnum = {
    Initiation: 'initiation',
    RequiresPaymentMethod: 'requires_payment_method',
    RequiresConfirmation: 'requires_confirmation',
    RequiresAction: 'requires_action',
    Processing: 'processing',
    RequiresCapture: 'requires_capture',
    Succeeded: 'succeeded',
    Failed: 'failed',
    Canceled: 'canceled'
} as const;
export type ListPaymentIntentsStatusEnum = typeof ListPaymentIntentsStatusEnum[keyof typeof ListPaymentIntentsStatusEnum];
