/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequestResponseDto,
  CreatePaymentLinkDto,
  InternalServerErrorResponseDto,
  ListPaymentLinksResponseDto,
  NotFoundResponseDto,
  PaymentLinkResponseDto,
  UnauthorizedResponseDto,
  UpdatePaymentLinkDto,
} from '../models/index';
import {
    BadRequestResponseDtoFromJSON,
    BadRequestResponseDtoToJSON,
    CreatePaymentLinkDtoFromJSON,
    CreatePaymentLinkDtoToJSON,
    InternalServerErrorResponseDtoFromJSON,
    InternalServerErrorResponseDtoToJSON,
    ListPaymentLinksResponseDtoFromJSON,
    ListPaymentLinksResponseDtoToJSON,
    NotFoundResponseDtoFromJSON,
    NotFoundResponseDtoToJSON,
    PaymentLinkResponseDtoFromJSON,
    PaymentLinkResponseDtoToJSON,
    UnauthorizedResponseDtoFromJSON,
    UnauthorizedResponseDtoToJSON,
    UpdatePaymentLinkDtoFromJSON,
    UpdatePaymentLinkDtoToJSON,
} from '../models/index';

export interface CreatePaymentLinkRequest {
    createPaymentLinkDto: CreatePaymentLinkDto;
}

export interface ListPaymentLinksRequest {
    merchantId?: string;
    limit?: number;
    offset?: number;
    active?: boolean;
}

export interface RetrievePaymentLinkRequest {
    id: string;
}

export interface UpdatePaymentLinkRequest {
    id: string;
    updatePaymentLinkDto: UpdatePaymentLinkDto;
}

/**
 * 
 */
export class PaymentLinksApi extends runtime.BaseAPI {

    /**
     * Creates a re-usable hosted link. Can be used for: (1) Selling a product, or (2) as a \"Pay-In\" link for a customer.
     * Create Payment Link
     */
    async createPaymentLinkRaw(requestParameters: CreatePaymentLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentLinkResponseDto>> {
        if (requestParameters['createPaymentLinkDto'] == null) {
            throw new runtime.RequiredError(
                'createPaymentLinkDto',
                'Required parameter "createPaymentLinkDto" was null or undefined when calling createPaymentLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/payment-links`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePaymentLinkDtoToJSON(requestParameters['createPaymentLinkDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentLinkResponseDtoFromJSON(jsonValue));
    }

    /**
     * Creates a re-usable hosted link. Can be used for: (1) Selling a product, or (2) as a \"Pay-In\" link for a customer.
     * Create Payment Link
     */
    async createPaymentLink(createPaymentLinkDto: CreatePaymentLinkDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentLinkResponseDto> {
        const response = await this.createPaymentLinkRaw({ createPaymentLinkDto: createPaymentLinkDto }, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves all payment links created by the merchant.
     * List Payment Links
     */
    async listPaymentLinksRaw(requestParameters: ListPaymentLinksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPaymentLinksResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['merchantId'] != null) {
            queryParameters['merchantId'] = requestParameters['merchantId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['active'] != null) {
            queryParameters['active'] = requestParameters['active'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/payment-links`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPaymentLinksResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieves all payment links created by the merchant.
     * List Payment Links
     */
    async listPaymentLinks(merchantId?: string, limit?: number, offset?: number, active?: boolean, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPaymentLinksResponseDto> {
        const response = await this.listPaymentLinksRaw({ merchantId: merchantId, limit: limit, offset: offset, active: active }, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a single payment link by ID.
     * Retrieve Payment Link
     */
    async retrievePaymentLinkRaw(requestParameters: RetrievePaymentLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentLinkResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling retrievePaymentLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/payment-links/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentLinkResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieves a single payment link by ID.
     * Retrieve Payment Link
     */
    async retrievePaymentLink(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentLinkResponseDto> {
        const response = await this.retrievePaymentLinkRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Updates a link\'s details, most commonly to set active: false.
     * Update Payment Link
     */
    async updatePaymentLinkRaw(requestParameters: UpdatePaymentLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updatePaymentLink().'
            );
        }

        if (requestParameters['updatePaymentLinkDto'] == null) {
            throw new runtime.RequiredError(
                'updatePaymentLinkDto',
                'Required parameter "updatePaymentLinkDto" was null or undefined when calling updatePaymentLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/payment-links/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePaymentLinkDtoToJSON(requestParameters['updatePaymentLinkDto']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Updates a link\'s details, most commonly to set active: false.
     * Update Payment Link
     */
    async updatePaymentLink(id: string, updatePaymentLinkDto: UpdatePaymentLinkDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updatePaymentLinkRaw({ id: id, updatePaymentLinkDto: updatePaymentLinkDto }, initOverrides);
        return await response.value();
    }

}
