/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateProductDto,
  ErrorResponseDto,
  ListProductsResponseDto,
  ProductResponseDto,
  UpdateProductDto,
} from '../models/index';
import {
    CreateProductDtoFromJSON,
    CreateProductDtoToJSON,
    ErrorResponseDtoFromJSON,
    ErrorResponseDtoToJSON,
    ListProductsResponseDtoFromJSON,
    ListProductsResponseDtoToJSON,
    ProductResponseDtoFromJSON,
    ProductResponseDtoToJSON,
    UpdateProductDtoFromJSON,
    UpdateProductDtoToJSON,
} from '../models/index';

export interface CreateProductRequest {
    createProductDto: CreateProductDto;
}

export interface ListProductsRequest {
    merchantId: string;
    limit?: number;
    offset?: number;
    active?: boolean;
}

export interface UpdateProductRequest {
    id: string;
    updateProductDto: UpdateProductDto;
}

/**
 * 
 */
export class ProductsApi extends runtime.BaseAPI {

    /**
     * Defines a product in the merchant\'s catalog (e.g., \"Airtime,\" \"Data\").
     * Create Product
     */
    async createProductRaw(requestParameters: CreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductResponseDto>> {
        if (requestParameters['createProductDto'] == null) {
            throw new runtime.RequiredError(
                'createProductDto',
                'Required parameter "createProductDto" was null or undefined when calling createProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/products`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProductDtoToJSON(requestParameters['createProductDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductResponseDtoFromJSON(jsonValue));
    }

    /**
     * Defines a product in the merchant\'s catalog (e.g., \"Airtime,\" \"Data\").
     * Create Product
     */
    async createProduct(createProductDto: CreateProductDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductResponseDto> {
        const response = await this.createProductRaw({ createProductDto: createProductDto }, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves all products in the merchant\'s catalog.
     * List Products
     */
    async listProductsRaw(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListProductsResponseDto>> {
        if (requestParameters['merchantId'] == null) {
            throw new runtime.RequiredError(
                'merchantId',
                'Required parameter "merchantId" was null or undefined when calling listProducts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['merchantId'] != null) {
            queryParameters['merchantId'] = requestParameters['merchantId'];
        }

        if (requestParameters['active'] != null) {
            queryParameters['active'] = requestParameters['active'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/products`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListProductsResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieves all products in the merchant\'s catalog.
     * List Products
     */
    async listProducts(merchantId: string, limit?: number, offset?: number, active?: boolean, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListProductsResponseDto> {
        const response = await this.listProductsRaw({ merchantId: merchantId, limit: limit, offset: offset, active: active }, initOverrides);
        return await response.value();
    }

    /**
     * Updates a product\'s name, description, or metadata.
     * Update Product
     */
    async updateProductRaw(requestParameters: UpdateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateProduct().'
            );
        }

        if (requestParameters['updateProductDto'] == null) {
            throw new runtime.RequiredError(
                'updateProductDto',
                'Required parameter "updateProductDto" was null or undefined when calling updateProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/products/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProductDtoToJSON(requestParameters['updateProductDto']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Updates a product\'s name, description, or metadata.
     * Update Product
     */
    async updateProduct(id: string, updateProductDto: UpdateProductDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateProductRaw({ id: id, updateProductDto: updateProductDto }, initOverrides);
        return await response.value();
    }

}
