/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePurchaseDto,
  ErrorResponseDto,
  PurchaseResponseDto,
} from '../models/index';
import {
    CreatePurchaseDtoFromJSON,
    CreatePurchaseDtoToJSON,
    ErrorResponseDtoFromJSON,
    ErrorResponseDtoToJSON,
    PurchaseResponseDtoFromJSON,
    PurchaseResponseDtoToJSON,
} from '../models/index';

export interface CreatePurchaseRequest {
    createPurchaseDto: CreatePurchaseDto;
}

/**
 * 
 */
export class PurchasesApi extends runtime.BaseAPI {

    /**
     * (Wallet-Enabling) Spends a product using the CustomerBalance as the source. Atomically debits the CustomerBalance and credits the MerchantBalance.
     * Buy with Cash Balance
     */
    async createPurchaseRaw(requestParameters: CreatePurchaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PurchaseResponseDto>> {
        if (requestParameters['createPurchaseDto'] == null) {
            throw new runtime.RequiredError(
                'createPurchaseDto',
                'Required parameter "createPurchaseDto" was null or undefined when calling createPurchase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/purchases`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePurchaseDtoToJSON(requestParameters['createPurchaseDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PurchaseResponseDtoFromJSON(jsonValue));
    }

    /**
     * (Wallet-Enabling) Spends a product using the CustomerBalance as the source. Atomically debits the CustomerBalance and credits the MerchantBalance.
     * Buy with Cash Balance
     */
    async createPurchase(createPurchaseDto: CreatePurchaseDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PurchaseResponseDto> {
        const response = await this.createPurchaseRaw({ createPurchaseDto: createPurchaseDto }, initOverrides);
        return await response.value();
    }

}
