/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequestResponseDto,
  ConfirmUploadDto,
  FileDto,
  InternalServerErrorResponseDto,
  ListFilesResponseDto,
  NotFoundResponseDto,
  PresignedDownloadResponseDto,
  PresignedUploadResponseDto,
  RequestUploadUrlDto,
  UnauthorizedResponseDto,
} from '../models/index';
import {
    BadRequestResponseDtoFromJSON,
    BadRequestResponseDtoToJSON,
    ConfirmUploadDtoFromJSON,
    ConfirmUploadDtoToJSON,
    FileDtoFromJSON,
    FileDtoToJSON,
    InternalServerErrorResponseDtoFromJSON,
    InternalServerErrorResponseDtoToJSON,
    ListFilesResponseDtoFromJSON,
    ListFilesResponseDtoToJSON,
    NotFoundResponseDtoFromJSON,
    NotFoundResponseDtoToJSON,
    PresignedDownloadResponseDtoFromJSON,
    PresignedDownloadResponseDtoToJSON,
    PresignedUploadResponseDtoFromJSON,
    PresignedUploadResponseDtoToJSON,
    RequestUploadUrlDtoFromJSON,
    RequestUploadUrlDtoToJSON,
    UnauthorizedResponseDtoFromJSON,
    UnauthorizedResponseDtoToJSON,
} from '../models/index';

export interface ConfirmUploadRequest {
    confirmUploadDto: ConfirmUploadDto;
}

export interface DeleteFileRequest {
    id: string;
}

export interface GetDownloadUrlRequest {
    id: string;
}

export interface GetFileDetailsRequest {
    id: string;
}

export interface ListFilesRequest {
    limit?: number;
    offset?: number;
    tag?: string;
    status?: ListFilesStatusEnum;
    relatedEntityId?: string;
    relatedEntityType?: string;
}

export interface RequestUploadUrlRequest {
    requestUploadUrlDto: RequestUploadUrlDto;
}

/**
 * 
 */
export class StorageApi extends runtime.BaseAPI {

    /**
     * Confirm that a file upload was completed
     */
    async confirmUploadRaw(requestParameters: ConfirmUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileDto>> {
        if (requestParameters['confirmUploadDto'] == null) {
            throw new runtime.RequiredError(
                'confirmUploadDto',
                'Required parameter "confirmUploadDto" was null or undefined when calling confirmUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/storage/confirm-upload`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmUploadDtoToJSON(requestParameters['confirmUploadDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileDtoFromJSON(jsonValue));
    }

    /**
     * Confirm that a file upload was completed
     */
    async confirmUpload(confirmUploadDto: ConfirmUploadDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileDto> {
        const response = await this.confirmUploadRaw({ confirmUploadDto: confirmUploadDto }, initOverrides);
        return await response.value();
    }

    /**
     * Delete a file
     */
    async deleteFileRaw(requestParameters: DeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/storage/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a file
     */
    async deleteFile(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFileRaw({ id: id }, initOverrides);
    }

    /**
     * Get a presigned download URL for a file
     */
    async getDownloadUrlRaw(requestParameters: GetDownloadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresignedDownloadResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDownloadUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/storage/{id}/download-url`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresignedDownloadResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a presigned download URL for a file
     */
    async getDownloadUrl(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresignedDownloadResponseDto> {
        const response = await this.getDownloadUrlRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Get file details
     */
    async getFileDetailsRaw(requestParameters: GetFileDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFileDetails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/storage/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileDtoFromJSON(jsonValue));
    }

    /**
     * Get file details
     */
    async getFileDetails(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileDto> {
        const response = await this.getFileDetailsRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * List files
     */
    async listFilesRaw(requestParameters: ListFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFilesResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['tag'] != null) {
            queryParameters['tag'] = requestParameters['tag'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['relatedEntityId'] != null) {
            queryParameters['relatedEntityId'] = requestParameters['relatedEntityId'];
        }

        if (requestParameters['relatedEntityType'] != null) {
            queryParameters['relatedEntityType'] = requestParameters['relatedEntityType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/storage`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListFilesResponseDtoFromJSON(jsonValue));
    }

    /**
     * List files
     */
    async listFiles(limit?: number, offset?: number, tag?: string, status?: ListFilesStatusEnum, relatedEntityId?: string, relatedEntityType?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFilesResponseDto> {
        const response = await this.listFilesRaw({ limit: limit, offset: offset, tag: tag, status: status, relatedEntityId: relatedEntityId, relatedEntityType: relatedEntityType }, initOverrides);
        return await response.value();
    }

    /**
     * Request a presigned URL for file upload
     */
    async requestUploadUrlRaw(requestParameters: RequestUploadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresignedUploadResponseDto>> {
        if (requestParameters['requestUploadUrlDto'] == null) {
            throw new runtime.RequiredError(
                'requestUploadUrlDto',
                'Required parameter "requestUploadUrlDto" was null or undefined when calling requestUploadUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/storage/upload-url`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestUploadUrlDtoToJSON(requestParameters['requestUploadUrlDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresignedUploadResponseDtoFromJSON(jsonValue));
    }

    /**
     * Request a presigned URL for file upload
     */
    async requestUploadUrl(requestUploadUrlDto: RequestUploadUrlDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresignedUploadResponseDto> {
        const response = await this.requestUploadUrlRaw({ requestUploadUrlDto: requestUploadUrlDto }, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListFilesStatusEnum = {
    Pending: 'pending',
    Uploaded: 'uploaded',
    Failed: 'failed',
    Deleted: 'deleted'
} as const;
export type ListFilesStatusEnum = typeof ListFilesStatusEnum[keyof typeof ListFilesStatusEnum];
