/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequestResponseDto,
  CreateWebhookEndpointDto,
  InternalServerErrorResponseDto,
  ListWebhookEndpointsResponseDto,
  NotFoundResponseDto,
  UnauthorizedResponseDto,
  WebhookEndpointResponseDto,
} from '../models/index';
import {
    BadRequestResponseDtoFromJSON,
    BadRequestResponseDtoToJSON,
    CreateWebhookEndpointDtoFromJSON,
    CreateWebhookEndpointDtoToJSON,
    InternalServerErrorResponseDtoFromJSON,
    InternalServerErrorResponseDtoToJSON,
    ListWebhookEndpointsResponseDtoFromJSON,
    ListWebhookEndpointsResponseDtoToJSON,
    NotFoundResponseDtoFromJSON,
    NotFoundResponseDtoToJSON,
    UnauthorizedResponseDtoFromJSON,
    UnauthorizedResponseDtoToJSON,
    WebhookEndpointResponseDtoFromJSON,
    WebhookEndpointResponseDtoToJSON,
} from '../models/index';

export interface CreateWebhookEndpointRequest {
    createWebhookEndpointDto: CreateWebhookEndpointDto;
}

export interface DeleteWebhookEndpointRequest {
    id: string;
}

export interface ListWebhookEndpointsRequest {
    merchantId?: string;
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Registers a URL to receive real-time events (e.g., checkout.session.completed, purchase.succeeded).
     * Create Webhook Endpoint
     */
    async createWebhookEndpointRaw(requestParameters: CreateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpointResponseDto>> {
        if (requestParameters['createWebhookEndpointDto'] == null) {
            throw new runtime.RequiredError(
                'createWebhookEndpointDto',
                'Required parameter "createWebhookEndpointDto" was null or undefined when calling createWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/webhook-endpoints`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWebhookEndpointDtoToJSON(requestParameters['createWebhookEndpointDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointResponseDtoFromJSON(jsonValue));
    }

    /**
     * Registers a URL to receive real-time events (e.g., checkout.session.completed, purchase.succeeded).
     * Create Webhook Endpoint
     */
    async createWebhookEndpoint(createWebhookEndpointDto: CreateWebhookEndpointDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpointResponseDto> {
        const response = await this.createWebhookEndpointRaw({ createWebhookEndpointDto: createWebhookEndpointDto }, initOverrides);
        return await response.value();
    }

    /**
     * Stops sending events to a specific URL.
     * Delete Webhook Endpoint
     */
    async deleteWebhookEndpointRaw(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/webhook-endpoints/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Stops sending events to a specific URL.
     * Delete Webhook Endpoint
     */
    async deleteWebhookEndpoint(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteWebhookEndpointRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Lists all configured webhook endpoints.
     * List Webhook Endpoints
     */
    async listWebhookEndpointsRaw(requestParameters: ListWebhookEndpointsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWebhookEndpointsResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['merchantId'] != null) {
            queryParameters['merchantId'] = requestParameters['merchantId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/webhook-endpoints`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListWebhookEndpointsResponseDtoFromJSON(jsonValue));
    }

    /**
     * Lists all configured webhook endpoints.
     * List Webhook Endpoints
     */
    async listWebhookEndpoints(merchantId?: string, limit?: number, offset?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWebhookEndpointsResponseDto> {
        const response = await this.listWebhookEndpointsRaw({ merchantId: merchantId, limit: limit, offset: offset }, initOverrides);
        return await response.value();
    }

}
