/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcceptInvitationResponseDto
 */
export interface AcceptInvitationResponseDto {
    /**
     * Invitation accepted successfully
     * @type {boolean}
     * @memberof AcceptInvitationResponseDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the AcceptInvitationResponseDto interface.
 */
export function instanceOfAcceptInvitationResponseDto(value: object): value is AcceptInvitationResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function AcceptInvitationResponseDtoFromJSON(json: any): AcceptInvitationResponseDto {
    return AcceptInvitationResponseDtoFromJSONTyped(json, false);
}

export function AcceptInvitationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptInvitationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function AcceptInvitationResponseDtoToJSON(json: any): AcceptInvitationResponseDto {
    return AcceptInvitationResponseDtoToJSONTyped(json, false);
}

export function AcceptInvitationResponseDtoToJSONTyped(value?: AcceptInvitationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

