/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminRevokeUserSessionsDto
 */
export interface AdminRevokeUserSessionsDto {
    /**
     * The ID of the user whose sessions to revoke
     * @type {string}
     * @memberof AdminRevokeUserSessionsDto
     */
    userId: string;
}

/**
 * Check if a given object implements the AdminRevokeUserSessionsDto interface.
 */
export function instanceOfAdminRevokeUserSessionsDto(value: object): value is AdminRevokeUserSessionsDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AdminRevokeUserSessionsDtoFromJSON(json: any): AdminRevokeUserSessionsDto {
    return AdminRevokeUserSessionsDtoFromJSONTyped(json, false);
}

export function AdminRevokeUserSessionsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRevokeUserSessionsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function AdminRevokeUserSessionsDtoToJSON(json: any): AdminRevokeUserSessionsDto {
    return AdminRevokeUserSessionsDtoToJSONTyped(json, false);
}

export function AdminRevokeUserSessionsDtoToJSONTyped(value?: AdminRevokeUserSessionsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

