/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminUpdateUserDto
 */
export interface AdminUpdateUserDto {
    /**
     * The ID of the user to update
     * @type {string}
     * @memberof AdminUpdateUserDto
     */
    userId: string;
    /**
     * Data to update
     * @type {object}
     * @memberof AdminUpdateUserDto
     */
    data: object;
}

/**
 * Check if a given object implements the AdminUpdateUserDto interface.
 */
export function instanceOfAdminUpdateUserDto(value: object): value is AdminUpdateUserDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AdminUpdateUserDtoFromJSON(json: any): AdminUpdateUserDto {
    return AdminUpdateUserDtoFromJSONTyped(json, false);
}

export function AdminUpdateUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUpdateUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'data': json['data'],
    };
}

export function AdminUpdateUserDtoToJSON(json: any): AdminUpdateUserDto {
    return AdminUpdateUserDtoToJSONTyped(json, false);
}

export function AdminUpdateUserDtoToJSONTyped(value?: AdminUpdateUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'data': value['data'],
    };
}

