/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminRemoveUserResponseDto
 */
export interface AdminRemoveUserResponseDto {
    /**
     * User removed successfully
     * @type {boolean}
     * @memberof AdminRemoveUserResponseDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the AdminRemoveUserResponseDto interface.
 */
export function instanceOfAdminRemoveUserResponseDto(value: object): value is AdminRemoveUserResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function AdminRemoveUserResponseDtoFromJSON(json: any): AdminRemoveUserResponseDto {
    return AdminRemoveUserResponseDtoFromJSONTyped(json, false);
}

export function AdminRemoveUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRemoveUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function AdminRemoveUserResponseDtoToJSON(json: any): AdminRemoveUserResponseDto {
    return AdminRemoveUserResponseDtoToJSONTyped(json, false);
}

export function AdminRemoveUserResponseDtoToJSONTyped(value?: AdminRemoveUserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

