/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionUserDto } from './SessionUserDto';
import {
    SessionUserDtoFromJSON,
    SessionUserDtoFromJSONTyped,
    SessionUserDtoToJSON,
    SessionUserDtoToJSONTyped,
} from './SessionUserDto';

/**
 * 
 * @export
 * @interface AdminGetUserResponseDto
 */
export interface AdminGetUserResponseDto {
    /**
     * User details retrieved successfully
     * @type {SessionUserDto}
     * @memberof AdminGetUserResponseDto
     */
    user: SessionUserDto;
}

/**
 * Check if a given object implements the AdminGetUserResponseDto interface.
 */
export function instanceOfAdminGetUserResponseDto(value: object): value is AdminGetUserResponseDto {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function AdminGetUserResponseDtoFromJSON(json: any): AdminGetUserResponseDto {
    return AdminGetUserResponseDtoFromJSONTyped(json, false);
}

export function AdminGetUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminGetUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'user': SessionUserDtoFromJSON(json['user']),
    };
}

export function AdminGetUserResponseDtoToJSON(json: any): AdminGetUserResponseDto {
    return AdminGetUserResponseDtoToJSONTyped(json, false);
}

export function AdminGetUserResponseDtoToJSONTyped(value?: AdminGetUserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': SessionUserDtoToJSON(value['user']),
    };
}

