/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionUserDto } from './SessionUserDto';
import {
    SessionUserDtoFromJSON,
    SessionUserDtoFromJSONTyped,
    SessionUserDtoToJSON,
    SessionUserDtoToJSONTyped,
} from './SessionUserDto';

/**
 * 
 * @export
 * @interface AdminUpdateUserResponseDto
 */
export interface AdminUpdateUserResponseDto {
    /**
     * User updated successfully
     * @type {SessionUserDto}
     * @memberof AdminUpdateUserResponseDto
     */
    user: SessionUserDto;
}

/**
 * Check if a given object implements the AdminUpdateUserResponseDto interface.
 */
export function instanceOfAdminUpdateUserResponseDto(value: object): value is AdminUpdateUserResponseDto {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function AdminUpdateUserResponseDtoFromJSON(json: any): AdminUpdateUserResponseDto {
    return AdminUpdateUserResponseDtoFromJSONTyped(json, false);
}

export function AdminUpdateUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUpdateUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'user': SessionUserDtoFromJSON(json['user']),
    };
}

export function AdminUpdateUserResponseDtoToJSON(json: any): AdminUpdateUserResponseDto {
    return AdminUpdateUserResponseDtoToJSONTyped(json, false);
}

export function AdminUpdateUserResponseDtoToJSONTyped(value?: AdminUpdateUserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': SessionUserDtoToJSON(value['user']),
    };
}

