/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminGetUserDto
 */
export interface AdminGetUserDto {
    /**
     * The ID of the user to get
     * @type {string}
     * @memberof AdminGetUserDto
     */
    userId: string;
}

/**
 * Check if a given object implements the AdminGetUserDto interface.
 */
export function instanceOfAdminGetUserDto(value: object): value is AdminGetUserDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AdminGetUserDtoFromJSON(json: any): AdminGetUserDto {
    return AdminGetUserDtoFromJSONTyped(json, false);
}

export function AdminGetUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminGetUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function AdminGetUserDtoToJSON(json: any): AdminGetUserDto {
    return AdminGetUserDtoToJSONTyped(json, false);
}

export function AdminGetUserDtoToJSONTyped(value?: AdminGetUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

