/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminListUserSessionsDto
 */
export interface AdminListUserSessionsDto {
    /**
     * The ID of the user whose sessions to list
     * @type {string}
     * @memberof AdminListUserSessionsDto
     */
    userId: string;
}

/**
 * Check if a given object implements the AdminListUserSessionsDto interface.
 */
export function instanceOfAdminListUserSessionsDto(value: object): value is AdminListUserSessionsDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AdminListUserSessionsDtoFromJSON(json: any): AdminListUserSessionsDto {
    return AdminListUserSessionsDtoFromJSONTyped(json, false);
}

export function AdminListUserSessionsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminListUserSessionsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function AdminListUserSessionsDtoToJSON(json: any): AdminListUserSessionsDto {
    return AdminListUserSessionsDtoToJSONTyped(json, false);
}

export function AdminListUserSessionsDtoToJSONTyped(value?: AdminListUserSessionsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

