/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminSetUserPasswordResponseDto
 */
export interface AdminSetUserPasswordResponseDto {
    /**
     * User password set successfully
     * @type {boolean}
     * @memberof AdminSetUserPasswordResponseDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the AdminSetUserPasswordResponseDto interface.
 */
export function instanceOfAdminSetUserPasswordResponseDto(value: object): value is AdminSetUserPasswordResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function AdminSetUserPasswordResponseDtoFromJSON(json: any): AdminSetUserPasswordResponseDto {
    return AdminSetUserPasswordResponseDtoFromJSONTyped(json, false);
}

export function AdminSetUserPasswordResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSetUserPasswordResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function AdminSetUserPasswordResponseDtoToJSON(json: any): AdminSetUserPasswordResponseDto {
    return AdminSetUserPasswordResponseDtoToJSONTyped(json, false);
}

export function AdminSetUserPasswordResponseDtoToJSONTyped(value?: AdminSetUserPasswordResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

