/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminRevokeUserSessionDto
 */
export interface AdminRevokeUserSessionDto {
    /**
     * The ID of the user whose session to revoke
     * @type {string}
     * @memberof AdminRevokeUserSessionDto
     */
    userId: string;
    /**
     * The ID of the session to revoke
     * @type {string}
     * @memberof AdminRevokeUserSessionDto
     */
    sessionId: string;
}

/**
 * Check if a given object implements the AdminRevokeUserSessionDto interface.
 */
export function instanceOfAdminRevokeUserSessionDto(value: object): value is AdminRevokeUserSessionDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    return true;
}

export function AdminRevokeUserSessionDtoFromJSON(json: any): AdminRevokeUserSessionDto {
    return AdminRevokeUserSessionDtoFromJSONTyped(json, false);
}

export function AdminRevokeUserSessionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRevokeUserSessionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'sessionId': json['sessionId'],
    };
}

export function AdminRevokeUserSessionDtoToJSON(json: any): AdminRevokeUserSessionDto {
    return AdminRevokeUserSessionDtoToJSONTyped(json, false);
}

export function AdminRevokeUserSessionDtoToJSONTyped(value?: AdminRevokeUserSessionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'sessionId': value['sessionId'],
    };
}

