/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsSummaryDto
 */
export interface AnalyticsSummaryDto {
    /**
     * Current merchant balance in cents/smallest unit
     * @type {number}
     * @memberof AnalyticsSummaryDto
     */
    balance: number;
    /**
     * Total number of customers
     * @type {number}
     * @memberof AnalyticsSummaryDto
     */
    customers: number;
    /**
     * Total number of transactions
     * @type {number}
     * @memberof AnalyticsSummaryDto
     */
    transactions: number;
    /**
     * Total number of organization members
     * @type {number}
     * @memberof AnalyticsSummaryDto
     */
    members: number;
}

/**
 * Check if a given object implements the AnalyticsSummaryDto interface.
 */
export function instanceOfAnalyticsSummaryDto(value: object): value is AnalyticsSummaryDto {
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('customers' in value) || value['customers'] === undefined) return false;
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    if (!('members' in value) || value['members'] === undefined) return false;
    return true;
}

export function AnalyticsSummaryDtoFromJSON(json: any): AnalyticsSummaryDto {
    return AnalyticsSummaryDtoFromJSONTyped(json, false);
}

export function AnalyticsSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'balance': json['balance'],
        'customers': json['customers'],
        'transactions': json['transactions'],
        'members': json['members'],
    };
}

export function AnalyticsSummaryDtoToJSON(json: any): AnalyticsSummaryDto {
    return AnalyticsSummaryDtoToJSONTyped(json, false);
}

export function AnalyticsSummaryDtoToJSONTyped(value?: AnalyticsSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'balance': value['balance'],
        'customers': value['customers'],
        'transactions': value['transactions'],
        'members': value['members'],
    };
}

