/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeframeMetricsDto } from './TimeframeMetricsDto';
import {
    TimeframeMetricsDtoFromJSON,
    TimeframeMetricsDtoFromJSONTyped,
    TimeframeMetricsDtoToJSON,
    TimeframeMetricsDtoToJSONTyped,
} from './TimeframeMetricsDto';
import type { CustomerTransactionDto } from './CustomerTransactionDto';
import {
    CustomerTransactionDtoFromJSON,
    CustomerTransactionDtoFromJSONTyped,
    CustomerTransactionDtoToJSON,
    CustomerTransactionDtoToJSONTyped,
} from './CustomerTransactionDto';
import type { CustomerStatsDto } from './CustomerStatsDto';
import {
    CustomerStatsDtoFromJSON,
    CustomerStatsDtoFromJSONTyped,
    CustomerStatsDtoToJSON,
    CustomerStatsDtoToJSONTyped,
} from './CustomerStatsDto';

/**
 * 
 * @export
 * @interface AnalyticsResponseDto
 */
export interface AnalyticsResponseDto {
    /**
     * 
     * @type {TimeframeMetricsDto}
     * @memberof AnalyticsResponseDto
     */
    transactions: TimeframeMetricsDto;
    /**
     * 
     * @type {CustomerStatsDto}
     * @memberof AnalyticsResponseDto
     */
    newCustomers: CustomerStatsDto;
    /**
     * The 5 most recent transactions
     * @type {Array<CustomerTransactionDto>}
     * @memberof AnalyticsResponseDto
     */
    recentTransactions: Array<CustomerTransactionDto>;
}

/**
 * Check if a given object implements the AnalyticsResponseDto interface.
 */
export function instanceOfAnalyticsResponseDto(value: object): value is AnalyticsResponseDto {
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    if (!('newCustomers' in value) || value['newCustomers'] === undefined) return false;
    if (!('recentTransactions' in value) || value['recentTransactions'] === undefined) return false;
    return true;
}

export function AnalyticsResponseDtoFromJSON(json: any): AnalyticsResponseDto {
    return AnalyticsResponseDtoFromJSONTyped(json, false);
}

export function AnalyticsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'transactions': TimeframeMetricsDtoFromJSON(json['transactions']),
        'newCustomers': CustomerStatsDtoFromJSON(json['newCustomers']),
        'recentTransactions': ((json['recentTransactions'] as Array<any>).map(CustomerTransactionDtoFromJSON)),
    };
}

export function AnalyticsResponseDtoToJSON(json: any): AnalyticsResponseDto {
    return AnalyticsResponseDtoToJSONTyped(json, false);
}

export function AnalyticsResponseDtoToJSONTyped(value?: AnalyticsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactions': TimeframeMetricsDtoToJSON(value['transactions']),
        'newCustomers': CustomerStatsDtoToJSON(value['newCustomers']),
        'recentTransactions': ((value['recentTransactions'] as Array<any>).map(CustomerTransactionDtoToJSON)),
    };
}

