/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BadRequestResponseDto
 */
export interface BadRequestResponseDto {
    /**
     * HTTP status code
     * @type {number}
     * @memberof BadRequestResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof BadRequestResponseDto
     */
    message: Array<string>;
    /**
     * Error type
     * @type {string}
     * @memberof BadRequestResponseDto
     */
    error: string;
}

/**
 * Check if a given object implements the BadRequestResponseDto interface.
 */
export function instanceOfBadRequestResponseDto(value: object): value is BadRequestResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function BadRequestResponseDtoFromJSON(json: any): BadRequestResponseDto {
    return BadRequestResponseDtoFromJSONTyped(json, false);
}

export function BadRequestResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadRequestResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'error': json['error'],
    };
}

export function BadRequestResponseDtoToJSON(json: any): BadRequestResponseDto {
    return BadRequestResponseDtoToJSONTyped(json, false);
}

export function BadRequestResponseDtoToJSONTyped(value?: BadRequestResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'error': value['error'],
    };
}

