/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BanUserResponseDto
 */
export interface BanUserResponseDto {
    /**
     * User banned successfully
     * @type {boolean}
     * @memberof BanUserResponseDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the BanUserResponseDto interface.
 */
export function instanceOfBanUserResponseDto(value: object): value is BanUserResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function BanUserResponseDtoFromJSON(json: any): BanUserResponseDto {
    return BanUserResponseDtoFromJSONTyped(json, false);
}

export function BanUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BanUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function BanUserResponseDtoToJSON(json: any): BanUserResponseDto {
    return BanUserResponseDtoToJSONTyped(json, false);
}

export function BanUserResponseDtoToJSONTyped(value?: BanUserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

