/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BanUserDto
 */
export interface BanUserDto {
    /**
     * The ID of the user to ban
     * @type {string}
     * @memberof BanUserDto
     */
    userId: string;
    /**
     * The reason for the ban
     * @type {string}
     * @memberof BanUserDto
     */
    banReason?: string;
    /**
     * Ban duration in seconds
     * @type {number}
     * @memberof BanUserDto
     */
    banExpiresIn?: number;
}

/**
 * Check if a given object implements the BanUserDto interface.
 */
export function instanceOfBanUserDto(value: object): value is BanUserDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function BanUserDtoFromJSON(json: any): BanUserDto {
    return BanUserDtoFromJSONTyped(json, false);
}

export function BanUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BanUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'banReason': json['banReason'] == null ? undefined : json['banReason'],
        'banExpiresIn': json['banExpiresIn'] == null ? undefined : json['banExpiresIn'],
    };
}

export function BanUserDtoToJSON(json: any): BanUserDto {
    return BanUserDtoToJSONTyped(json, false);
}

export function BanUserDtoToJSONTyped(value?: BanUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'banReason': value['banReason'],
        'banExpiresIn': value['banExpiresIn'],
    };
}

