/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseDto
 */
export interface BaseDto {
    /**
     * Unique identifier
     * @type {string}
     * @memberof BaseDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof BaseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof BaseDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof BaseDto
     */
    deletedAt?: Date;
}

/**
 * Check if a given object implements the BaseDto interface.
 */
export function instanceOfBaseDto(value: object): value is BaseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function BaseDtoFromJSON(json: any): BaseDto {
    return BaseDtoFromJSONTyped(json, false);
}

export function BaseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
    };
}

export function BaseDtoToJSON(json: any): BaseDto {
    return BaseDtoToJSONTyped(json, false);
}

export function BaseDtoToJSONTyped(value?: BaseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'deletedAt': value['deletedAt'] == null ? value['deletedAt'] : value['deletedAt'].toISOString(),
    };
}

