/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkIdsDto
 */
export interface BulkIdsDto {
    /**
     * List of IDs to target
     * @type {Array<string>}
     * @memberof BulkIdsDto
     */
    ids: Array<string>;
}

/**
 * Check if a given object implements the BulkIdsDto interface.
 */
export function instanceOfBulkIdsDto(value: object): value is BulkIdsDto {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function BulkIdsDtoFromJSON(json: any): BulkIdsDto {
    return BulkIdsDtoFromJSONTyped(json, false);
}

export function BulkIdsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkIdsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
    };
}

export function BulkIdsDtoToJSON(json: any): BulkIdsDto {
    return BulkIdsDtoToJSONTyped(json, false);
}

export function BulkIdsDtoToJSONTyped(value?: BulkIdsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
    };
}

