/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelInvitationResponseDto
 */
export interface CancelInvitationResponseDto {
    /**
     * Invitation cancelled successfully
     * @type {boolean}
     * @memberof CancelInvitationResponseDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the CancelInvitationResponseDto interface.
 */
export function instanceOfCancelInvitationResponseDto(value: object): value is CancelInvitationResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function CancelInvitationResponseDtoFromJSON(json: any): CancelInvitationResponseDto {
    return CancelInvitationResponseDtoFromJSONTyped(json, false);
}

export function CancelInvitationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelInvitationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function CancelInvitationResponseDtoToJSON(json: any): CancelInvitationResponseDto {
    return CancelInvitationResponseDtoToJSONTyped(json, false);
}

export function CancelInvitationResponseDtoToJSONTyped(value?: CancelInvitationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

