/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordDto
 */
export interface ChangePasswordDto {
    /**
     * The new password to set
     * @type {string}
     * @memberof ChangePasswordDto
     */
    newPassword: string;
    /**
     * The current password is required
     * @type {string}
     * @memberof ChangePasswordDto
     */
    currentPassword: string;
    /**
     * Must be a boolean value
     * @type {boolean}
     * @memberof ChangePasswordDto
     */
    revokeOtherSessions?: boolean;
}

/**
 * Check if a given object implements the ChangePasswordDto interface.
 */
export function instanceOfChangePasswordDto(value: object): value is ChangePasswordDto {
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    return true;
}

export function ChangePasswordDtoFromJSON(json: any): ChangePasswordDto {
    return ChangePasswordDtoFromJSONTyped(json, false);
}

export function ChangePasswordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'newPassword': json['newPassword'],
        'currentPassword': json['currentPassword'],
        'revokeOtherSessions': json['revokeOtherSessions'] == null ? undefined : json['revokeOtherSessions'],
    };
}

export function ChangePasswordDtoToJSON(json: any): ChangePasswordDto {
    return ChangePasswordDtoToJSONTyped(json, false);
}

export function ChangePasswordDtoToJSONTyped(value?: ChangePasswordDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newPassword': value['newPassword'],
        'currentPassword': value['currentPassword'],
        'revokeOtherSessions': value['revokeOtherSessions'],
    };
}

