/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionUserDto } from './SessionUserDto';
import {
    SessionUserDtoFromJSON,
    SessionUserDtoFromJSONTyped,
    SessionUserDtoToJSON,
    SessionUserDtoToJSONTyped,
} from './SessionUserDto';

/**
 * 
 * @export
 * @interface ChangeEmailResponseDto
 */
export interface ChangeEmailResponseDto {
    /**
     * Indicates if request was successful
     * @type {boolean}
     * @memberof ChangeEmailResponseDto
     */
    status: boolean;
    /**
     * Status message of email change process
     * @type {string}
     * @memberof ChangeEmailResponseDto
     */
    message?: ChangeEmailResponseDtoMessageEnum;
    /**
     * User object
     * @type {SessionUserDto}
     * @memberof ChangeEmailResponseDto
     */
    user?: SessionUserDto;
}


/**
 * @export
 */
export const ChangeEmailResponseDtoMessageEnum = {
    EmailUpdated: 'Email updated',
    VerificationEmailSent: 'Verification email sent'
} as const;
export type ChangeEmailResponseDtoMessageEnum = typeof ChangeEmailResponseDtoMessageEnum[keyof typeof ChangeEmailResponseDtoMessageEnum];


/**
 * Check if a given object implements the ChangeEmailResponseDto interface.
 */
export function instanceOfChangeEmailResponseDto(value: object): value is ChangeEmailResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ChangeEmailResponseDtoFromJSON(json: any): ChangeEmailResponseDto {
    return ChangeEmailResponseDtoFromJSONTyped(json, false);
}

export function ChangeEmailResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeEmailResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'user': json['user'] == null ? undefined : SessionUserDtoFromJSON(json['user']),
    };
}

export function ChangeEmailResponseDtoToJSON(json: any): ChangeEmailResponseDto {
    return ChangeEmailResponseDtoToJSONTyped(json, false);
}

export function ChangeEmailResponseDtoToJSONTyped(value?: ChangeEmailResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'user': SessionUserDtoToJSON(value['user']),
    };
}

