/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckSlugResponseDto
 */
export interface CheckSlugResponseDto {
    /**
     * Whether slug is available
     * @type {boolean}
     * @memberof CheckSlugResponseDto
     */
    available: boolean;
}

/**
 * Check if a given object implements the CheckSlugResponseDto interface.
 */
export function instanceOfCheckSlugResponseDto(value: object): value is CheckSlugResponseDto {
    if (!('available' in value) || value['available'] === undefined) return false;
    return true;
}

export function CheckSlugResponseDtoFromJSON(json: any): CheckSlugResponseDto {
    return CheckSlugResponseDtoFromJSONTyped(json, false);
}

export function CheckSlugResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckSlugResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'available': json['available'],
    };
}

export function CheckSlugResponseDtoToJSON(json: any): CheckSlugResponseDto {
    return CheckSlugResponseDtoToJSONTyped(json, false);
}

export function CheckSlugResponseDtoToJSONTyped(value?: CheckSlugResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available': value['available'],
    };
}

