/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckoutSessionConfirmResponseDto
 */
export interface CheckoutSessionConfirmResponseDto {
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionConfirmResponseDto
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionConfirmResponseDto
     */
    paymentIntentId: string;
    /**
     * 
     * @type {object}
     * @memberof CheckoutSessionConfirmResponseDto
     */
    iveriParams: object;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionConfirmResponseDto
     */
    iVeri3dsEndpoint: string;
}

/**
 * Check if a given object implements the CheckoutSessionConfirmResponseDto interface.
 */
export function instanceOfCheckoutSessionConfirmResponseDto(value: object): value is CheckoutSessionConfirmResponseDto {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('paymentIntentId' in value) || value['paymentIntentId'] === undefined) return false;
    if (!('iveriParams' in value) || value['iveriParams'] === undefined) return false;
    if (!('iVeri3dsEndpoint' in value) || value['iVeri3dsEndpoint'] === undefined) return false;
    return true;
}

export function CheckoutSessionConfirmResponseDtoFromJSON(json: any): CheckoutSessionConfirmResponseDto {
    return CheckoutSessionConfirmResponseDtoFromJSONTyped(json, false);
}

export function CheckoutSessionConfirmResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionConfirmResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'paymentIntentId': json['paymentIntentId'],
        'iveriParams': json['iveriParams'],
        'iVeri3dsEndpoint': json['iVeri3dsEndpoint'],
    };
}

export function CheckoutSessionConfirmResponseDtoToJSON(json: any): CheckoutSessionConfirmResponseDto {
    return CheckoutSessionConfirmResponseDtoToJSONTyped(json, false);
}

export function CheckoutSessionConfirmResponseDtoToJSONTyped(value?: CheckoutSessionConfirmResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
        'paymentIntentId': value['paymentIntentId'],
        'iveriParams': value['iveriParams'],
        'iVeri3dsEndpoint': value['iVeri3dsEndpoint'],
    };
}

