/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckSlugDto
 */
export interface CheckSlugDto {
    /**
     * The organization slug to check
     * @type {string}
     * @memberof CheckSlugDto
     */
    slug: string;
}

/**
 * Check if a given object implements the CheckSlugDto interface.
 */
export function instanceOfCheckSlugDto(value: object): value is CheckSlugDto {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function CheckSlugDtoFromJSON(json: any): CheckSlugDto {
    return CheckSlugDtoFromJSONTyped(json, false);
}

export function CheckSlugDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckSlugDto {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
    };
}

export function CheckSlugDtoToJSON(json: any): CheckSlugDto {
    return CheckSlugDtoToJSONTyped(json, false);
}

export function CheckSlugDtoToJSONTyped(value?: CheckSlugDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
    };
}

