/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LineItemDto } from './LineItemDto';
import {
    LineItemDtoFromJSON,
    LineItemDtoFromJSONTyped,
    LineItemDtoToJSON,
    LineItemDtoToJSONTyped,
} from './LineItemDto';

/**
 * 
 * @export
 * @interface CheckoutSessionResponseDto
 */
export interface CheckoutSessionResponseDto {
    /**
     * Unique identifier
     * @type {string}
     * @memberof CheckoutSessionResponseDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof CheckoutSessionResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CheckoutSessionResponseDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CheckoutSessionResponseDto
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionResponseDto
     */
    merchantId: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionResponseDto
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionResponseDto
     */
    sessionUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionResponseDto
     */
    successUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionResponseDto
     */
    cancelUrl: string;
    /**
     * 
     * @type {Array<LineItemDto>}
     * @memberof CheckoutSessionResponseDto
     */
    lineItems?: Array<LineItemDto>;
    /**
     * 
     * @type {number}
     * @memberof CheckoutSessionResponseDto
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionResponseDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionResponseDto
     */
    mode?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionResponseDto
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof CheckoutSessionResponseDto
     */
    expiresAt?: Date;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CheckoutSessionResponseDto
     */
    metadata: { [key: string]: any; };
}

/**
 * Check if a given object implements the CheckoutSessionResponseDto interface.
 */
export function instanceOfCheckoutSessionResponseDto(value: object): value is CheckoutSessionResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('sessionUrl' in value) || value['sessionUrl'] === undefined) return false;
    if (!('successUrl' in value) || value['successUrl'] === undefined) return false;
    if (!('cancelUrl' in value) || value['cancelUrl'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function CheckoutSessionResponseDtoFromJSON(json: any): CheckoutSessionResponseDto {
    return CheckoutSessionResponseDtoFromJSONTyped(json, false);
}

export function CheckoutSessionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'merchantId': json['merchantId'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'sessionUrl': json['sessionUrl'],
        'successUrl': json['successUrl'],
        'cancelUrl': json['cancelUrl'],
        'lineItems': json['lineItems'] == null ? undefined : ((json['lineItems'] as Array<any>).map(LineItemDtoFromJSON)),
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'currency': json['currency'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'status': json['status'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'metadata': json['metadata'],
    };
}

export function CheckoutSessionResponseDtoToJSON(json: any): CheckoutSessionResponseDto {
    return CheckoutSessionResponseDtoToJSONTyped(json, false);
}

export function CheckoutSessionResponseDtoToJSONTyped(value?: CheckoutSessionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'deletedAt': value['deletedAt'] == null ? value['deletedAt'] : value['deletedAt'].toISOString(),
        'merchantId': value['merchantId'],
        'customerId': value['customerId'],
        'sessionUrl': value['sessionUrl'],
        'successUrl': value['successUrl'],
        'cancelUrl': value['cancelUrl'],
        'lineItems': value['lineItems'] == null ? undefined : ((value['lineItems'] as Array<any>).map(LineItemDtoToJSON)),
        'totalAmount': value['totalAmount'],
        'currency': value['currency'],
        'mode': value['mode'],
        'status': value['status'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'metadata': value['metadata'],
    };
}

