/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.1
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EvervaultEncryptedCardDto } from './EvervaultEncryptedCardDto';
import {
    EvervaultEncryptedCardDtoFromJSON,
    EvervaultEncryptedCardDtoFromJSONTyped,
    EvervaultEncryptedCardDtoToJSON,
    EvervaultEncryptedCardDtoToJSONTyped,
} from './EvervaultEncryptedCardDto';

/**
 * 
 * @export
 * @interface ConfirmPaymentIntentDto
 */
export interface ConfirmPaymentIntentDto {
    /**
     * Evervault encrypted card details
     * @type {EvervaultEncryptedCardDto}
     * @memberof ConfirmPaymentIntentDto
     */
    evervaultEncryptedCard: EvervaultEncryptedCardDto;
    /**
     * Masked PAN for display purposes
     * @type {string}
     * @memberof ConfirmPaymentIntentDto
     */
    maskedPan?: string;
    /**
     * Whether to tokenize the card for future use
     * @type {boolean}
     * @memberof ConfirmPaymentIntentDto
     */
    tokenizeCard?: boolean;
    /**
     * Cardholder first name
     * @type {string}
     * @memberof ConfirmPaymentIntentDto
     */
    firstName?: string;
    /**
     * Cardholder last name
     * @type {string}
     * @memberof ConfirmPaymentIntentDto
     */
    lastName?: string;
    /**
     * Cardholder phone number
     * @type {string}
     * @memberof ConfirmPaymentIntentDto
     */
    phoneNumber?: string;
    /**
     * Payment description
     * @type {string}
     * @memberof ConfirmPaymentIntentDto
     */
    paymentDescription?: string;
    /**
     * Merchant name for display
     * @type {string}
     * @memberof ConfirmPaymentIntentDto
     */
    merchantName?: string;
    /**
     * Additional metadata
     * @type {{ [key: string]: any; }}
     * @memberof ConfirmPaymentIntentDto
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the ConfirmPaymentIntentDto interface.
 */
export function instanceOfConfirmPaymentIntentDto(value: object): value is ConfirmPaymentIntentDto {
    if (!('evervaultEncryptedCard' in value) || value['evervaultEncryptedCard'] === undefined) return false;
    return true;
}

export function ConfirmPaymentIntentDtoFromJSON(json: any): ConfirmPaymentIntentDto {
    return ConfirmPaymentIntentDtoFromJSONTyped(json, false);
}

export function ConfirmPaymentIntentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmPaymentIntentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'evervaultEncryptedCard': EvervaultEncryptedCardDtoFromJSON(json['evervaultEncryptedCard']),
        'maskedPan': json['maskedPan'] == null ? undefined : json['maskedPan'],
        'tokenizeCard': json['tokenizeCard'] == null ? undefined : json['tokenizeCard'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'paymentDescription': json['paymentDescription'] == null ? undefined : json['paymentDescription'],
        'merchantName': json['merchantName'] == null ? undefined : json['merchantName'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ConfirmPaymentIntentDtoToJSON(json: any): ConfirmPaymentIntentDto {
    return ConfirmPaymentIntentDtoToJSONTyped(json, false);
}

export function ConfirmPaymentIntentDtoToJSONTyped(value?: ConfirmPaymentIntentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'evervaultEncryptedCard': EvervaultEncryptedCardDtoToJSON(value['evervaultEncryptedCard']),
        'maskedPan': value['maskedPan'],
        'tokenizeCard': value['tokenizeCard'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'phoneNumber': value['phoneNumber'],
        'paymentDescription': value['paymentDescription'],
        'merchantName': value['merchantName'],
        'metadata': value['metadata'],
    };
}

