/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.1
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentIntentResponseDto } from './PaymentIntentResponseDto';
import {
    PaymentIntentResponseDtoFromJSON,
    PaymentIntentResponseDtoFromJSONTyped,
    PaymentIntentResponseDtoToJSON,
    PaymentIntentResponseDtoToJSONTyped,
} from './PaymentIntentResponseDto';

/**
 * 
 * @export
 * @interface ConfirmPaymentIntentResponseDto
 */
export interface ConfirmPaymentIntentResponseDto {
    /**
     * 
     * @type {PaymentIntentResponseDto}
     * @memberof ConfirmPaymentIntentResponseDto
     */
    paymentIntent: PaymentIntentResponseDto;
    /**
     * 
     * @type {object}
     * @memberof ConfirmPaymentIntentResponseDto
     */
    iveriParams?: object;
    /**
     * 
     * @type {string}
     * @memberof ConfirmPaymentIntentResponseDto
     */
    iVeri3dsEndpoint?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConfirmPaymentIntentResponseDto
     */
    sandboxMode?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfirmPaymentIntentResponseDto
     */
    status?: ConfirmPaymentIntentResponseDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ConfirmPaymentIntentResponseDto
     */
    transactionId?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmPaymentIntentResponseDto
     */
    authCode?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfirmPaymentIntentResponseDto
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfirmPaymentIntentResponseDto
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmPaymentIntentResponseDto
     */
    reason?: string;
}


/**
 * @export
 */
export const ConfirmPaymentIntentResponseDtoStatusEnum = {
    Succeeded: 'succeeded',
    Failed: 'failed'
} as const;
export type ConfirmPaymentIntentResponseDtoStatusEnum = typeof ConfirmPaymentIntentResponseDtoStatusEnum[keyof typeof ConfirmPaymentIntentResponseDtoStatusEnum];


/**
 * Check if a given object implements the ConfirmPaymentIntentResponseDto interface.
 */
export function instanceOfConfirmPaymentIntentResponseDto(value: object): value is ConfirmPaymentIntentResponseDto {
    if (!('paymentIntent' in value) || value['paymentIntent'] === undefined) return false;
    return true;
}

export function ConfirmPaymentIntentResponseDtoFromJSON(json: any): ConfirmPaymentIntentResponseDto {
    return ConfirmPaymentIntentResponseDtoFromJSONTyped(json, false);
}

export function ConfirmPaymentIntentResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmPaymentIntentResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentIntent': PaymentIntentResponseDtoFromJSON(json['paymentIntent']),
        'iveriParams': json['iveriParams'] == null ? undefined : json['iveriParams'],
        'iVeri3dsEndpoint': json['iVeri3dsEndpoint'] == null ? undefined : json['iVeri3dsEndpoint'],
        'sandboxMode': json['sandboxMode'] == null ? undefined : json['sandboxMode'],
        'status': json['status'] == null ? undefined : json['status'],
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
        'authCode': json['authCode'] == null ? undefined : json['authCode'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function ConfirmPaymentIntentResponseDtoToJSON(json: any): ConfirmPaymentIntentResponseDto {
    return ConfirmPaymentIntentResponseDtoToJSONTyped(json, false);
}

export function ConfirmPaymentIntentResponseDtoToJSONTyped(value?: ConfirmPaymentIntentResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentIntent': PaymentIntentResponseDtoToJSON(value['paymentIntent']),
        'iveriParams': value['iveriParams'],
        'iVeri3dsEndpoint': value['iVeri3dsEndpoint'],
        'sandboxMode': value['sandboxMode'],
        'status': value['status'],
        'transactionId': value['transactionId'],
        'authCode': value['authCode'],
        'amount': value['amount'],
        'currency': value['currency'],
        'reason': value['reason'],
    };
}

