/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCustomerDto
 */
export interface CreateCustomerDto {
    /**
     * The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.
     * @type {string}
     * @memberof CreateCustomerDto
     */
    merchantId?: string;
    /**
     * The email address of the customer
     * @type {string}
     * @memberof CreateCustomerDto
     */
    email: string;
    /**
     * The full name of the customer
     * @type {string}
     * @memberof CreateCustomerDto
     */
    name?: string;
    /**
     * Optional custom metadata
     * @type {{ [key: string]: any; }}
     * @memberof CreateCustomerDto
     */
    metadata: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateCustomerDto interface.
 */
export function instanceOfCreateCustomerDto(value: object): value is CreateCustomerDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function CreateCustomerDtoFromJSON(json: any): CreateCustomerDto {
    return CreateCustomerDtoFromJSONTyped(json, false);
}

export function CreateCustomerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'merchantId': json['merchantId'] == null ? undefined : json['merchantId'],
        'email': json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'metadata': json['metadata'],
    };
}

export function CreateCustomerDtoToJSON(json: any): CreateCustomerDto {
    return CreateCustomerDtoToJSONTyped(json, false);
}

export function CreateCustomerDtoToJSONTyped(value?: CreateCustomerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'merchantId': value['merchantId'],
        'email': value['email'],
        'name': value['name'],
        'metadata': value['metadata'],
    };
}

