/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.1
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEventTypeDto
 */
export interface CreateEventTypeDto {
    /**
     * Name of the event type
     * @type {string}
     * @memberof CreateEventTypeDto
     */
    name: string;
    /**
     * Description of the event type
     * @type {string}
     * @memberof CreateEventTypeDto
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateEventTypeDto interface.
 */
export function instanceOfCreateEventTypeDto(value: object): value is CreateEventTypeDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateEventTypeDtoFromJSON(json: any): CreateEventTypeDto {
    return CreateEventTypeDtoFromJSONTyped(json, false);
}

export function CreateEventTypeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEventTypeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateEventTypeDtoToJSON(json: any): CreateEventTypeDto {
    return CreateEventTypeDtoToJSONTyped(json, false);
}

export function CreateEventTypeDtoToJSONTyped(value?: CreateEventTypeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

