/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.1
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEventDto
 */
export interface CreateEventDto {
    /**
     * Merchant ID associated with the event
     * @type {string}
     * @memberof CreateEventDto
     */
    merchantId: string;
    /**
     * Event type identifier (e.g., 'checkout.loaded')
     * @type {string}
     * @memberof CreateEventDto
     */
    type: string;
    /**
     * Event payload data
     * @type {object}
     * @memberof CreateEventDto
     */
    data: object;
    /**
     * ID of the related entity
     * @type {string}
     * @memberof CreateEventDto
     */
    relatedEntityId?: string;
    /**
     * Type of the related entity
     * @type {string}
     * @memberof CreateEventDto
     */
    relatedEntityType?: string;
}

/**
 * Check if a given object implements the CreateEventDto interface.
 */
export function instanceOfCreateEventDto(value: object): value is CreateEventDto {
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateEventDtoFromJSON(json: any): CreateEventDto {
    return CreateEventDtoFromJSONTyped(json, false);
}

export function CreateEventDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEventDto {
    if (json == null) {
        return json;
    }
    return {
        
        'merchantId': json['merchantId'],
        'type': json['type'],
        'data': json['data'],
        'relatedEntityId': json['relatedEntityId'] == null ? undefined : json['relatedEntityId'],
        'relatedEntityType': json['relatedEntityType'] == null ? undefined : json['relatedEntityType'],
    };
}

export function CreateEventDtoToJSON(json: any): CreateEventDto {
    return CreateEventDtoToJSONTyped(json, false);
}

export function CreateEventDtoToJSONTyped(value?: CreateEventDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'merchantId': value['merchantId'],
        'type': value['type'],
        'data': value['data'],
        'relatedEntityId': value['relatedEntityId'],
        'relatedEntityType': value['relatedEntityType'],
    };
}

