/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePayoutDto
 */
export interface CreatePayoutDto {
    /**
     * The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.
     * @type {string}
     * @memberof CreatePayoutDto
     */
    merchantId?: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePayoutDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePayoutDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePayoutDto
     */
    bankAccount?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePayoutDto
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreatePayoutDto
     */
    metadata: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreatePayoutDto interface.
 */
export function instanceOfCreatePayoutDto(value: object): value is CreatePayoutDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function CreatePayoutDtoFromJSON(json: any): CreatePayoutDto {
    return CreatePayoutDtoFromJSONTyped(json, false);
}

export function CreatePayoutDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePayoutDto {
    if (json == null) {
        return json;
    }
    return {
        
        'merchantId': json['merchantId'] == null ? undefined : json['merchantId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'bankAccount': json['bankAccount'] == null ? undefined : json['bankAccount'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'],
    };
}

export function CreatePayoutDtoToJSON(json: any): CreatePayoutDto {
    return CreatePayoutDtoToJSONTyped(json, false);
}

export function CreatePayoutDtoToJSONTyped(value?: CreatePayoutDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'merchantId': value['merchantId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'bankAccount': value['bankAccount'],
        'description': value['description'],
        'metadata': value['metadata'],
    };
}

