/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKey } from './ApiKey';
import {
    ApiKeyFromJSON,
    ApiKeyFromJSONTyped,
    ApiKeyToJSON,
    ApiKeyToJSONTyped,
} from './ApiKey';

/**
 * 
 * @export
 * @interface CreateApiKeyResponseDto
 */
export interface CreateApiKeyResponseDto {
    /**
     * API key created successfully
     * @type {ApiKey}
     * @memberof CreateApiKeyResponseDto
     */
    apiKey: ApiKey;
}

/**
 * Check if a given object implements the CreateApiKeyResponseDto interface.
 */
export function instanceOfCreateApiKeyResponseDto(value: object): value is CreateApiKeyResponseDto {
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    return true;
}

export function CreateApiKeyResponseDtoFromJSON(json: any): CreateApiKeyResponseDto {
    return CreateApiKeyResponseDtoFromJSONTyped(json, false);
}

export function CreateApiKeyResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiKeyResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': ApiKeyFromJSON(json['apiKey']),
    };
}

export function CreateApiKeyResponseDtoToJSON(json: any): CreateApiKeyResponseDto {
    return CreateApiKeyResponseDtoToJSONTyped(json, false);
}

export function CreateApiKeyResponseDtoToJSONTyped(value?: CreateApiKeyResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiKey': ApiKeyToJSON(value['apiKey']),
    };
}

