/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWebhookEndpointDto
 */
export interface CreateWebhookEndpointDto {
    /**
     * The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.
     * @type {string}
     * @memberof CreateWebhookEndpointDto
     */
    merchantId?: string;
    /**
     * The URL where webhook events will be sent
     * @type {string}
     * @memberof CreateWebhookEndpointDto
     */
    url: string;
    /**
     * Array of event types to listen for
     * @type {Array<string>}
     * @memberof CreateWebhookEndpointDto
     */
    events: Array<string>;
    /**
     * Optional custom metadata
     * @type {{ [key: string]: any; }}
     * @memberof CreateWebhookEndpointDto
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateWebhookEndpointDto interface.
 */
export function instanceOfCreateWebhookEndpointDto(value: object): value is CreateWebhookEndpointDto {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function CreateWebhookEndpointDtoFromJSON(json: any): CreateWebhookEndpointDto {
    return CreateWebhookEndpointDtoFromJSONTyped(json, false);
}

export function CreateWebhookEndpointDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookEndpointDto {
    if (json == null) {
        return json;
    }
    return {
        
        'merchantId': json['merchantId'] == null ? undefined : json['merchantId'],
        'url': json['url'],
        'events': json['events'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateWebhookEndpointDtoToJSON(json: any): CreateWebhookEndpointDto {
    return CreateWebhookEndpointDtoToJSONTyped(json, false);
}

export function CreateWebhookEndpointDtoToJSONTyped(value?: CreateWebhookEndpointDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'merchantId': value['merchantId'],
        'url': value['url'],
        'events': value['events'],
        'metadata': value['metadata'],
    };
}

