/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePurchaseDto
 */
export interface CreatePurchaseDto {
    /**
     * The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.
     * @type {string}
     * @memberof CreatePurchaseDto
     */
    merchantId?: string;
    /**
     * The unique identifier of the customer
     * @type {string}
     * @memberof CreatePurchaseDto
     */
    customerId: string;
    /**
     * The unique identifier of the product
     * @type {string}
     * @memberof CreatePurchaseDto
     */
    productId: string;
    /**
     * The amount in the smallest currency unit
     * @type {number}
     * @memberof CreatePurchaseDto
     */
    amount: number;
    /**
     * The three-letter ISO 4217 currency code
     * @type {string}
     * @memberof CreatePurchaseDto
     */
    currency: string;
    /**
     * The quantity of items in the purchase
     * @type {number}
     * @memberof CreatePurchaseDto
     */
    quantity?: number;
}

/**
 * Check if a given object implements the CreatePurchaseDto interface.
 */
export function instanceOfCreatePurchaseDto(value: object): value is CreatePurchaseDto {
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function CreatePurchaseDtoFromJSON(json: any): CreatePurchaseDto {
    return CreatePurchaseDtoFromJSONTyped(json, false);
}

export function CreatePurchaseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePurchaseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'merchantId': json['merchantId'] == null ? undefined : json['merchantId'],
        'customerId': json['customerId'],
        'productId': json['productId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function CreatePurchaseDtoToJSON(json: any): CreatePurchaseDto {
    return CreatePurchaseDtoToJSONTyped(json, false);
}

export function CreatePurchaseDtoToJSONTyped(value?: CreatePurchaseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'merchantId': value['merchantId'],
        'customerId': value['customerId'],
        'productId': value['productId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'quantity': value['quantity'],
    };
}

