/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationDto } from './OrganizationDto';
import {
    OrganizationDtoFromJSON,
    OrganizationDtoFromJSONTyped,
    OrganizationDtoToJSON,
    OrganizationDtoToJSONTyped,
} from './OrganizationDto';

/**
 * 
 * @export
 * @interface CreateOrganizationResponseDto
 */
export interface CreateOrganizationResponseDto {
    /**
     * Organization created successfully
     * @type {OrganizationDto}
     * @memberof CreateOrganizationResponseDto
     */
    organization: OrganizationDto;
}

/**
 * Check if a given object implements the CreateOrganizationResponseDto interface.
 */
export function instanceOfCreateOrganizationResponseDto(value: object): value is CreateOrganizationResponseDto {
    if (!('organization' in value) || value['organization'] === undefined) return false;
    return true;
}

export function CreateOrganizationResponseDtoFromJSON(json: any): CreateOrganizationResponseDto {
    return CreateOrganizationResponseDtoFromJSONTyped(json, false);
}

export function CreateOrganizationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'organization': OrganizationDtoFromJSON(json['organization']),
    };
}

export function CreateOrganizationResponseDtoToJSON(json: any): CreateOrganizationResponseDto {
    return CreateOrganizationResponseDtoToJSONTyped(json, false);
}

export function CreateOrganizationResponseDtoToJSONTyped(value?: CreateOrganizationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization': OrganizationDtoToJSON(value['organization']),
    };
}

