/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerBalanceDto
 */
export interface CustomerBalanceDto {
    /**
     * Unique identifier
     * @type {string}
     * @memberof CustomerBalanceDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomerBalanceDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerBalanceDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerBalanceDto
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomerBalanceDto
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerBalanceDto
     */
    merchantId?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerBalanceDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerBalanceDto
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerBalanceDto
     */
    available: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerBalanceDto
     */
    pending: number;
}

/**
 * Check if a given object implements the CustomerBalanceDto interface.
 */
export function instanceOfCustomerBalanceDto(value: object): value is CustomerBalanceDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('available' in value) || value['available'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    return true;
}

export function CustomerBalanceDtoFromJSON(json: any): CustomerBalanceDto {
    return CustomerBalanceDtoFromJSONTyped(json, false);
}

export function CustomerBalanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerBalanceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'customerId': json['customerId'],
        'merchantId': json['merchantId'] == null ? undefined : json['merchantId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'available': json['available'],
        'pending': json['pending'],
    };
}

export function CustomerBalanceDtoToJSON(json: any): CustomerBalanceDto {
    return CustomerBalanceDtoToJSONTyped(json, false);
}

export function CustomerBalanceDtoToJSONTyped(value?: CustomerBalanceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'deletedAt': value['deletedAt'] == null ? value['deletedAt'] : value['deletedAt'].toISOString(),
        'customerId': value['customerId'],
        'merchantId': value['merchantId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'available': value['available'],
        'pending': value['pending'],
    };
}

