/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerTransactionDto
 */
export interface CustomerTransactionDto {
    /**
     * Unique identifier
     * @type {string}
     * @memberof CustomerTransactionDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomerTransactionDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerTransactionDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerTransactionDto
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomerTransactionDto
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerTransactionDto
     */
    merchantId?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerTransactionDto
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerTransactionDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerTransactionDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerTransactionDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerTransactionDto
     */
    relatedEntityId?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerTransactionDto
     */
    relatedEntityType?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerTransactionDto
     */
    balanceAfter?: number;
}

/**
 * Check if a given object implements the CustomerTransactionDto interface.
 */
export function instanceOfCustomerTransactionDto(value: object): value is CustomerTransactionDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function CustomerTransactionDtoFromJSON(json: any): CustomerTransactionDto {
    return CustomerTransactionDtoFromJSONTyped(json, false);
}

export function CustomerTransactionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerTransactionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'merchantId': json['merchantId'] == null ? undefined : json['merchantId'],
        'type': json['type'],
        'amount': json['amount'],
        'currency': json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'relatedEntityId': json['relatedEntityId'] == null ? undefined : json['relatedEntityId'],
        'relatedEntityType': json['relatedEntityType'] == null ? undefined : json['relatedEntityType'],
        'balanceAfter': json['balanceAfter'] == null ? undefined : json['balanceAfter'],
    };
}

export function CustomerTransactionDtoToJSON(json: any): CustomerTransactionDto {
    return CustomerTransactionDtoToJSONTyped(json, false);
}

export function CustomerTransactionDtoToJSONTyped(value?: CustomerTransactionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'deletedAt': value['deletedAt'] == null ? value['deletedAt'] : value['deletedAt'].toISOString(),
        'customerId': value['customerId'],
        'merchantId': value['merchantId'],
        'type': value['type'],
        'amount': value['amount'],
        'currency': value['currency'],
        'description': value['description'],
        'relatedEntityId': value['relatedEntityId'],
        'relatedEntityType': value['relatedEntityType'],
        'balanceAfter': value['balanceAfter'],
    };
}

