/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerStatsDto
 */
export interface CustomerStatsDto {
    /**
     * New customers in the last 24 hours
     * @type {number}
     * @memberof CustomerStatsDto
     */
    daily: number;
    /**
     * New customers in the last 7 days
     * @type {number}
     * @memberof CustomerStatsDto
     */
    weekly: number;
    /**
     * New customers in the last 30 days
     * @type {number}
     * @memberof CustomerStatsDto
     */
    monthly: number;
}

/**
 * Check if a given object implements the CustomerStatsDto interface.
 */
export function instanceOfCustomerStatsDto(value: object): value is CustomerStatsDto {
    if (!('daily' in value) || value['daily'] === undefined) return false;
    if (!('weekly' in value) || value['weekly'] === undefined) return false;
    if (!('monthly' in value) || value['monthly'] === undefined) return false;
    return true;
}

export function CustomerStatsDtoFromJSON(json: any): CustomerStatsDto {
    return CustomerStatsDtoFromJSONTyped(json, false);
}

export function CustomerStatsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerStatsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'daily': json['daily'],
        'weekly': json['weekly'],
        'monthly': json['monthly'],
    };
}

export function CustomerStatsDtoToJSON(json: any): CustomerStatsDto {
    return CustomerStatsDtoToJSONTyped(json, false);
}

export function CustomerStatsDtoToJSONTyped(value?: CustomerStatsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'daily': value['daily'],
        'weekly': value['weekly'],
        'monthly': value['monthly'],
    };
}

