/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerResponseDto
 */
export interface CustomerResponseDto {
    /**
     * Unique identifier
     * @type {string}
     * @memberof CustomerResponseDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomerResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerResponseDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerResponseDto
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponseDto
     */
    merchantId: string;
    /**
     * The phone number of the customer
     * @type {string}
     * @memberof CustomerResponseDto
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponseDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponseDto
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CustomerResponseDto
     */
    metadata: { [key: string]: any; };
}

/**
 * Check if a given object implements the CustomerResponseDto interface.
 */
export function instanceOfCustomerResponseDto(value: object): value is CustomerResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function CustomerResponseDtoFromJSON(json: any): CustomerResponseDto {
    return CustomerResponseDtoFromJSONTyped(json, false);
}

export function CustomerResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'merchantId': json['merchantId'],
        'phoneNumber': json['phoneNumber'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'metadata': json['metadata'],
    };
}

export function CustomerResponseDtoToJSON(json: any): CustomerResponseDto {
    return CustomerResponseDtoToJSONTyped(json, false);
}

export function CustomerResponseDtoToJSONTyped(value?: CustomerResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'deletedAt': value['deletedAt'] == null ? value['deletedAt'] : value['deletedAt'].toISOString(),
        'merchantId': value['merchantId'],
        'phoneNumber': value['phoneNumber'],
        'email': value['email'],
        'name': value['name'],
        'metadata': value['metadata'],
    };
}

