/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DebitReturnResponseDto
 */
export interface DebitReturnResponseDto {
    /**
     * Payment status after 3DS authentication
     * @type {string}
     * @memberof DebitReturnResponseDto
     */
    status: DebitReturnResponseDtoStatusEnum;
    /**
     * Merchant reference for the payment
     * @type {string}
     * @memberof DebitReturnResponseDto
     */
    merchantReference: string;
    /**
     * Payment intent ID
     * @type {string}
     * @memberof DebitReturnResponseDto
     */
    paymentIntentId?: string;
    /**
     * Transaction ID if payment succeeded
     * @type {string}
     * @memberof DebitReturnResponseDto
     */
    transactionId?: string;
    /**
     * Authorization code from payment gateway
     * @type {string}
     * @memberof DebitReturnResponseDto
     */
    authCode?: string;
    /**
     * Reason for failure if payment failed
     * @type {string}
     * @memberof DebitReturnResponseDto
     */
    reason?: string;
    /**
     * Payment amount in smallest currency unit
     * @type {number}
     * @memberof DebitReturnResponseDto
     */
    amount?: number;
    /**
     * Currency code
     * @type {string}
     * @memberof DebitReturnResponseDto
     */
    currency?: string;
}


/**
 * @export
 */
export const DebitReturnResponseDtoStatusEnum = {
    Succeeded: 'succeeded',
    Failed: 'failed',
    Pending: 'pending'
} as const;
export type DebitReturnResponseDtoStatusEnum = typeof DebitReturnResponseDtoStatusEnum[keyof typeof DebitReturnResponseDtoStatusEnum];


/**
 * Check if a given object implements the DebitReturnResponseDto interface.
 */
export function instanceOfDebitReturnResponseDto(value: object): value is DebitReturnResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('merchantReference' in value) || value['merchantReference'] === undefined) return false;
    return true;
}

export function DebitReturnResponseDtoFromJSON(json: any): DebitReturnResponseDto {
    return DebitReturnResponseDtoFromJSONTyped(json, false);
}

export function DebitReturnResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebitReturnResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'merchantReference': json['merchantReference'],
        'paymentIntentId': json['paymentIntentId'] == null ? undefined : json['paymentIntentId'],
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
        'authCode': json['authCode'] == null ? undefined : json['authCode'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function DebitReturnResponseDtoToJSON(json: any): DebitReturnResponseDto {
    return DebitReturnResponseDtoToJSONTyped(json, false);
}

export function DebitReturnResponseDtoToJSONTyped(value?: DebitReturnResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'merchantReference': value['merchantReference'],
        'paymentIntentId': value['paymentIntentId'],
        'transactionId': value['transactionId'],
        'authCode': value['authCode'],
        'reason': value['reason'],
        'amount': value['amount'],
        'currency': value['currency'],
    };
}

