/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteOrganizationDto
 */
export interface DeleteOrganizationDto {
    /**
     * The ID of the organization to delete
     * @type {string}
     * @memberof DeleteOrganizationDto
     */
    organizationId: string;
}

/**
 * Check if a given object implements the DeleteOrganizationDto interface.
 */
export function instanceOfDeleteOrganizationDto(value: object): value is DeleteOrganizationDto {
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function DeleteOrganizationDtoFromJSON(json: any): DeleteOrganizationDto {
    return DeleteOrganizationDtoFromJSONTyped(json, false);
}

export function DeleteOrganizationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteOrganizationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organizationId'],
    };
}

export function DeleteOrganizationDtoToJSON(json: any): DeleteOrganizationDto {
    return DeleteOrganizationDtoToJSONTyped(json, false);
}

export function DeleteOrganizationDtoToJSONTyped(value?: DeleteOrganizationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organizationId': value['organizationId'],
    };
}

