/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteUserDto
 */
export interface DeleteUserDto {
    /**
     * The callback URL to redirect to after user is deleted
     * @type {string}
     * @memberof DeleteUserDto
     */
    callbackURL?: string;
    /**
     * The user's password. Required if session is not fresh
     * @type {string}
     * @memberof DeleteUserDto
     */
    password?: string;
    /**
     * The deletion verification token
     * @type {string}
     * @memberof DeleteUserDto
     */
    token?: string;
}

/**
 * Check if a given object implements the DeleteUserDto interface.
 */
export function instanceOfDeleteUserDto(value: object): value is DeleteUserDto {
    return true;
}

export function DeleteUserDtoFromJSON(json: any): DeleteUserDto {
    return DeleteUserDtoFromJSONTyped(json, false);
}

export function DeleteUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'callbackURL': json['callbackURL'] == null ? undefined : json['callbackURL'],
        'password': json['password'] == null ? undefined : json['password'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function DeleteUserDtoToJSON(json: any): DeleteUserDto {
    return DeleteUserDtoToJSONTyped(json, false);
}

export function DeleteUserDtoToJSONTyped(value?: DeleteUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'callbackURL': value['callbackURL'],
        'password': value['password'],
        'token': value['token'],
    };
}

