/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteApiKeyDto
 */
export interface DeleteApiKeyDto {
    /**
     * The ID of the API key to delete
     * @type {string}
     * @memberof DeleteApiKeyDto
     */
    keyId: string;
}

/**
 * Check if a given object implements the DeleteApiKeyDto interface.
 */
export function instanceOfDeleteApiKeyDto(value: object): value is DeleteApiKeyDto {
    if (!('keyId' in value) || value['keyId'] === undefined) return false;
    return true;
}

export function DeleteApiKeyDtoFromJSON(json: any): DeleteApiKeyDto {
    return DeleteApiKeyDtoFromJSONTyped(json, false);
}

export function DeleteApiKeyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteApiKeyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'keyId': json['keyId'],
    };
}

export function DeleteApiKeyDtoToJSON(json: any): DeleteApiKeyDto {
    return DeleteApiKeyDtoToJSONTyped(json, false);
}

export function DeleteApiKeyDtoToJSONTyped(value?: DeleteApiKeyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keyId': value['keyId'],
    };
}

