/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteApiKeyResponseDto
 */
export interface DeleteApiKeyResponseDto {
    /**
     * API key deleted successfully
     * @type {boolean}
     * @memberof DeleteApiKeyResponseDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the DeleteApiKeyResponseDto interface.
 */
export function instanceOfDeleteApiKeyResponseDto(value: object): value is DeleteApiKeyResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function DeleteApiKeyResponseDtoFromJSON(json: any): DeleteApiKeyResponseDto {
    return DeleteApiKeyResponseDtoFromJSONTyped(json, false);
}

export function DeleteApiKeyResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteApiKeyResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function DeleteApiKeyResponseDtoToJSON(json: any): DeleteApiKeyResponseDto {
    return DeleteApiKeyResponseDtoToJSONTyped(json, false);
}

export function DeleteApiKeyResponseDtoToJSONTyped(value?: DeleteApiKeyResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

