/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteUserResponseDto
 */
export interface DeleteUserResponseDto {
    /**
     * Indicates if operation was successful
     * @type {boolean}
     * @memberof DeleteUserResponseDto
     */
    success: boolean;
    /**
     * Status message of deletion process
     * @type {string}
     * @memberof DeleteUserResponseDto
     */
    message: DeleteUserResponseDtoMessageEnum;
}


/**
 * @export
 */
export const DeleteUserResponseDtoMessageEnum = {
    UserDeleted: 'User deleted',
    VerificationEmailSent: 'Verification email sent'
} as const;
export type DeleteUserResponseDtoMessageEnum = typeof DeleteUserResponseDtoMessageEnum[keyof typeof DeleteUserResponseDtoMessageEnum];


/**
 * Check if a given object implements the DeleteUserResponseDto interface.
 */
export function instanceOfDeleteUserResponseDto(value: object): value is DeleteUserResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteUserResponseDtoFromJSON(json: any): DeleteUserResponseDto {
    return DeleteUserResponseDtoFromJSONTyped(json, false);
}

export function DeleteUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
    };
}

export function DeleteUserResponseDtoToJSON(json: any): DeleteUserResponseDto {
    return DeleteUserResponseDtoToJSONTyped(json, false);
}

export function DeleteUserResponseDtoToJSONTyped(value?: DeleteUserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

