/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventResponseDto
 */
export interface EventResponseDto {
    /**
     * 
     * @type {string}
     * @memberof EventResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EventResponseDto
     */
    merchantId: string;
    /**
     * 
     * @type {string}
     * @memberof EventResponseDto
     */
    type: string;
    /**
     * Event data payload
     * @type {object}
     * @memberof EventResponseDto
     */
    data: object;
    /**
     * 
     * @type {string}
     * @memberof EventResponseDto
     */
    relatedEntityId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventResponseDto
     */
    relatedEntityType?: string;
    /**
     * 
     * @type {Date}
     * @memberof EventResponseDto
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the EventResponseDto interface.
 */
export function instanceOfEventResponseDto(value: object): value is EventResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function EventResponseDtoFromJSON(json: any): EventResponseDto {
    return EventResponseDtoFromJSONTyped(json, false);
}

export function EventResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'merchantId': json['merchantId'],
        'type': json['type'],
        'data': json['data'],
        'relatedEntityId': json['relatedEntityId'] == null ? undefined : json['relatedEntityId'],
        'relatedEntityType': json['relatedEntityType'] == null ? undefined : json['relatedEntityType'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function EventResponseDtoToJSON(json: any): EventResponseDto {
    return EventResponseDtoToJSONTyped(json, false);
}

export function EventResponseDtoToJSONTyped(value?: EventResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'merchantId': value['merchantId'],
        'type': value['type'],
        'data': value['data'],
        'relatedEntityId': value['relatedEntityId'],
        'relatedEntityType': value['relatedEntityType'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

