/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventResponseDto
 */
export interface EventResponseDto {
    /**
     * Unique identifier for the event
     * @type {string}
     * @memberof EventResponseDto
     */
    id: string;
    /**
     * ID of the merchant this event belongs to
     * @type {string}
     * @memberof EventResponseDto
     */
    merchantId: string;
    /**
     * ID of the webhook endpoint this event was sent to
     * @type {string}
     * @memberof EventResponseDto
     */
    webhookEndpointId: string;
    /**
     * Event type name
     * @type {string}
     * @memberof EventResponseDto
     */
    type: string;
    /**
     * Event data payload
     * @type {object}
     * @memberof EventResponseDto
     */
    data: object;
    /**
     * Current delivery status of the event
     * @type {string}
     * @memberof EventResponseDto
     */
    status: EventResponseDtoStatusEnum;
    /**
     * Number of delivery attempts
     * @type {number}
     * @memberof EventResponseDto
     */
    attempts: number;
    /**
     * ID of the related entity
     * @type {string}
     * @memberof EventResponseDto
     */
    relatedEntityId?: string;
    /**
     * Type of the related entity
     * @type {string}
     * @memberof EventResponseDto
     */
    relatedEntityType?: string;
    /**
     * Timestamp of the last delivery attempt
     * @type {Date}
     * @memberof EventResponseDto
     */
    lastAttemptAt?: Date;
    /**
     * Timestamp for the next retry attempt
     * @type {Date}
     * @memberof EventResponseDto
     */
    nextRetryAt?: Date;
    /**
     * Timestamp when the event was successfully delivered
     * @type {Date}
     * @memberof EventResponseDto
     */
    deliveredAt?: Date;
    /**
     * Timestamp when the event was created
     * @type {Date}
     * @memberof EventResponseDto
     */
    createdAt: Date;
    /**
     * Timestamp when the event was last updated
     * @type {Date}
     * @memberof EventResponseDto
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const EventResponseDtoStatusEnum = {
    Pending: 'pending',
    Delivered: 'delivered',
    Failed: 'failed'
} as const;
export type EventResponseDtoStatusEnum = typeof EventResponseDtoStatusEnum[keyof typeof EventResponseDtoStatusEnum];


/**
 * Check if a given object implements the EventResponseDto interface.
 */
export function instanceOfEventResponseDto(value: object): value is EventResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('webhookEndpointId' in value) || value['webhookEndpointId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('attempts' in value) || value['attempts'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EventResponseDtoFromJSON(json: any): EventResponseDto {
    return EventResponseDtoFromJSONTyped(json, false);
}

export function EventResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'merchantId': json['merchantId'],
        'webhookEndpointId': json['webhookEndpointId'],
        'type': json['type'],
        'data': json['data'],
        'status': json['status'],
        'attempts': json['attempts'],
        'relatedEntityId': json['relatedEntityId'] == null ? undefined : json['relatedEntityId'],
        'relatedEntityType': json['relatedEntityType'] == null ? undefined : json['relatedEntityType'],
        'lastAttemptAt': json['lastAttemptAt'] == null ? undefined : (new Date(json['lastAttemptAt'])),
        'nextRetryAt': json['nextRetryAt'] == null ? undefined : (new Date(json['nextRetryAt'])),
        'deliveredAt': json['deliveredAt'] == null ? undefined : (new Date(json['deliveredAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EventResponseDtoToJSON(json: any): EventResponseDto {
    return EventResponseDtoToJSONTyped(json, false);
}

export function EventResponseDtoToJSONTyped(value?: EventResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'merchantId': value['merchantId'],
        'webhookEndpointId': value['webhookEndpointId'],
        'type': value['type'],
        'data': value['data'],
        'status': value['status'],
        'attempts': value['attempts'],
        'relatedEntityId': value['relatedEntityId'],
        'relatedEntityType': value['relatedEntityType'],
        'lastAttemptAt': value['lastAttemptAt'] == null ? value['lastAttemptAt'] : value['lastAttemptAt'].toISOString(),
        'nextRetryAt': value['nextRetryAt'] == null ? value['nextRetryAt'] : value['nextRetryAt'].toISOString(),
        'deliveredAt': value['deliveredAt'] == null ? value['deliveredAt'] : value['deliveredAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

