/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvervaultEncryptedCardDto
 */
export interface EvervaultEncryptedCardDto {
    /**
     * Encrypted Primary Account Number (PAN)
     * @type {string}
     * @memberof EvervaultEncryptedCardDto
     */
    pAN: string;
    /**
     * Encrypted card expiry date
     * @type {string}
     * @memberof EvervaultEncryptedCardDto
     */
    expiryDate: string;
    /**
     * Encrypted card security code (CVV)
     * @type {string}
     * @memberof EvervaultEncryptedCardDto
     */
    cardSecurityCode: string;
    /**
     * Encrypted cardholder name
     * @type {string}
     * @memberof EvervaultEncryptedCardDto
     */
    cardholderName?: string;
}

/**
 * Check if a given object implements the EvervaultEncryptedCardDto interface.
 */
export function instanceOfEvervaultEncryptedCardDto(value: object): value is EvervaultEncryptedCardDto {
    if (!('pAN' in value) || value['pAN'] === undefined) return false;
    if (!('expiryDate' in value) || value['expiryDate'] === undefined) return false;
    if (!('cardSecurityCode' in value) || value['cardSecurityCode'] === undefined) return false;
    return true;
}

export function EvervaultEncryptedCardDtoFromJSON(json: any): EvervaultEncryptedCardDto {
    return EvervaultEncryptedCardDtoFromJSONTyped(json, false);
}

export function EvervaultEncryptedCardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvervaultEncryptedCardDto {
    if (json == null) {
        return json;
    }
    return {
        
        'pAN': json['PAN'],
        'expiryDate': json['ExpiryDate'],
        'cardSecurityCode': json['CardSecurityCode'],
        'cardholderName': json['CardholderName'] == null ? undefined : json['CardholderName'],
    };
}

export function EvervaultEncryptedCardDtoToJSON(json: any): EvervaultEncryptedCardDto {
    return EvervaultEncryptedCardDtoToJSONTyped(json, false);
}

export function EvervaultEncryptedCardDtoToJSONTyped(value?: EvervaultEncryptedCardDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'PAN': value['pAN'],
        'ExpiryDate': value['expiryDate'],
        'CardSecurityCode': value['cardSecurityCode'],
        'CardholderName': value['cardholderName'],
    };
}

