/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileDto
 */
export interface FileDto {
    /**
     * Unique identifier
     * @type {string}
     * @memberof FileDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof FileDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof FileDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof FileDto
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    bucket: string;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    mimeType: string;
    /**
     * 
     * @type {number}
     * @memberof FileDto
     */
    size: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof FileDto
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    status: FileDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    checksum?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FileDto
     */
    isPublic: boolean;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    relatedEntityId?: string;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    relatedEntityType?: string;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    uploadedById?: string;
}


/**
 * @export
 */
export const FileDtoStatusEnum = {
    Pending: 'pending',
    Uploaded: 'uploaded',
    Failed: 'failed',
    Deleted: 'deleted'
} as const;
export type FileDtoStatusEnum = typeof FileDtoStatusEnum[keyof typeof FileDtoStatusEnum];


/**
 * Check if a given object implements the FileDto interface.
 */
export function instanceOfFileDto(value: object): value is FileDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('bucket' in value) || value['bucket'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
    return true;
}

export function FileDtoFromJSON(json: any): FileDto {
    return FileDtoFromJSONTyped(json, false);
}

export function FileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'key': json['key'],
        'bucket': json['bucket'],
        'filename': json['filename'],
        'mimeType': json['mimeType'],
        'size': json['size'],
        'tags': json['tags'],
        'status': json['status'],
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'isPublic': json['isPublic'],
        'relatedEntityId': json['relatedEntityId'] == null ? undefined : json['relatedEntityId'],
        'relatedEntityType': json['relatedEntityType'] == null ? undefined : json['relatedEntityType'],
        'uploadedById': json['uploadedById'] == null ? undefined : json['uploadedById'],
    };
}

export function FileDtoToJSON(json: any): FileDto {
    return FileDtoToJSONTyped(json, false);
}

export function FileDtoToJSONTyped(value?: FileDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'deletedAt': value['deletedAt'] == null ? value['deletedAt'] : value['deletedAt'].toISOString(),
        'key': value['key'],
        'bucket': value['bucket'],
        'filename': value['filename'],
        'mimeType': value['mimeType'],
        'size': value['size'],
        'tags': value['tags'],
        'status': value['status'],
        'checksum': value['checksum'],
        'isPublic': value['isPublic'],
        'relatedEntityId': value['relatedEntityId'],
        'relatedEntityType': value['relatedEntityType'],
        'uploadedById': value['uploadedById'],
    };
}

