/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForgotPasswordResponseDto
 */
export interface ForgotPasswordResponseDto {
    /**
     * Password reset email sent
     * @type {boolean}
     * @memberof ForgotPasswordResponseDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the ForgotPasswordResponseDto interface.
 */
export function instanceOfForgotPasswordResponseDto(value: object): value is ForgotPasswordResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ForgotPasswordResponseDtoFromJSON(json: any): ForgotPasswordResponseDto {
    return ForgotPasswordResponseDtoFromJSONTyped(json, false);
}

export function ForgotPasswordResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotPasswordResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function ForgotPasswordResponseDtoToJSON(json: any): ForgotPasswordResponseDto {
    return ForgotPasswordResponseDtoToJSONTyped(json, false);
}

export function ForgotPasswordResponseDtoToJSONTyped(value?: ForgotPasswordResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

