/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKey } from './ApiKey';
import {
    ApiKeyFromJSON,
    ApiKeyFromJSONTyped,
    ApiKeyToJSON,
    ApiKeyToJSONTyped,
} from './ApiKey';

/**
 * 
 * @export
 * @interface GetApiKeyResponseDto
 */
export interface GetApiKeyResponseDto {
    /**
     * API key retrieved successfully
     * @type {ApiKey}
     * @memberof GetApiKeyResponseDto
     */
    apiKey: ApiKey;
}

/**
 * Check if a given object implements the GetApiKeyResponseDto interface.
 */
export function instanceOfGetApiKeyResponseDto(value: object): value is GetApiKeyResponseDto {
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    return true;
}

export function GetApiKeyResponseDtoFromJSON(json: any): GetApiKeyResponseDto {
    return GetApiKeyResponseDtoFromJSONTyped(json, false);
}

export function GetApiKeyResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiKeyResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': ApiKeyFromJSON(json['apiKey']),
    };
}

export function GetApiKeyResponseDtoToJSON(json: any): GetApiKeyResponseDto {
    return GetApiKeyResponseDtoToJSONTyped(json, false);
}

export function GetApiKeyResponseDtoToJSONTyped(value?: GetApiKeyResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiKey': ApiKeyToJSON(value['apiKey']),
    };
}

