/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAccessTokenDto
 */
export interface GetAccessTokenDto {
    /**
     * The provider to get token for
     * @type {string}
     * @memberof GetAccessTokenDto
     */
    provider?: string;
    /**
     * Whether to force token refresh
     * @type {boolean}
     * @memberof GetAccessTokenDto
     */
    forceRefresh?: boolean;
}

/**
 * Check if a given object implements the GetAccessTokenDto interface.
 */
export function instanceOfGetAccessTokenDto(value: object): value is GetAccessTokenDto {
    return true;
}

export function GetAccessTokenDtoFromJSON(json: any): GetAccessTokenDto {
    return GetAccessTokenDtoFromJSONTyped(json, false);
}

export function GetAccessTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccessTokenDto {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'] == null ? undefined : json['provider'],
        'forceRefresh': json['forceRefresh'] == null ? undefined : json['forceRefresh'],
    };
}

export function GetAccessTokenDtoToJSON(json: any): GetAccessTokenDto {
    return GetAccessTokenDtoToJSONTyped(json, false);
}

export function GetAccessTokenDtoToJSONTyped(value?: GetAccessTokenDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'forceRefresh': value['forceRefresh'],
    };
}

