/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberDto } from './MemberDto';
import {
    MemberDtoFromJSON,
    MemberDtoFromJSONTyped,
    MemberDtoToJSON,
    MemberDtoToJSONTyped,
} from './MemberDto';

/**
 * 
 * @export
 * @interface GetActiveMemberResponseDto
 */
export interface GetActiveMemberResponseDto {
    /**
     * Active member details
     * @type {MemberDto}
     * @memberof GetActiveMemberResponseDto
     */
    member: MemberDto;
}

/**
 * Check if a given object implements the GetActiveMemberResponseDto interface.
 */
export function instanceOfGetActiveMemberResponseDto(value: object): value is GetActiveMemberResponseDto {
    if (!('member' in value) || value['member'] === undefined) return false;
    return true;
}

export function GetActiveMemberResponseDtoFromJSON(json: any): GetActiveMemberResponseDto {
    return GetActiveMemberResponseDtoFromJSONTyped(json, false);
}

export function GetActiveMemberResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetActiveMemberResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'member': MemberDtoFromJSON(json['member']),
    };
}

export function GetActiveMemberResponseDtoToJSON(json: any): GetActiveMemberResponseDto {
    return GetActiveMemberResponseDtoToJSONTyped(json, false);
}

export function GetActiveMemberResponseDtoToJSONTyped(value?: GetActiveMemberResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member': MemberDtoToJSON(value['member']),
    };
}

