/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationDto } from './OrganizationDto';
import {
    OrganizationDtoFromJSON,
    OrganizationDtoFromJSONTyped,
    OrganizationDtoToJSON,
    OrganizationDtoToJSONTyped,
} from './OrganizationDto';

/**
 * 
 * @export
 * @interface GetFullOrganizationResponseDto
 */
export interface GetFullOrganizationResponseDto {
    /**
     * The full organization object
     * @type {OrganizationDto}
     * @memberof GetFullOrganizationResponseDto
     */
    organization: OrganizationDto;
}

/**
 * Check if a given object implements the GetFullOrganizationResponseDto interface.
 */
export function instanceOfGetFullOrganizationResponseDto(value: object): value is GetFullOrganizationResponseDto {
    if (!('organization' in value) || value['organization'] === undefined) return false;
    return true;
}

export function GetFullOrganizationResponseDtoFromJSON(json: any): GetFullOrganizationResponseDto {
    return GetFullOrganizationResponseDtoFromJSONTyped(json, false);
}

export function GetFullOrganizationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFullOrganizationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'organization': OrganizationDtoFromJSON(json['organization']),
    };
}

export function GetFullOrganizationResponseDtoToJSON(json: any): GetFullOrganizationResponseDto {
    return GetFullOrganizationResponseDtoToJSONTyped(json, false);
}

export function GetFullOrganizationResponseDtoToJSONTyped(value?: GetFullOrganizationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization': OrganizationDtoToJSON(value['organization']),
    };
}

