/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetJsonWebTokenResponseDto
 */
export interface GetJsonWebTokenResponseDto {
    /**
     * The JWT token
     * @type {string}
     * @memberof GetJsonWebTokenResponseDto
     */
    token: string;
}

/**
 * Check if a given object implements the GetJsonWebTokenResponseDto interface.
 */
export function instanceOfGetJsonWebTokenResponseDto(value: object): value is GetJsonWebTokenResponseDto {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function GetJsonWebTokenResponseDtoFromJSON(json: any): GetJsonWebTokenResponseDto {
    return GetJsonWebTokenResponseDtoFromJSONTyped(json, false);
}

export function GetJsonWebTokenResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetJsonWebTokenResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function GetJsonWebTokenResponseDtoToJSON(json: any): GetJsonWebTokenResponseDto {
    return GetJsonWebTokenResponseDtoToJSONTyped(json, false);
}

export function GetJsonWebTokenResponseDtoToJSONTyped(value?: GetJsonWebTokenResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

