/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JwkDto } from './JwkDto';
import {
    JwkDtoFromJSON,
    JwkDtoFromJSONTyped,
    JwkDtoToJSON,
    JwkDtoToJSONTyped,
} from './JwkDto';

/**
 * 
 * @export
 * @interface GetJsonWebKeySetResponseDto
 */
export interface GetJsonWebKeySetResponseDto {
    /**
     * Array of public JSON Web Keys
     * @type {Array<JwkDto>}
     * @memberof GetJsonWebKeySetResponseDto
     */
    keys: Array<JwkDto>;
}

/**
 * Check if a given object implements the GetJsonWebKeySetResponseDto interface.
 */
export function instanceOfGetJsonWebKeySetResponseDto(value: object): value is GetJsonWebKeySetResponseDto {
    if (!('keys' in value) || value['keys'] === undefined) return false;
    return true;
}

export function GetJsonWebKeySetResponseDtoFromJSON(json: any): GetJsonWebKeySetResponseDto {
    return GetJsonWebKeySetResponseDtoFromJSONTyped(json, false);
}

export function GetJsonWebKeySetResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetJsonWebKeySetResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'keys': ((json['keys'] as Array<any>).map(JwkDtoFromJSON)),
    };
}

export function GetJsonWebKeySetResponseDtoToJSON(json: any): GetJsonWebKeySetResponseDto {
    return GetJsonWebKeySetResponseDtoToJSONTyped(json, false);
}

export function GetJsonWebKeySetResponseDtoToJSONTyped(value?: GetJsonWebKeySetResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keys': ((value['keys'] as Array<any>).map(JwkDtoToJSON)),
    };
}

