/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HasPermissionDto
 */
export interface HasPermissionDto {
    /**
     * The permission to check
     * @type {object}
     * @memberof HasPermissionDto
     */
    permission: object;
    /**
     * The resource to check permission on
     * @type {string}
     * @memberof HasPermissionDto
     */
    resource?: string;
    /**
     * The organization ID to check permission in
     * @type {string}
     * @memberof HasPermissionDto
     */
    organizationId?: string;
}

/**
 * Check if a given object implements the HasPermissionDto interface.
 */
export function instanceOfHasPermissionDto(value: object): value is HasPermissionDto {
    if (!('permission' in value) || value['permission'] === undefined) return false;
    return true;
}

export function HasPermissionDtoFromJSON(json: any): HasPermissionDto {
    return HasPermissionDtoFromJSONTyped(json, false);
}

export function HasPermissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HasPermissionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'permission': json['permission'],
        'resource': json['resource'] == null ? undefined : json['resource'],
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
    };
}

export function HasPermissionDtoToJSON(json: any): HasPermissionDto {
    return HasPermissionDtoToJSONTyped(json, false);
}

export function HasPermissionDtoToJSONTyped(value?: HasPermissionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permission': value['permission'],
        'resource': value['resource'],
        'organizationId': value['organizationId'],
    };
}

