/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HostedCheckoutConfigDto
 */
export interface HostedCheckoutConfigDto {
    /**
     * Merchant ID
     * @type {string}
     * @memberof HostedCheckoutConfigDto
     */
    merchantId?: string;
    /**
     * Merchant alias
     * @type {string}
     * @memberof HostedCheckoutConfigDto
     */
    merchantAlias?: string;
    /**
     * Merchant legal name
     * @type {string}
     * @memberof HostedCheckoutConfigDto
     */
    merchantLegalName?: string;
    /**
     * Merchant avatar text placeholder
     * @type {string}
     * @memberof HostedCheckoutConfigDto
     */
    merchantAvatarTextPlaceholder?: string;
    /**
     * Merchant avatar URL
     * @type {string}
     * @memberof HostedCheckoutConfigDto
     */
    merchantAvatarUrl?: string;
    /**
     * Require contact
     * @type {boolean}
     * @memberof HostedCheckoutConfigDto
     */
    requireContact?: boolean;
    /**
     * Require address
     * @type {boolean}
     * @memberof HostedCheckoutConfigDto
     */
    requireAddress?: boolean;
    /**
     * Tax rate
     * @type {number}
     * @memberof HostedCheckoutConfigDto
     */
    taxRate?: number;
    /**
     * Embed mode
     * @type {boolean}
     * @memberof HostedCheckoutConfigDto
     */
    embedMode?: boolean;
    /**
     * Embed origin
     * @type {string}
     * @memberof HostedCheckoutConfigDto
     */
    embedOrigin?: string;
}

/**
 * Check if a given object implements the HostedCheckoutConfigDto interface.
 */
export function instanceOfHostedCheckoutConfigDto(value: object): value is HostedCheckoutConfigDto {
    return true;
}

export function HostedCheckoutConfigDtoFromJSON(json: any): HostedCheckoutConfigDto {
    return HostedCheckoutConfigDtoFromJSONTyped(json, false);
}

export function HostedCheckoutConfigDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HostedCheckoutConfigDto {
    if (json == null) {
        return json;
    }
    return {
        
        'merchantId': json['merchantId'] == null ? undefined : json['merchantId'],
        'merchantAlias': json['merchantAlias'] == null ? undefined : json['merchantAlias'],
        'merchantLegalName': json['merchantLegalName'] == null ? undefined : json['merchantLegalName'],
        'merchantAvatarTextPlaceholder': json['merchantAvatarTextPlaceholder'] == null ? undefined : json['merchantAvatarTextPlaceholder'],
        'merchantAvatarUrl': json['merchantAvatarUrl'] == null ? undefined : json['merchantAvatarUrl'],
        'requireContact': json['requireContact'] == null ? undefined : json['requireContact'],
        'requireAddress': json['requireAddress'] == null ? undefined : json['requireAddress'],
        'taxRate': json['taxRate'] == null ? undefined : json['taxRate'],
        'embedMode': json['embedMode'] == null ? undefined : json['embedMode'],
        'embedOrigin': json['embedOrigin'] == null ? undefined : json['embedOrigin'],
    };
}

export function HostedCheckoutConfigDtoToJSON(json: any): HostedCheckoutConfigDto {
    return HostedCheckoutConfigDtoToJSONTyped(json, false);
}

export function HostedCheckoutConfigDtoToJSONTyped(value?: HostedCheckoutConfigDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'merchantId': value['merchantId'],
        'merchantAlias': value['merchantAlias'],
        'merchantLegalName': value['merchantLegalName'],
        'merchantAvatarTextPlaceholder': value['merchantAvatarTextPlaceholder'],
        'merchantAvatarUrl': value['merchantAvatarUrl'],
        'requireContact': value['requireContact'],
        'requireAddress': value['requireAddress'],
        'taxRate': value['taxRate'],
        'embedMode': value['embedMode'],
        'embedOrigin': value['embedOrigin'],
    };
}

