/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImpersonateUserResponseDto
 */
export interface ImpersonateUserResponseDto {
    /**
     * User impersonated successfully
     * @type {boolean}
     * @memberof ImpersonateUserResponseDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the ImpersonateUserResponseDto interface.
 */
export function instanceOfImpersonateUserResponseDto(value: object): value is ImpersonateUserResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ImpersonateUserResponseDtoFromJSON(json: any): ImpersonateUserResponseDto {
    return ImpersonateUserResponseDtoFromJSONTyped(json, false);
}

export function ImpersonateUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpersonateUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function ImpersonateUserResponseDtoToJSON(json: any): ImpersonateUserResponseDto {
    return ImpersonateUserResponseDtoToJSONTyped(json, false);
}

export function ImpersonateUserResponseDtoToJSONTyped(value?: ImpersonateUserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

