/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteMemberDto
 */
export interface InviteMemberDto {
    /**
     * The email of the user to invite
     * @type {string}
     * @memberof InviteMemberDto
     */
    email: string;
    /**
     * The role to assign to the user
     * @type {string}
     * @memberof InviteMemberDto
     */
    role: string;
    /**
     * The ID of the organization
     * @type {string}
     * @memberof InviteMemberDto
     */
    organizationId: string;
}

/**
 * Check if a given object implements the InviteMemberDto interface.
 */
export function instanceOfInviteMemberDto(value: object): value is InviteMemberDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function InviteMemberDtoFromJSON(json: any): InviteMemberDto {
    return InviteMemberDtoFromJSONTyped(json, false);
}

export function InviteMemberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteMemberDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'role': json['role'],
        'organizationId': json['organizationId'],
    };
}

export function InviteMemberDtoToJSON(json: any): InviteMemberDto {
    return InviteMemberDtoToJSONTyped(json, false);
}

export function InviteMemberDtoToJSONTyped(value?: InviteMemberDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'role': value['role'],
        'organizationId': value['organizationId'],
    };
}

