/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvitationDto
 */
export interface InvitationDto {
    /**
     * Invitation ID
     * @type {string}
     * @memberof InvitationDto
     */
    id: string;
    /**
     * Organization ID
     * @type {string}
     * @memberof InvitationDto
     */
    organizationId: string;
    /**
     * Invited email
     * @type {string}
     * @memberof InvitationDto
     */
    email: string;
    /**
     * Invitation role
     * @type {string}
     * @memberof InvitationDto
     */
    role: string;
    /**
     * Invitation status
     * @type {string}
     * @memberof InvitationDto
     */
    status: string;
    /**
     * Invitation expiration date
     * @type {string}
     * @memberof InvitationDto
     */
    expiresAt: string;
    /**
     * Invitation creation date
     * @type {string}
     * @memberof InvitationDto
     */
    createdAt: string;
    /**
     * Inviter ID
     * @type {string}
     * @memberof InvitationDto
     */
    inviterId: string;
}

/**
 * Check if a given object implements the InvitationDto interface.
 */
export function instanceOfInvitationDto(value: object): value is InvitationDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('inviterId' in value) || value['inviterId'] === undefined) return false;
    return true;
}

export function InvitationDtoFromJSON(json: any): InvitationDto {
    return InvitationDtoFromJSONTyped(json, false);
}

export function InvitationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'],
        'email': json['email'],
        'role': json['role'],
        'status': json['status'],
        'expiresAt': json['expiresAt'],
        'createdAt': json['createdAt'],
        'inviterId': json['inviterId'],
    };
}

export function InvitationDtoToJSON(json: any): InvitationDto {
    return InvitationDtoToJSONTyped(json, false);
}

export function InvitationDtoToJSONTyped(value?: InvitationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'email': value['email'],
        'role': value['role'],
        'status': value['status'],
        'expiresAt': value['expiresAt'],
        'createdAt': value['createdAt'],
        'inviterId': value['inviterId'],
    };
}

