/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteMemberResponseDto
 */
export interface InviteMemberResponseDto {
    /**
     * Member invited successfully
     * @type {object}
     * @memberof InviteMemberResponseDto
     */
    invitation: object;
}

/**
 * Check if a given object implements the InviteMemberResponseDto interface.
 */
export function instanceOfInviteMemberResponseDto(value: object): value is InviteMemberResponseDto {
    if (!('invitation' in value) || value['invitation'] === undefined) return false;
    return true;
}

export function InviteMemberResponseDtoFromJSON(json: any): InviteMemberResponseDto {
    return InviteMemberResponseDtoFromJSONTyped(json, false);
}

export function InviteMemberResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteMemberResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'invitation': json['invitation'],
    };
}

export function InviteMemberResponseDtoToJSON(json: any): InviteMemberResponseDto {
    return InviteMemberResponseDtoToJSONTyped(json, false);
}

export function InviteMemberResponseDtoToJSONTyped(value?: InviteMemberResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invitation': value['invitation'],
    };
}

