/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IVeriHealthCheckResponseDto
 */
export interface IVeriHealthCheckResponseDto {
    /**
     * Service health status
     * @type {string}
     * @memberof IVeriHealthCheckResponseDto
     */
    status: string;
    /**
     * Current server timestamp in ISO format
     * @type {string}
     * @memberof IVeriHealthCheckResponseDto
     */
    timestamp: string;
}

/**
 * Check if a given object implements the IVeriHealthCheckResponseDto interface.
 */
export function instanceOfIVeriHealthCheckResponseDto(value: object): value is IVeriHealthCheckResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function IVeriHealthCheckResponseDtoFromJSON(json: any): IVeriHealthCheckResponseDto {
    return IVeriHealthCheckResponseDtoFromJSONTyped(json, false);
}

export function IVeriHealthCheckResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IVeriHealthCheckResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'timestamp': json['timestamp'],
    };
}

export function IVeriHealthCheckResponseDtoToJSON(json: any): IVeriHealthCheckResponseDto {
    return IVeriHealthCheckResponseDtoToJSONTyped(json, false);
}

export function IVeriHealthCheckResponseDtoToJSONTyped(value?: IVeriHealthCheckResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': value['timestamp'],
    };
}

