/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IveriParamsDto
 */
export interface IveriParamsDto {
    /**
     * iVeri Application ID
     * @type {string}
     * @memberof IveriParamsDto
     */
    applicationID: string;
    /**
     * URL to return to after 3DS authentication
     * @type {string}
     * @memberof IveriParamsDto
     */
    returnUrl: string;
    /**
     * Unique merchant reference for this payment
     * @type {string}
     * @memberof IveriParamsDto
     */
    merchantReference: string;
    /**
     * Payment amount in cents (as string)
     * @type {string}
     * @memberof IveriParamsDto
     */
    amount: string;
    /**
     * Three-letter ISO 4217 currency code
     * @type {string}
     * @memberof IveriParamsDto
     */
    currency: string;
}

/**
 * Check if a given object implements the IveriParamsDto interface.
 */
export function instanceOfIveriParamsDto(value: object): value is IveriParamsDto {
    if (!('applicationID' in value) || value['applicationID'] === undefined) return false;
    if (!('returnUrl' in value) || value['returnUrl'] === undefined) return false;
    if (!('merchantReference' in value) || value['merchantReference'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function IveriParamsDtoFromJSON(json: any): IveriParamsDto {
    return IveriParamsDtoFromJSONTyped(json, false);
}

export function IveriParamsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IveriParamsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationID': json['ApplicationID'],
        'returnUrl': json['ReturnUrl'],
        'merchantReference': json['MerchantReference'],
        'amount': json['Amount'],
        'currency': json['Currency'],
    };
}

export function IveriParamsDtoToJSON(json: any): IveriParamsDto {
    return IveriParamsDtoToJSONTyped(json, false);
}

export function IveriParamsDtoToJSONTyped(value?: IveriParamsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ApplicationID': value['applicationID'],
        'ReturnUrl': value['returnUrl'],
        'MerchantReference': value['merchantReference'],
        'Amount': value['amount'],
        'Currency': value['currency'],
    };
}

