/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JwkDto
 */
export interface JwkDto {
    /**
     * Key ID uniquely identifying the key
     * @type {string}
     * @memberof JwkDto
     */
    kid: string;
    /**
     * Key type (e.g., 'RSA', 'EC', 'OKP')
     * @type {string}
     * @memberof JwkDto
     */
    kty: string;
    /**
     * Algorithm intended for use with the key
     * @type {string}
     * @memberof JwkDto
     */
    alg: string;
    /**
     * Intended use of the public key
     * @type {string}
     * @memberof JwkDto
     */
    use?: JwkDtoUseEnum | null;
    /**
     * Modulus for RSA keys
     * @type {string}
     * @memberof JwkDto
     */
    n?: string | null;
    /**
     * Exponent for RSA keys
     * @type {string}
     * @memberof JwkDto
     */
    e?: string | null;
    /**
     * Curve name for elliptic curve keys
     * @type {string}
     * @memberof JwkDto
     */
    crv?: string | null;
    /**
     * X coordinate for elliptic curve keys
     * @type {string}
     * @memberof JwkDto
     */
    x?: string | null;
    /**
     * Y coordinate for elliptic curve keys
     * @type {string}
     * @memberof JwkDto
     */
    y?: string | null;
}


/**
 * @export
 */
export const JwkDtoUseEnum = {
    Sig: 'sig'
} as const;
export type JwkDtoUseEnum = typeof JwkDtoUseEnum[keyof typeof JwkDtoUseEnum];


/**
 * Check if a given object implements the JwkDto interface.
 */
export function instanceOfJwkDto(value: object): value is JwkDto {
    if (!('kid' in value) || value['kid'] === undefined) return false;
    if (!('kty' in value) || value['kty'] === undefined) return false;
    if (!('alg' in value) || value['alg'] === undefined) return false;
    return true;
}

export function JwkDtoFromJSON(json: any): JwkDto {
    return JwkDtoFromJSONTyped(json, false);
}

export function JwkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwkDto {
    if (json == null) {
        return json;
    }
    return {
        
        'kid': json['kid'],
        'kty': json['kty'],
        'alg': json['alg'],
        'use': json['use'] == null ? undefined : json['use'],
        'n': json['n'] == null ? undefined : json['n'],
        'e': json['e'] == null ? undefined : json['e'],
        'crv': json['crv'] == null ? undefined : json['crv'],
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
    };
}

export function JwkDtoToJSON(json: any): JwkDto {
    return JwkDtoToJSONTyped(json, false);
}

export function JwkDtoToJSONTyped(value?: JwkDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kid': value['kid'],
        'kty': value['kty'],
        'alg': value['alg'],
        'use': value['use'],
        'n': value['n'],
        'e': value['e'],
        'crv': value['crv'],
        'x': value['x'],
        'y': value['y'],
    };
}

