/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeaveOrganizationResponseDto
 */
export interface LeaveOrganizationResponseDto {
    /**
     * Leave operation result
     * @type {boolean}
     * @memberof LeaveOrganizationResponseDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the LeaveOrganizationResponseDto interface.
 */
export function instanceOfLeaveOrganizationResponseDto(value: object): value is LeaveOrganizationResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function LeaveOrganizationResponseDtoFromJSON(json: any): LeaveOrganizationResponseDto {
    return LeaveOrganizationResponseDtoFromJSONTyped(json, false);
}

export function LeaveOrganizationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaveOrganizationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function LeaveOrganizationResponseDtoToJSON(json: any): LeaveOrganizationResponseDto {
    return LeaveOrganizationResponseDtoToJSONTyped(json, false);
}

export function LeaveOrganizationResponseDtoToJSONTyped(value?: LeaveOrganizationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

