/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LineItemDto
 */
export interface LineItemDto {
    /**
     * The unique identifier of the product
     * @type {string}
     * @memberof LineItemDto
     */
    productId?: string;
    /**
     * The quantity of the product
     * @type {number}
     * @memberof LineItemDto
     */
    quantity?: number;
    /**
     * The amount for this line item in the smallest currency unit
     * @type {number}
     * @memberof LineItemDto
     */
    amount: number;
    /**
     * The three-letter ISO 4217 currency code
     * @type {string}
     * @memberof LineItemDto
     */
    currency: string;
}

/**
 * Check if a given object implements the LineItemDto interface.
 */
export function instanceOfLineItemDto(value: object): value is LineItemDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function LineItemDtoFromJSON(json: any): LineItemDto {
    return LineItemDtoFromJSONTyped(json, false);
}

export function LineItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'] == null ? undefined : json['productId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'amount': json['amount'],
        'currency': json['currency'],
    };
}

export function LineItemDtoToJSON(json: any): LineItemDto {
    return LineItemDtoToJSONTyped(json, false);
}

export function LineItemDtoToJSONTyped(value?: LineItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'quantity': value['quantity'],
        'amount': value['amount'],
        'currency': value['currency'],
    };
}

