/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkedAccountDto
 */
export interface LinkedAccountDto {
    /**
     * Unique identifier
     * @type {string}
     * @memberof LinkedAccountDto
     */
    id: string;
    /**
     * Account ID
     * @type {string}
     * @memberof LinkedAccountDto
     */
    accountId: string;
    /**
     * Provider ID (e.g., google, github)
     * @type {string}
     * @memberof LinkedAccountDto
     */
    providerId: string;
    /**
     * User ID
     * @type {string}
     * @memberof LinkedAccountDto
     */
    userId: string;
    /**
     * Access token
     * @type {string}
     * @memberof LinkedAccountDto
     */
    accessToken?: string;
    /**
     * Refresh token
     * @type {string}
     * @memberof LinkedAccountDto
     */
    refreshToken?: string;
    /**
     * ID token
     * @type {string}
     * @memberof LinkedAccountDto
     */
    idToken?: string;
    /**
     * Access token expires at
     * @type {Date}
     * @memberof LinkedAccountDto
     */
    accessTokenExpiresAt?: Date;
    /**
     * Refresh token expires at
     * @type {Date}
     * @memberof LinkedAccountDto
     */
    refreshTokenExpiresAt?: Date;
    /**
     * Scope
     * @type {string}
     * @memberof LinkedAccountDto
     */
    scope?: string;
    /**
     * Password
     * @type {string}
     * @memberof LinkedAccountDto
     */
    password?: string;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof LinkedAccountDto
     */
    createdAt: Date;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof LinkedAccountDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the LinkedAccountDto interface.
 */
export function instanceOfLinkedAccountDto(value: object): value is LinkedAccountDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function LinkedAccountDtoFromJSON(json: any): LinkedAccountDto {
    return LinkedAccountDtoFromJSONTyped(json, false);
}

export function LinkedAccountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkedAccountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'accountId': json['accountId'],
        'providerId': json['providerId'],
        'userId': json['userId'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'idToken': json['idToken'] == null ? undefined : json['idToken'],
        'accessTokenExpiresAt': json['accessTokenExpiresAt'] == null ? undefined : (new Date(json['accessTokenExpiresAt'])),
        'refreshTokenExpiresAt': json['refreshTokenExpiresAt'] == null ? undefined : (new Date(json['refreshTokenExpiresAt'])),
        'scope': json['scope'] == null ? undefined : json['scope'],
        'password': json['password'] == null ? undefined : json['password'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function LinkedAccountDtoToJSON(json: any): LinkedAccountDto {
    return LinkedAccountDtoToJSONTyped(json, false);
}

export function LinkedAccountDtoToJSONTyped(value?: LinkedAccountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'accountId': value['accountId'],
        'providerId': value['providerId'],
        'userId': value['userId'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'idToken': value['idToken'],
        'accessTokenExpiresAt': value['accessTokenExpiresAt'] == null ? value['accessTokenExpiresAt'] : value['accessTokenExpiresAt'].toISOString(),
        'refreshTokenExpiresAt': value['refreshTokenExpiresAt'] == null ? value['refreshTokenExpiresAt'] : value['refreshTokenExpiresAt'].toISOString(),
        'scope': value['scope'],
        'password': value['password'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

