/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkSocialDto
 */
export interface LinkSocialDto {
    /**
     * The social provider to link
     * @type {string}
     * @memberof LinkSocialDto
     */
    provider: string;
    /**
     * Access token from provider
     * @type {string}
     * @memberof LinkSocialDto
     */
    accessToken?: string;
    /**
     * Refresh token from provider
     * @type {string}
     * @memberof LinkSocialDto
     */
    refreshToken?: string;
    /**
     * ID token from provider
     * @type {string}
     * @memberof LinkSocialDto
     */
    idToken?: string;
    /**
     * Token expiration time
     * @type {number}
     * @memberof LinkSocialDto
     */
    expiresAt?: number;
}

/**
 * Check if a given object implements the LinkSocialDto interface.
 */
export function instanceOfLinkSocialDto(value: object): value is LinkSocialDto {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function LinkSocialDtoFromJSON(json: any): LinkSocialDto {
    return LinkSocialDtoFromJSONTyped(json, false);
}

export function LinkSocialDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkSocialDto {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'idToken': json['idToken'] == null ? undefined : json['idToken'],
        'expiresAt': json['expiresAt'] == null ? undefined : json['expiresAt'],
    };
}

export function LinkSocialDtoToJSON(json: any): LinkSocialDto {
    return LinkSocialDtoToJSONTyped(json, false);
}

export function LinkSocialDtoToJSONTyped(value?: LinkSocialDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'idToken': value['idToken'],
        'expiresAt': value['expiresAt'],
    };
}

