/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentLinkResponseDto } from './PaymentLinkResponseDto';
import {
    PaymentLinkResponseDtoFromJSON,
    PaymentLinkResponseDtoFromJSONTyped,
    PaymentLinkResponseDtoToJSON,
    PaymentLinkResponseDtoToJSONTyped,
} from './PaymentLinkResponseDto';
import type { PaginationResponseDto } from './PaginationResponseDto';
import {
    PaginationResponseDtoFromJSON,
    PaginationResponseDtoFromJSONTyped,
    PaginationResponseDtoToJSON,
    PaginationResponseDtoToJSONTyped,
} from './PaginationResponseDto';

/**
 * 
 * @export
 * @interface ListPaymentLinksResponseDto
 */
export interface ListPaymentLinksResponseDto {
    /**
     * 
     * @type {Array<PaymentLinkResponseDto>}
     * @memberof ListPaymentLinksResponseDto
     */
    data: Array<PaymentLinkResponseDto>;
    /**
     * 
     * @type {PaginationResponseDto}
     * @memberof ListPaymentLinksResponseDto
     */
    pagination: PaginationResponseDto;
}

/**
 * Check if a given object implements the ListPaymentLinksResponseDto interface.
 */
export function instanceOfListPaymentLinksResponseDto(value: object): value is ListPaymentLinksResponseDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListPaymentLinksResponseDtoFromJSON(json: any): ListPaymentLinksResponseDto {
    return ListPaymentLinksResponseDtoFromJSONTyped(json, false);
}

export function ListPaymentLinksResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPaymentLinksResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PaymentLinkResponseDtoFromJSON)),
        'pagination': PaginationResponseDtoFromJSON(json['pagination']),
    };
}

export function ListPaymentLinksResponseDtoToJSON(json: any): ListPaymentLinksResponseDto {
    return ListPaymentLinksResponseDtoToJSONTyped(json, false);
}

export function ListPaymentLinksResponseDtoToJSONTyped(value?: ListPaymentLinksResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PaymentLinkResponseDtoToJSON)),
        'pagination': PaginationResponseDtoToJSON(value['pagination']),
    };
}

