/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResponseDto } from './PaginationResponseDto';
import {
    PaginationResponseDtoFromJSON,
    PaginationResponseDtoFromJSONTyped,
    PaginationResponseDtoToJSON,
    PaginationResponseDtoToJSONTyped,
} from './PaginationResponseDto';
import type { MerchantBalanceResponseDto } from './MerchantBalanceResponseDto';
import {
    MerchantBalanceResponseDtoFromJSON,
    MerchantBalanceResponseDtoFromJSONTyped,
    MerchantBalanceResponseDtoToJSON,
    MerchantBalanceResponseDtoToJSONTyped,
} from './MerchantBalanceResponseDto';

/**
 * 
 * @export
 * @interface ListMerchantBalancesResponseDto
 */
export interface ListMerchantBalancesResponseDto {
    /**
     * 
     * @type {Array<MerchantBalanceResponseDto>}
     * @memberof ListMerchantBalancesResponseDto
     */
    data: Array<MerchantBalanceResponseDto>;
    /**
     * 
     * @type {PaginationResponseDto}
     * @memberof ListMerchantBalancesResponseDto
     */
    pagination: PaginationResponseDto;
}

/**
 * Check if a given object implements the ListMerchantBalancesResponseDto interface.
 */
export function instanceOfListMerchantBalancesResponseDto(value: object): value is ListMerchantBalancesResponseDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListMerchantBalancesResponseDtoFromJSON(json: any): ListMerchantBalancesResponseDto {
    return ListMerchantBalancesResponseDtoFromJSONTyped(json, false);
}

export function ListMerchantBalancesResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMerchantBalancesResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(MerchantBalanceResponseDtoFromJSON)),
        'pagination': PaginationResponseDtoFromJSON(json['pagination']),
    };
}

export function ListMerchantBalancesResponseDtoToJSON(json: any): ListMerchantBalancesResponseDto {
    return ListMerchantBalancesResponseDtoToJSONTyped(json, false);
}

export function ListMerchantBalancesResponseDtoToJSONTyped(value?: ListMerchantBalancesResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(MerchantBalanceResponseDtoToJSON)),
        'pagination': PaginationResponseDtoToJSON(value['pagination']),
    };
}

