/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResponseDto } from './PaginationResponseDto';
import {
    PaginationResponseDtoFromJSON,
    PaginationResponseDtoFromJSONTyped,
    PaginationResponseDtoToJSON,
    PaginationResponseDtoToJSONTyped,
} from './PaginationResponseDto';
import type { PayoutResponseDto } from './PayoutResponseDto';
import {
    PayoutResponseDtoFromJSON,
    PayoutResponseDtoFromJSONTyped,
    PayoutResponseDtoToJSON,
    PayoutResponseDtoToJSONTyped,
} from './PayoutResponseDto';

/**
 * 
 * @export
 * @interface ListPayoutsResponseDto
 */
export interface ListPayoutsResponseDto {
    /**
     * 
     * @type {Array<PayoutResponseDto>}
     * @memberof ListPayoutsResponseDto
     */
    data: Array<PayoutResponseDto>;
    /**
     * 
     * @type {PaginationResponseDto}
     * @memberof ListPayoutsResponseDto
     */
    pagination: PaginationResponseDto;
}

/**
 * Check if a given object implements the ListPayoutsResponseDto interface.
 */
export function instanceOfListPayoutsResponseDto(value: object): value is ListPayoutsResponseDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListPayoutsResponseDtoFromJSON(json: any): ListPayoutsResponseDto {
    return ListPayoutsResponseDtoFromJSONTyped(json, false);
}

export function ListPayoutsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPayoutsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PayoutResponseDtoFromJSON)),
        'pagination': PaginationResponseDtoFromJSON(json['pagination']),
    };
}

export function ListPayoutsResponseDtoToJSON(json: any): ListPayoutsResponseDto {
    return ListPayoutsResponseDtoToJSONTyped(json, false);
}

export function ListPayoutsResponseDtoToJSONTyped(value?: ListPayoutsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PayoutResponseDtoToJSON)),
        'pagination': PaginationResponseDtoToJSON(value['pagination']),
    };
}

