/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKey } from './ApiKey';
import {
    ApiKeyFromJSON,
    ApiKeyFromJSONTyped,
    ApiKeyToJSON,
    ApiKeyToJSONTyped,
} from './ApiKey';

/**
 * 
 * @export
 * @interface ListApiKeysResponseDto
 */
export interface ListApiKeysResponseDto {
    /**
     * List of API keys
     * @type {Array<ApiKey>}
     * @memberof ListApiKeysResponseDto
     */
    apiKeys: Array<ApiKey>;
}

/**
 * Check if a given object implements the ListApiKeysResponseDto interface.
 */
export function instanceOfListApiKeysResponseDto(value: object): value is ListApiKeysResponseDto {
    if (!('apiKeys' in value) || value['apiKeys'] === undefined) return false;
    return true;
}

export function ListApiKeysResponseDtoFromJSON(json: any): ListApiKeysResponseDto {
    return ListApiKeysResponseDtoFromJSONTyped(json, false);
}

export function ListApiKeysResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListApiKeysResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKeys': ((json['apiKeys'] as Array<any>).map(ApiKeyFromJSON)),
    };
}

export function ListApiKeysResponseDtoToJSON(json: any): ListApiKeysResponseDto {
    return ListApiKeysResponseDtoToJSONTyped(json, false);
}

export function ListApiKeysResponseDtoToJSONTyped(value?: ListApiKeysResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiKeys': ((value['apiKeys'] as Array<any>).map(ApiKeyToJSON)),
    };
}

