/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResponseDto } from './PaginationResponseDto';
import {
    PaginationResponseDtoFromJSON,
    PaginationResponseDtoFromJSONTyped,
    PaginationResponseDtoToJSON,
    PaginationResponseDtoToJSONTyped,
} from './PaginationResponseDto';
import type { PaymentIntentResponseDto } from './PaymentIntentResponseDto';
import {
    PaymentIntentResponseDtoFromJSON,
    PaymentIntentResponseDtoFromJSONTyped,
    PaymentIntentResponseDtoToJSON,
    PaymentIntentResponseDtoToJSONTyped,
} from './PaymentIntentResponseDto';

/**
 * 
 * @export
 * @interface ListPaymentIntentsResponseDto
 */
export interface ListPaymentIntentsResponseDto {
    /**
     * List of payment intents
     * @type {Array<PaymentIntentResponseDto>}
     * @memberof ListPaymentIntentsResponseDto
     */
    data: Array<PaymentIntentResponseDto>;
    /**
     * Pagination metadata
     * @type {PaginationResponseDto}
     * @memberof ListPaymentIntentsResponseDto
     */
    pagination: PaginationResponseDto;
}

/**
 * Check if a given object implements the ListPaymentIntentsResponseDto interface.
 */
export function instanceOfListPaymentIntentsResponseDto(value: object): value is ListPaymentIntentsResponseDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListPaymentIntentsResponseDtoFromJSON(json: any): ListPaymentIntentsResponseDto {
    return ListPaymentIntentsResponseDtoFromJSONTyped(json, false);
}

export function ListPaymentIntentsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPaymentIntentsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PaymentIntentResponseDtoFromJSON)),
        'pagination': PaginationResponseDtoFromJSON(json['pagination']),
    };
}

export function ListPaymentIntentsResponseDtoToJSON(json: any): ListPaymentIntentsResponseDto {
    return ListPaymentIntentsResponseDtoToJSONTyped(json, false);
}

export function ListPaymentIntentsResponseDtoToJSONTyped(value?: ListPaymentIntentsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PaymentIntentResponseDtoToJSON)),
        'pagination': PaginationResponseDtoToJSON(value['pagination']),
    };
}

