/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResponseDto } from './PaginationResponseDto';
import {
    PaginationResponseDtoFromJSON,
    PaginationResponseDtoFromJSONTyped,
    PaginationResponseDtoToJSON,
    PaginationResponseDtoToJSONTyped,
} from './PaginationResponseDto';
import type { TransferResponseDto } from './TransferResponseDto';
import {
    TransferResponseDtoFromJSON,
    TransferResponseDtoFromJSONTyped,
    TransferResponseDtoToJSON,
    TransferResponseDtoToJSONTyped,
} from './TransferResponseDto';

/**
 * 
 * @export
 * @interface ListTransfersResponseDto
 */
export interface ListTransfersResponseDto {
    /**
     * List of transfers
     * @type {Array<TransferResponseDto>}
     * @memberof ListTransfersResponseDto
     */
    data: Array<TransferResponseDto>;
    /**
     * Pagination metadata
     * @type {PaginationResponseDto}
     * @memberof ListTransfersResponseDto
     */
    pagination: PaginationResponseDto;
}

/**
 * Check if a given object implements the ListTransfersResponseDto interface.
 */
export function instanceOfListTransfersResponseDto(value: object): value is ListTransfersResponseDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListTransfersResponseDtoFromJSON(json: any): ListTransfersResponseDto {
    return ListTransfersResponseDtoFromJSONTyped(json, false);
}

export function ListTransfersResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTransfersResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TransferResponseDtoFromJSON)),
        'pagination': PaginationResponseDtoFromJSON(json['pagination']),
    };
}

export function ListTransfersResponseDtoToJSON(json: any): ListTransfersResponseDto {
    return ListTransfersResponseDtoToJSONTyped(json, false);
}

export function ListTransfersResponseDtoToJSONTyped(value?: ListTransfersResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(TransferResponseDtoToJSON)),
        'pagination': PaginationResponseDtoToJSON(value['pagination']),
    };
}

