/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResponseDto } from './PaginationResponseDto';
import {
    PaginationResponseDtoFromJSON,
    PaginationResponseDtoFromJSONTyped,
    PaginationResponseDtoToJSON,
    PaginationResponseDtoToJSONTyped,
} from './PaginationResponseDto';
import type { CustomerTransactionDto } from './CustomerTransactionDto';
import {
    CustomerTransactionDtoFromJSON,
    CustomerTransactionDtoFromJSONTyped,
    CustomerTransactionDtoToJSON,
    CustomerTransactionDtoToJSONTyped,
} from './CustomerTransactionDto';

/**
 * 
 * @export
 * @interface ListCustomerTransactionsResponseDto
 */
export interface ListCustomerTransactionsResponseDto {
    /**
     * 
     * @type {Array<CustomerTransactionDto>}
     * @memberof ListCustomerTransactionsResponseDto
     */
    data: Array<CustomerTransactionDto>;
    /**
     * 
     * @type {PaginationResponseDto}
     * @memberof ListCustomerTransactionsResponseDto
     */
    pagination: PaginationResponseDto;
}

/**
 * Check if a given object implements the ListCustomerTransactionsResponseDto interface.
 */
export function instanceOfListCustomerTransactionsResponseDto(value: object): value is ListCustomerTransactionsResponseDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListCustomerTransactionsResponseDtoFromJSON(json: any): ListCustomerTransactionsResponseDto {
    return ListCustomerTransactionsResponseDtoFromJSONTyped(json, false);
}

export function ListCustomerTransactionsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCustomerTransactionsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CustomerTransactionDtoFromJSON)),
        'pagination': PaginationResponseDtoFromJSON(json['pagination']),
    };
}

export function ListCustomerTransactionsResponseDtoToJSON(json: any): ListCustomerTransactionsResponseDto {
    return ListCustomerTransactionsResponseDtoToJSONTyped(json, false);
}

export function ListCustomerTransactionsResponseDtoToJSONTyped(value?: ListCustomerTransactionsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(CustomerTransactionDtoToJSON)),
        'pagination': PaginationResponseDtoToJSON(value['pagination']),
    };
}

