/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEndpointResponseDto } from './WebhookEndpointResponseDto';
import {
    WebhookEndpointResponseDtoFromJSON,
    WebhookEndpointResponseDtoFromJSONTyped,
    WebhookEndpointResponseDtoToJSON,
    WebhookEndpointResponseDtoToJSONTyped,
} from './WebhookEndpointResponseDto';
import type { PaginationResponseDto } from './PaginationResponseDto';
import {
    PaginationResponseDtoFromJSON,
    PaginationResponseDtoFromJSONTyped,
    PaginationResponseDtoToJSON,
    PaginationResponseDtoToJSONTyped,
} from './PaginationResponseDto';

/**
 * 
 * @export
 * @interface ListWebhookEndpointsResponseDto
 */
export interface ListWebhookEndpointsResponseDto {
    /**
     * 
     * @type {Array<WebhookEndpointResponseDto>}
     * @memberof ListWebhookEndpointsResponseDto
     */
    data: Array<WebhookEndpointResponseDto>;
    /**
     * 
     * @type {PaginationResponseDto}
     * @memberof ListWebhookEndpointsResponseDto
     */
    pagination: PaginationResponseDto;
}

/**
 * Check if a given object implements the ListWebhookEndpointsResponseDto interface.
 */
export function instanceOfListWebhookEndpointsResponseDto(value: object): value is ListWebhookEndpointsResponseDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListWebhookEndpointsResponseDtoFromJSON(json: any): ListWebhookEndpointsResponseDto {
    return ListWebhookEndpointsResponseDtoFromJSONTyped(json, false);
}

export function ListWebhookEndpointsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWebhookEndpointsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(WebhookEndpointResponseDtoFromJSON)),
        'pagination': PaginationResponseDtoFromJSON(json['pagination']),
    };
}

export function ListWebhookEndpointsResponseDtoToJSON(json: any): ListWebhookEndpointsResponseDto {
    return ListWebhookEndpointsResponseDtoToJSONTyped(json, false);
}

export function ListWebhookEndpointsResponseDtoToJSONTyped(value?: ListWebhookEndpointsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(WebhookEndpointResponseDtoToJSON)),
        'pagination': PaginationResponseDtoToJSON(value['pagination']),
    };
}

