/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResponseDto } from './PaginationResponseDto';
import {
    PaginationResponseDtoFromJSON,
    PaginationResponseDtoFromJSONTyped,
    PaginationResponseDtoToJSON,
    PaginationResponseDtoToJSONTyped,
} from './PaginationResponseDto';
import type { CustomerPaymentMethodDto } from './CustomerPaymentMethodDto';
import {
    CustomerPaymentMethodDtoFromJSON,
    CustomerPaymentMethodDtoFromJSONTyped,
    CustomerPaymentMethodDtoToJSON,
    CustomerPaymentMethodDtoToJSONTyped,
} from './CustomerPaymentMethodDto';

/**
 * 
 * @export
 * @interface ListCustomerPaymentMethodsResponseDto
 */
export interface ListCustomerPaymentMethodsResponseDto {
    /**
     * 
     * @type {Array<CustomerPaymentMethodDto>}
     * @memberof ListCustomerPaymentMethodsResponseDto
     */
    data: Array<CustomerPaymentMethodDto>;
    /**
     * 
     * @type {PaginationResponseDto}
     * @memberof ListCustomerPaymentMethodsResponseDto
     */
    pagination: PaginationResponseDto;
}

/**
 * Check if a given object implements the ListCustomerPaymentMethodsResponseDto interface.
 */
export function instanceOfListCustomerPaymentMethodsResponseDto(value: object): value is ListCustomerPaymentMethodsResponseDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListCustomerPaymentMethodsResponseDtoFromJSON(json: any): ListCustomerPaymentMethodsResponseDto {
    return ListCustomerPaymentMethodsResponseDtoFromJSONTyped(json, false);
}

export function ListCustomerPaymentMethodsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCustomerPaymentMethodsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CustomerPaymentMethodDtoFromJSON)),
        'pagination': PaginationResponseDtoFromJSON(json['pagination']),
    };
}

export function ListCustomerPaymentMethodsResponseDtoToJSON(json: any): ListCustomerPaymentMethodsResponseDto {
    return ListCustomerPaymentMethodsResponseDtoToJSONTyped(json, false);
}

export function ListCustomerPaymentMethodsResponseDtoToJSONTyped(value?: ListCustomerPaymentMethodsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(CustomerPaymentMethodDtoToJSON)),
        'pagination': PaginationResponseDtoToJSON(value['pagination']),
    };
}

