/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvitationDto } from './InvitationDto';
import {
    InvitationDtoFromJSON,
    InvitationDtoFromJSONTyped,
    InvitationDtoToJSON,
    InvitationDtoToJSONTyped,
} from './InvitationDto';

/**
 * 
 * @export
 * @interface ListInvitationsResponseDto
 */
export interface ListInvitationsResponseDto {
    /**
     * List of invitations
     * @type {Array<InvitationDto>}
     * @memberof ListInvitationsResponseDto
     */
    invitations: Array<InvitationDto>;
}

/**
 * Check if a given object implements the ListInvitationsResponseDto interface.
 */
export function instanceOfListInvitationsResponseDto(value: object): value is ListInvitationsResponseDto {
    if (!('invitations' in value) || value['invitations'] === undefined) return false;
    return true;
}

export function ListInvitationsResponseDtoFromJSON(json: any): ListInvitationsResponseDto {
    return ListInvitationsResponseDtoFromJSONTyped(json, false);
}

export function ListInvitationsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInvitationsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'invitations': ((json['invitations'] as Array<any>).map(InvitationDtoFromJSON)),
    };
}

export function ListInvitationsResponseDtoToJSON(json: any): ListInvitationsResponseDto {
    return ListInvitationsResponseDtoToJSONTyped(json, false);
}

export function ListInvitationsResponseDtoToJSONTyped(value?: ListInvitationsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invitations': ((value['invitations'] as Array<any>).map(InvitationDtoToJSON)),
    };
}

