/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResponseDto } from './PaginationResponseDto';
import {
    PaginationResponseDtoFromJSON,
    PaginationResponseDtoFromJSONTyped,
    PaginationResponseDtoToJSON,
    PaginationResponseDtoToJSONTyped,
} from './PaginationResponseDto';
import type { PaymentMethodResponseDto } from './PaymentMethodResponseDto';
import {
    PaymentMethodResponseDtoFromJSON,
    PaymentMethodResponseDtoFromJSONTyped,
    PaymentMethodResponseDtoToJSON,
    PaymentMethodResponseDtoToJSONTyped,
} from './PaymentMethodResponseDto';

/**
 * 
 * @export
 * @interface ListPaymentMethodsResponseDto
 */
export interface ListPaymentMethodsResponseDto {
    /**
     * 
     * @type {Array<PaymentMethodResponseDto>}
     * @memberof ListPaymentMethodsResponseDto
     */
    data: Array<PaymentMethodResponseDto>;
    /**
     * 
     * @type {PaginationResponseDto}
     * @memberof ListPaymentMethodsResponseDto
     */
    pagination: PaginationResponseDto;
}

/**
 * Check if a given object implements the ListPaymentMethodsResponseDto interface.
 */
export function instanceOfListPaymentMethodsResponseDto(value: object): value is ListPaymentMethodsResponseDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListPaymentMethodsResponseDtoFromJSON(json: any): ListPaymentMethodsResponseDto {
    return ListPaymentMethodsResponseDtoFromJSONTyped(json, false);
}

export function ListPaymentMethodsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPaymentMethodsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PaymentMethodResponseDtoFromJSON)),
        'pagination': PaginationResponseDtoFromJSON(json['pagination']),
    };
}

export function ListPaymentMethodsResponseDtoToJSON(json: any): ListPaymentMethodsResponseDto {
    return ListPaymentMethodsResponseDtoToJSONTyped(json, false);
}

export function ListPaymentMethodsResponseDtoToJSONTyped(value?: ListPaymentMethodsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PaymentMethodResponseDtoToJSON)),
        'pagination': PaginationResponseDtoToJSON(value['pagination']),
    };
}

