/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemberDto
 */
export interface MemberDto {
    /**
     * Member ID
     * @type {string}
     * @memberof MemberDto
     */
    id: string;
    /**
     * User ID
     * @type {string}
     * @memberof MemberDto
     */
    userId: string;
    /**
     * Organization ID
     * @type {string}
     * @memberof MemberDto
     */
    organizationId: string;
    /**
     * Member role
     * @type {string}
     * @memberof MemberDto
     */
    role: string;
    /**
     * Member creation date
     * @type {string}
     * @memberof MemberDto
     */
    createdAt: string;
}

/**
 * Check if a given object implements the MemberDto interface.
 */
export function instanceOfMemberDto(value: object): value is MemberDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function MemberDtoFromJSON(json: any): MemberDto {
    return MemberDtoFromJSONTyped(json, false);
}

export function MemberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'organizationId': json['organizationId'],
        'role': json['role'],
        'createdAt': json['createdAt'],
    };
}

export function MemberDtoToJSON(json: any): MemberDto {
    return MemberDtoToJSONTyped(json, false);
}

export function MemberDtoToJSONTyped(value?: MemberDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'organizationId': value['organizationId'],
        'role': value['role'],
        'createdAt': value['createdAt'],
    };
}

