/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricStatsDto
 */
export interface MetricStatsDto {
    /**
     * Count of items
     * @type {number}
     * @memberof MetricStatsDto
     */
    count: number;
    /**
     * Sum of amounts in cents/smallest unit
     * @type {number}
     * @memberof MetricStatsDto
     */
    sum: number;
}

/**
 * Check if a given object implements the MetricStatsDto interface.
 */
export function instanceOfMetricStatsDto(value: object): value is MetricStatsDto {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('sum' in value) || value['sum'] === undefined) return false;
    return true;
}

export function MetricStatsDtoFromJSON(json: any): MetricStatsDto {
    return MetricStatsDtoFromJSONTyped(json, false);
}

export function MetricStatsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricStatsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'sum': json['sum'],
    };
}

export function MetricStatsDtoToJSON(json: any): MetricStatsDto {
    return MetricStatsDtoToJSONTyped(json, false);
}

export function MetricStatsDtoToJSONTyped(value?: MetricStatsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'sum': value['sum'],
    };
}

