/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendSmsDto } from './SendSmsDto';
import {
    SendSmsDtoFromJSON,
    SendSmsDtoFromJSONTyped,
    SendSmsDtoToJSON,
    SendSmsDtoToJSONTyped,
} from './SendSmsDto';
import type { SendEmailDto } from './SendEmailDto';
import {
    SendEmailDtoFromJSON,
    SendEmailDtoFromJSONTyped,
    SendEmailDtoToJSON,
    SendEmailDtoToJSONTyped,
} from './SendEmailDto';

/**
 * 
 * @export
 * @interface NotificationDto
 */
export interface NotificationDto {
    /**
     * Notification channel
     * @type {string}
     * @memberof NotificationDto
     */
    channel: NotificationDtoChannelEnum;
    /**
     * Email notification data
     * @type {SendEmailDto}
     * @memberof NotificationDto
     */
    email?: SendEmailDto;
    /**
     * SMS notification data
     * @type {SendSmsDto}
     * @memberof NotificationDto
     */
    sms?: SendSmsDto;
}


/**
 * @export
 */
export const NotificationDtoChannelEnum = {
    Email: 'email',
    Sms: 'sms'
} as const;
export type NotificationDtoChannelEnum = typeof NotificationDtoChannelEnum[keyof typeof NotificationDtoChannelEnum];


/**
 * Check if a given object implements the NotificationDto interface.
 */
export function instanceOfNotificationDto(value: object): value is NotificationDto {
    if (!('channel' in value) || value['channel'] === undefined) return false;
    return true;
}

export function NotificationDtoFromJSON(json: any): NotificationDto {
    return NotificationDtoFromJSONTyped(json, false);
}

export function NotificationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'channel': json['channel'],
        'email': json['email'] == null ? undefined : SendEmailDtoFromJSON(json['email']),
        'sms': json['sms'] == null ? undefined : SendSmsDtoFromJSON(json['sms']),
    };
}

export function NotificationDtoToJSON(json: any): NotificationDto {
    return NotificationDtoToJSONTyped(json, false);
}

export function NotificationDtoToJSONTyped(value?: NotificationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel': value['channel'],
        'email': SendEmailDtoToJSON(value['email']),
        'sms': SendSmsDtoToJSON(value['sms']),
    };
}

