/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationDto
 */
export interface OrganizationDto {
    /**
     * Organization ID
     * @type {string}
     * @memberof OrganizationDto
     */
    id: string;
    /**
     * Organization name
     * @type {string}
     * @memberof OrganizationDto
     */
    name: string;
    /**
     * Organization slug
     * @type {string}
     * @memberof OrganizationDto
     */
    slug: string;
    /**
     * Organization logo
     * @type {string}
     * @memberof OrganizationDto
     */
    logo?: string;
    /**
     * Organization creation date
     * @type {string}
     * @memberof OrganizationDto
     */
    createdAt: string;
    /**
     * Organization metadata
     * @type {object}
     * @memberof OrganizationDto
     */
    metadata?: object;
}

/**
 * Check if a given object implements the OrganizationDto interface.
 */
export function instanceOfOrganizationDto(value: object): value is OrganizationDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function OrganizationDtoFromJSON(json: any): OrganizationDto {
    return OrganizationDtoFromJSONTyped(json, false);
}

export function OrganizationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'createdAt': json['createdAt'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function OrganizationDtoToJSON(json: any): OrganizationDto {
    return OrganizationDtoToJSONTyped(json, false);
}

export function OrganizationDtoToJSONTyped(value?: OrganizationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'logo': value['logo'],
        'createdAt': value['createdAt'],
        'metadata': value['metadata'],
    };
}

