/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationResponseDto
 */
export interface PaginationResponseDto {
    /**
     * Maximum number of items returned in this response
     * @type {number}
     * @memberof PaginationResponseDto
     */
    limit: number;
    /**
     * Number of items skipped before this response
     * @type {number}
     * @memberof PaginationResponseDto
     */
    offset: number;
    /**
     * Total number of items available
     * @type {number}
     * @memberof PaginationResponseDto
     */
    total: number;
    /**
     * Whether there are more items available beyond this response
     * @type {boolean}
     * @memberof PaginationResponseDto
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the PaginationResponseDto interface.
 */
export function instanceOfPaginationResponseDto(value: object): value is PaginationResponseDto {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function PaginationResponseDtoFromJSON(json: any): PaginationResponseDto {
    return PaginationResponseDtoFromJSONTyped(json, false);
}

export function PaginationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
        'hasMore': json['hasMore'],
    };
}

export function PaginationResponseDtoToJSON(json: any): PaginationResponseDto {
    return PaginationResponseDtoToJSONTyped(json, false);
}

export function PaginationResponseDtoToJSONTyped(value?: PaginationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
        'hasMore': value['hasMore'],
    };
}

