/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentMethodResponseDto
 */
export interface PaymentMethodResponseDto {
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponseDto
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponseDto
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponseDto
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponseDto
     */
    last4?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentMethodResponseDto
     */
    expiryMonth?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentMethodResponseDto
     */
    expiryYear?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentMethodResponseDto
     */
    isDefault: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PaymentMethodResponseDto
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the PaymentMethodResponseDto interface.
 */
export function instanceOfPaymentMethodResponseDto(value: object): value is PaymentMethodResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PaymentMethodResponseDtoFromJSON(json: any): PaymentMethodResponseDto {
    return PaymentMethodResponseDtoFromJSONTyped(json, false);
}

export function PaymentMethodResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'customerId': json['customerId'],
        'type': json['type'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'last4': json['last4'] == null ? undefined : json['last4'],
        'expiryMonth': json['expiryMonth'] == null ? undefined : json['expiryMonth'],
        'expiryYear': json['expiryYear'] == null ? undefined : json['expiryYear'],
        'isDefault': json['isDefault'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function PaymentMethodResponseDtoToJSON(json: any): PaymentMethodResponseDto {
    return PaymentMethodResponseDtoToJSONTyped(json, false);
}

export function PaymentMethodResponseDtoToJSONTyped(value?: PaymentMethodResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'customerId': value['customerId'],
        'type': value['type'],
        'brand': value['brand'],
        'last4': value['last4'],
        'expiryMonth': value['expiryMonth'],
        'expiryYear': value['expiryYear'],
        'isDefault': value['isDefault'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

