/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentIntentResponseDto
 */
export interface PaymentIntentResponseDto {
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentResponseDto
     */
    merchantId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentResponseDto
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentResponseDto
     */
    paymentMethodId: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentIntentResponseDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentResponseDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentResponseDto
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PaymentIntentResponseDto
     */
    metadata: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof PaymentIntentResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PaymentIntentResponseDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the PaymentIntentResponseDto interface.
 */
export function instanceOfPaymentIntentResponseDto(value: object): value is PaymentIntentResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('paymentMethodId' in value) || value['paymentMethodId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PaymentIntentResponseDtoFromJSON(json: any): PaymentIntentResponseDto {
    return PaymentIntentResponseDtoFromJSONTyped(json, false);
}

export function PaymentIntentResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentIntentResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'merchantId': json['merchantId'],
        'customerId': json['customerId'],
        'paymentMethodId': json['paymentMethodId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'status': json['status'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function PaymentIntentResponseDtoToJSON(json: any): PaymentIntentResponseDto {
    return PaymentIntentResponseDtoToJSONTyped(json, false);
}

export function PaymentIntentResponseDtoToJSONTyped(value?: PaymentIntentResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'merchantId': value['merchantId'],
        'customerId': value['customerId'],
        'paymentMethodId': value['paymentMethodId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'status': value['status'],
        'description': value['description'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

