/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentLinkResponseDto
 */
export interface PaymentLinkResponseDto {
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponseDto
     */
    merchantId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponseDto
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponseDto
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponseDto
     */
    customerId?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentLinkResponseDto
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponseDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponseDto
     */
    mode: PaymentLinkResponseDtoModeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentLinkResponseDto
     */
    active: boolean;
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponseDto
     */
    successUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponseDto
     */
    cancelUrl: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PaymentLinkResponseDto
     */
    metadata: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof PaymentLinkResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PaymentLinkResponseDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PaymentLinkResponseDto
     */
    deletedAt?: Date;
}


/**
 * @export
 */
export const PaymentLinkResponseDtoModeEnum = {
    Payment: 'payment',
    Setup: 'setup',
    Subscription: 'subscription'
} as const;
export type PaymentLinkResponseDtoModeEnum = typeof PaymentLinkResponseDtoModeEnum[keyof typeof PaymentLinkResponseDtoModeEnum];


/**
 * Check if a given object implements the PaymentLinkResponseDto interface.
 */
export function instanceOfPaymentLinkResponseDto(value: object): value is PaymentLinkResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('successUrl' in value) || value['successUrl'] === undefined) return false;
    if (!('cancelUrl' in value) || value['cancelUrl'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PaymentLinkResponseDtoFromJSON(json: any): PaymentLinkResponseDto {
    return PaymentLinkResponseDtoFromJSONTyped(json, false);
}

export function PaymentLinkResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentLinkResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'merchantId': json['merchantId'],
        'url': json['url'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'],
        'mode': json['mode'],
        'active': json['active'],
        'successUrl': json['successUrl'],
        'cancelUrl': json['cancelUrl'],
        'metadata': json['metadata'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
    };
}

export function PaymentLinkResponseDtoToJSON(json: any): PaymentLinkResponseDto {
    return PaymentLinkResponseDtoToJSONTyped(json, false);
}

export function PaymentLinkResponseDtoToJSONTyped(value?: PaymentLinkResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'merchantId': value['merchantId'],
        'url': value['url'],
        'productId': value['productId'],
        'customerId': value['customerId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'mode': value['mode'],
        'active': value['active'],
        'successUrl': value['successUrl'],
        'cancelUrl': value['cancelUrl'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'deletedAt': value['deletedAt'] == null ? value['deletedAt'] : value['deletedAt'].toISOString(),
    };
}

