/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentMethodResponseDto
 */
export interface PaymentMethodResponseDto {
    /**
     * Unique payment method identifier
     * @type {string}
     * @memberof PaymentMethodResponseDto
     */
    id: string;
    /**
     * Customer ID this payment method belongs to
     * @type {string}
     * @memberof PaymentMethodResponseDto
     */
    customerId: string;
    /**
     * Payment method type (e.g., card, mobile_money)
     * @type {string}
     * @memberof PaymentMethodResponseDto
     */
    type: string;
    /**
     * Payment provider name (e.g., iveri, mpesa)
     * @type {string}
     * @memberof PaymentMethodResponseDto
     */
    provider: string;
    /**
     * Card brand (e.g., Visa, Mastercard)
     * @type {string}
     * @memberof PaymentMethodResponseDto
     */
    brand?: string;
    /**
     * Last 4 digits of card number
     * @type {string}
     * @memberof PaymentMethodResponseDto
     */
    last4?: string;
    /**
     * Card expiry month (1-12)
     * @type {number}
     * @memberof PaymentMethodResponseDto
     */
    expiryMonth?: number;
    /**
     * Card expiry year
     * @type {number}
     * @memberof PaymentMethodResponseDto
     */
    expiryYear?: number;
    /**
     * Phone number for mobile money
     * @type {string}
     * @memberof PaymentMethodResponseDto
     */
    phoneNumber?: string;
    /**
     * Whether this is the default payment method
     * @type {boolean}
     * @memberof PaymentMethodResponseDto
     */
    isDefault: boolean;
    /**
     * When the payment method was created
     * @type {Date}
     * @memberof PaymentMethodResponseDto
     */
    createdAt: Date;
    /**
     * When the payment method was last updated
     * @type {Date}
     * @memberof PaymentMethodResponseDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the PaymentMethodResponseDto interface.
 */
export function instanceOfPaymentMethodResponseDto(value: object): value is PaymentMethodResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PaymentMethodResponseDtoFromJSON(json: any): PaymentMethodResponseDto {
    return PaymentMethodResponseDtoFromJSONTyped(json, false);
}

export function PaymentMethodResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'customerId': json['customerId'],
        'type': json['type'],
        'provider': json['provider'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'last4': json['last4'] == null ? undefined : json['last4'],
        'expiryMonth': json['expiryMonth'] == null ? undefined : json['expiryMonth'],
        'expiryYear': json['expiryYear'] == null ? undefined : json['expiryYear'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'isDefault': json['isDefault'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function PaymentMethodResponseDtoToJSON(json: any): PaymentMethodResponseDto {
    return PaymentMethodResponseDtoToJSONTyped(json, false);
}

export function PaymentMethodResponseDtoToJSONTyped(value?: PaymentMethodResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'customerId': value['customerId'],
        'type': value['type'],
        'provider': value['provider'],
        'brand': value['brand'],
        'last4': value['last4'],
        'expiryMonth': value['expiryMonth'],
        'expiryYear': value['expiryYear'],
        'phoneNumber': value['phoneNumber'],
        'isDefault': value['isDefault'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

