/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayoutResponseDto
 */
export interface PayoutResponseDto {
    /**
     * 
     * @type {string}
     * @memberof PayoutResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PayoutResponseDto
     */
    merchantId: string;
    /**
     * 
     * @type {number}
     * @memberof PayoutResponseDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof PayoutResponseDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof PayoutResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof PayoutResponseDto
     */
    bankAccount?: string;
    /**
     * 
     * @type {string}
     * @memberof PayoutResponseDto
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PayoutResponseDto
     */
    metadata: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof PayoutResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PayoutResponseDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the PayoutResponseDto interface.
 */
export function instanceOfPayoutResponseDto(value: object): value is PayoutResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PayoutResponseDtoFromJSON(json: any): PayoutResponseDto {
    return PayoutResponseDtoFromJSONTyped(json, false);
}

export function PayoutResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayoutResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'merchantId': json['merchantId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'status': json['status'],
        'bankAccount': json['bankAccount'] == null ? undefined : json['bankAccount'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function PayoutResponseDtoToJSON(json: any): PayoutResponseDto {
    return PayoutResponseDtoToJSONTyped(json, false);
}

export function PayoutResponseDtoToJSONTyped(value?: PayoutResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'merchantId': value['merchantId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'status': value['status'],
        'bankAccount': value['bankAccount'],
        'description': value['description'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

