/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PresignedUploadResponseDto
 */
export interface PresignedUploadResponseDto {
    /**
     * Presigned upload URL
     * @type {string}
     * @memberof PresignedUploadResponseDto
     */
    uploadUrl: string;
    /**
     * File ID for tracking
     * @type {string}
     * @memberof PresignedUploadResponseDto
     */
    fileId: string;
    /**
     * S3 object key
     * @type {string}
     * @memberof PresignedUploadResponseDto
     */
    key: string;
    /**
     * URL expiration time
     * @type {Date}
     * @memberof PresignedUploadResponseDto
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the PresignedUploadResponseDto interface.
 */
export function instanceOfPresignedUploadResponseDto(value: object): value is PresignedUploadResponseDto {
    if (!('uploadUrl' in value) || value['uploadUrl'] === undefined) return false;
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function PresignedUploadResponseDtoFromJSON(json: any): PresignedUploadResponseDto {
    return PresignedUploadResponseDtoFromJSONTyped(json, false);
}

export function PresignedUploadResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresignedUploadResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'uploadUrl': json['uploadUrl'],
        'fileId': json['fileId'],
        'key': json['key'],
        'expiresAt': (new Date(json['expiresAt'])),
    };
}

export function PresignedUploadResponseDtoToJSON(json: any): PresignedUploadResponseDto {
    return PresignedUploadResponseDtoToJSONTyped(json, false);
}

export function PresignedUploadResponseDtoToJSONTyped(value?: PresignedUploadResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uploadUrl': value['uploadUrl'],
        'fileId': value['fileId'],
        'key': value['key'],
        'expiresAt': value['expiresAt'].toISOString(),
    };
}

