/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductResponseDto
 */
export interface ProductResponseDto {
    /**
     * Unique identifier
     * @type {string}
     * @memberof ProductResponseDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductResponseDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductResponseDto
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    merchantId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseDto
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    currency: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductResponseDto
     */
    active: boolean;
    /**
     * The ID of the product image file
     * @type {string}
     * @memberof ProductResponseDto
     */
    imageId?: string;
    /**
     * The public URL of the product image
     * @type {string}
     * @memberof ProductResponseDto
     */
    imageUrl?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ProductResponseDto
     */
    metadata: { [key: string]: any; };
}

/**
 * Check if a given object implements the ProductResponseDto interface.
 */
export function instanceOfProductResponseDto(value: object): value is ProductResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function ProductResponseDtoFromJSON(json: any): ProductResponseDto {
    return ProductResponseDtoFromJSONTyped(json, false);
}

export function ProductResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'merchantId': json['merchantId'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'],
        'active': json['active'],
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'metadata': json['metadata'],
    };
}

export function ProductResponseDtoToJSON(json: any): ProductResponseDto {
    return ProductResponseDtoToJSONTyped(json, false);
}

export function ProductResponseDtoToJSONTyped(value?: ProductResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'deletedAt': value['deletedAt'] == null ? value['deletedAt'] : value['deletedAt'].toISOString(),
        'merchantId': value['merchantId'],
        'name': value['name'],
        'description': value['description'],
        'amount': value['amount'],
        'currency': value['currency'],
        'active': value['active'],
        'imageId': value['imageId'],
        'imageUrl': value['imageUrl'],
        'metadata': value['metadata'],
    };
}

