/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveMemberDto
 */
export interface RemoveMemberDto {
    /**
     * The ID of the member to remove
     * @type {string}
     * @memberof RemoveMemberDto
     */
    memberId: string;
    /**
     * The ID of the organization
     * @type {string}
     * @memberof RemoveMemberDto
     */
    organizationId: string;
}

/**
 * Check if a given object implements the RemoveMemberDto interface.
 */
export function instanceOfRemoveMemberDto(value: object): value is RemoveMemberDto {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function RemoveMemberDtoFromJSON(json: any): RemoveMemberDto {
    return RemoveMemberDtoFromJSONTyped(json, false);
}

export function RemoveMemberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveMemberDto {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['memberId'],
        'organizationId': json['organizationId'],
    };
}

export function RemoveMemberDtoToJSON(json: any): RemoveMemberDto {
    return RemoveMemberDtoToJSONTyped(json, false);
}

export function RemoveMemberDtoToJSONTyped(value?: RemoveMemberDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memberId': value['memberId'],
        'organizationId': value['organizationId'],
    };
}

