/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPasswordResetResponseDto
 */
export interface RequestPasswordResetResponseDto {
    /**
     * Request status
     * @type {boolean}
     * @memberof RequestPasswordResetResponseDto
     */
    status: boolean;
    /**
     * Response message
     * @type {string}
     * @memberof RequestPasswordResetResponseDto
     */
    message?: string;
}

/**
 * Check if a given object implements the RequestPasswordResetResponseDto interface.
 */
export function instanceOfRequestPasswordResetResponseDto(value: object): value is RequestPasswordResetResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RequestPasswordResetResponseDtoFromJSON(json: any): RequestPasswordResetResponseDto {
    return RequestPasswordResetResponseDtoFromJSONTyped(json, false);
}

export function RequestPasswordResetResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPasswordResetResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function RequestPasswordResetResponseDtoToJSON(json: any): RequestPasswordResetResponseDto {
    return RequestPasswordResetResponseDtoToJSONTyped(json, false);
}

export function RequestPasswordResetResponseDtoToJSONTyped(value?: RequestPasswordResetResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
    };
}

