/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPasswordCallbackResponseDto
 */
export interface ResetPasswordCallbackResponseDto {
    /**
     * Password reset token
     * @type {string}
     * @memberof ResetPasswordCallbackResponseDto
     */
    token: string;
}

/**
 * Check if a given object implements the ResetPasswordCallbackResponseDto interface.
 */
export function instanceOfResetPasswordCallbackResponseDto(value: object): value is ResetPasswordCallbackResponseDto {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function ResetPasswordCallbackResponseDtoFromJSON(json: any): ResetPasswordCallbackResponseDto {
    return ResetPasswordCallbackResponseDtoFromJSONTyped(json, false);
}

export function ResetPasswordCallbackResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordCallbackResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function ResetPasswordCallbackResponseDtoToJSON(json: any): ResetPasswordCallbackResponseDto {
    return ResetPasswordCallbackResponseDtoToJSONTyped(json, false);
}

export function ResetPasswordCallbackResponseDtoToJSONTyped(value?: ResetPasswordCallbackResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

