/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetrieveMultipleProductsDto
 */
export interface RetrieveMultipleProductsDto {
    /**
     * Max 50 IDs of the products to retrieve
     * @type {Array<string>}
     * @memberof RetrieveMultipleProductsDto
     */
    ids: Array<string>;
}

/**
 * Check if a given object implements the RetrieveMultipleProductsDto interface.
 */
export function instanceOfRetrieveMultipleProductsDto(value: object): value is RetrieveMultipleProductsDto {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function RetrieveMultipleProductsDtoFromJSON(json: any): RetrieveMultipleProductsDto {
    return RetrieveMultipleProductsDtoFromJSONTyped(json, false);
}

export function RetrieveMultipleProductsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveMultipleProductsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
    };
}

export function RetrieveMultipleProductsDtoToJSON(json: any): RetrieveMultipleProductsDto {
    return RetrieveMultipleProductsDtoToJSONTyped(json, false);
}

export function RetrieveMultipleProductsDtoToJSONTyped(value?: RetrieveMultipleProductsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
    };
}

