/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendSmsDto
 */
export interface SendSmsDto {
    /**
     * Recipient phone number(s) in international format
     * @type {object}
     * @memberof SendSmsDto
     */
    to: object;
    /**
     * SMS message content
     * @type {string}
     * @memberof SendSmsDto
     */
    message: string;
    /**
     * Sender name or number
     * @type {string}
     * @memberof SendSmsDto
     */
    from?: string;
}

/**
 * Check if a given object implements the SendSmsDto interface.
 */
export function instanceOfSendSmsDto(value: object): value is SendSmsDto {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SendSmsDtoFromJSON(json: any): SendSmsDto {
    return SendSmsDtoFromJSONTyped(json, false);
}

export function SendSmsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendSmsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'message': json['message'],
        'from': json['from'] == null ? undefined : json['from'],
    };
}

export function SendSmsDtoToJSON(json: any): SendSmsDto {
    return SendSmsDtoToJSONTyped(json, false);
}

export function SendSmsDtoToJSONTyped(value?: SendSmsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'message': value['message'],
        'from': value['from'],
    };
}

