/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendVerificationEmailResponseDto
 */
export interface SendVerificationEmailResponseDto {
    /**
     * Indicates if email was sent successfully
     * @type {boolean}
     * @memberof SendVerificationEmailResponseDto
     */
    status: boolean;
}

/**
 * Check if a given object implements the SendVerificationEmailResponseDto interface.
 */
export function instanceOfSendVerificationEmailResponseDto(value: object): value is SendVerificationEmailResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SendVerificationEmailResponseDtoFromJSON(json: any): SendVerificationEmailResponseDto {
    return SendVerificationEmailResponseDtoFromJSONTyped(json, false);
}

export function SendVerificationEmailResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendVerificationEmailResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function SendVerificationEmailResponseDtoToJSON(json: any): SendVerificationEmailResponseDto {
    return SendVerificationEmailResponseDtoToJSONTyped(json, false);
}

export function SendVerificationEmailResponseDtoToJSONTyped(value?: SendVerificationEmailResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

