/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendSms200Response
 */
export interface SendSms200Response {
    /**
     * SMS message ID
     * @type {string}
     * @memberof SendSms200Response
     */
    messageId?: string;
}

/**
 * Check if a given object implements the SendSms200Response interface.
 */
export function instanceOfSendSms200Response(value: object): value is SendSms200Response {
    return true;
}

export function SendSms200ResponseFromJSON(json: any): SendSms200Response {
    return SendSms200ResponseFromJSONTyped(json, false);
}

export function SendSms200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendSms200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'messageId': json['messageId'] == null ? undefined : json['messageId'],
    };
}

export function SendSms200ResponseToJSON(json: any): SendSms200Response {
    return SendSms200ResponseToJSONTyped(json, false);
}

export function SendSms200ResponseToJSONTyped(value?: SendSms200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageId': value['messageId'],
    };
}

