/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendEmailDto
 */
export interface SendEmailDto {
    /**
     * Recipient email address(es)
     * @type {object}
     * @memberof SendEmailDto
     */
    to: object;
    /**
     * Email subject
     * @type {string}
     * @memberof SendEmailDto
     */
    subject: string;
    /**
     * Template name to use (if using templates)
     * @type {string}
     * @memberof SendEmailDto
     */
    template?: string;
    /**
     * Context variables for template rendering
     * @type {object}
     * @memberof SendEmailDto
     */
    context?: object;
    /**
     * HTML content (if not using templates)
     * @type {string}
     * @memberof SendEmailDto
     */
    html?: string;
    /**
     * Plain text content
     * @type {string}
     * @memberof SendEmailDto
     */
    text?: string;
    /**
     * Sender email address
     * @type {string}
     * @memberof SendEmailDto
     */
    from?: string;
    /**
     * CC email address(es)
     * @type {object}
     * @memberof SendEmailDto
     */
    cc?: object;
    /**
     * BCC email address(es)
     * @type {object}
     * @memberof SendEmailDto
     */
    bcc?: object;
}

/**
 * Check if a given object implements the SendEmailDto interface.
 */
export function instanceOfSendEmailDto(value: object): value is SendEmailDto {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    return true;
}

export function SendEmailDtoFromJSON(json: any): SendEmailDto {
    return SendEmailDtoFromJSONTyped(json, false);
}

export function SendEmailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEmailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'subject': json['subject'],
        'template': json['template'] == null ? undefined : json['template'],
        'context': json['context'] == null ? undefined : json['context'],
        'html': json['html'] == null ? undefined : json['html'],
        'text': json['text'] == null ? undefined : json['text'],
        'from': json['from'] == null ? undefined : json['from'],
        'cc': json['cc'] == null ? undefined : json['cc'],
        'bcc': json['bcc'] == null ? undefined : json['bcc'],
    };
}

export function SendEmailDtoToJSON(json: any): SendEmailDto {
    return SendEmailDtoToJSONTyped(json, false);
}

export function SendEmailDtoToJSONTyped(value?: SendEmailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'subject': value['subject'],
        'template': value['template'],
        'context': value['context'],
        'html': value['html'],
        'text': value['text'],
        'from': value['from'],
        'cc': value['cc'],
        'bcc': value['bcc'],
    };
}

