/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionDto
 */
export interface SessionDto {
    /**
     * 
     * @type {string}
     * @memberof SessionDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SessionDto
     */
    userId: string;
    /**
     * 
     * @type {Date}
     * @memberof SessionDto
     */
    expiresAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SessionDto
     */
    ipAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionDto
     */
    userAgent?: string;
}

/**
 * Check if a given object implements the SessionDto interface.
 */
export function instanceOfSessionDto(value: object): value is SessionDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function SessionDtoFromJSON(json: any): SessionDto {
    return SessionDtoFromJSONTyped(json, false);
}

export function SessionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'expiresAt': (new Date(json['expiresAt'])),
        'ipAddress': json['ipAddress'] == null ? undefined : json['ipAddress'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
    };
}

export function SessionDtoToJSON(json: any): SessionDto {
    return SessionDtoToJSONTyped(json, false);
}

export function SessionDtoToJSONTyped(value?: SessionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'expiresAt': value['expiresAt'].toISOString(),
        'ipAddress': value['ipAddress'],
        'userAgent': value['userAgent'],
    };
}

