/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetRoleDto
 */
export interface SetRoleDto {
    /**
     * The ID of the user
     * @type {string}
     * @memberof SetRoleDto
     */
    userId: string;
    /**
     * The role to assign
     * @type {string}
     * @memberof SetRoleDto
     */
    role: string;
}

/**
 * Check if a given object implements the SetRoleDto interface.
 */
export function instanceOfSetRoleDto(value: object): value is SetRoleDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function SetRoleDtoFromJSON(json: any): SetRoleDto {
    return SetRoleDtoFromJSONTyped(json, false);
}

export function SetRoleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetRoleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'role': json['role'],
    };
}

export function SetRoleDtoToJSON(json: any): SetRoleDto {
    return SetRoleDtoToJSONTyped(json, false);
}

export function SetRoleDtoToJSONTyped(value?: SetRoleDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'role': value['role'],
    };
}

