/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInDto
 */
export interface SignInDto {
    /**
     * The email address of the user
     * @type {string}
     * @memberof SignInDto
     */
    email: string;
    /**
     * The password for the user account
     * @type {string}
     * @memberof SignInDto
     */
    password: string;
    /**
     * The URL to use for email verification callback
     * @type {string}
     * @memberof SignInDto
     */
    callbackURL?: string;
    /**
     * If this is false, the session will not be remembered. Default is `true`.
     * @type {boolean}
     * @memberof SignInDto
     */
    rememberMe?: boolean;
}

/**
 * Check if a given object implements the SignInDto interface.
 */
export function instanceOfSignInDto(value: object): value is SignInDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SignInDtoFromJSON(json: any): SignInDto {
    return SignInDtoFromJSONTyped(json, false);
}

export function SignInDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'callbackURL': json['callbackURL'] == null ? undefined : json['callbackURL'],
        'rememberMe': json['rememberMe'] == null ? undefined : json['rememberMe'],
    };
}

export function SignInDtoToJSON(json: any): SignInDto {
    return SignInDtoToJSONTyped(json, false);
}

export function SignInDtoToJSONTyped(value?: SignInDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'callbackURL': value['callbackURL'],
        'rememberMe': value['rememberMe'],
    };
}

