/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInPhoneNumberDto
 */
export interface SignInPhoneNumberDto {
    /**
     * The phone number
     * @type {string}
     * @memberof SignInPhoneNumberDto
     */
    phoneNumber: string;
    /**
     * The password for the account
     * @type {string}
     * @memberof SignInPhoneNumberDto
     */
    password: string;
    /**
     * Callback URL after sign in
     * @type {string}
     * @memberof SignInPhoneNumberDto
     */
    callbackURL?: string;
}

/**
 * Check if a given object implements the SignInPhoneNumberDto interface.
 */
export function instanceOfSignInPhoneNumberDto(value: object): value is SignInPhoneNumberDto {
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SignInPhoneNumberDtoFromJSON(json: any): SignInPhoneNumberDto {
    return SignInPhoneNumberDtoFromJSONTyped(json, false);
}

export function SignInPhoneNumberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInPhoneNumberDto {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneNumber': json['phoneNumber'],
        'password': json['password'],
        'callbackURL': json['callbackURL'] == null ? undefined : json['callbackURL'],
    };
}

export function SignInPhoneNumberDtoToJSON(json: any): SignInPhoneNumberDto {
    return SignInPhoneNumberDtoToJSONTyped(json, false);
}

export function SignInPhoneNumberDtoToJSONTyped(value?: SignInPhoneNumberDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phoneNumber': value['phoneNumber'],
        'password': value['password'],
        'callbackURL': value['callbackURL'],
    };
}

