/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DailyBreakdownDto } from './DailyBreakdownDto';
import {
    DailyBreakdownDtoFromJSON,
    DailyBreakdownDtoFromJSONTyped,
    DailyBreakdownDtoToJSON,
    DailyBreakdownDtoToJSONTyped,
} from './DailyBreakdownDto';
import type { MetricStatsDto } from './MetricStatsDto';
import {
    MetricStatsDtoFromJSON,
    MetricStatsDtoFromJSONTyped,
    MetricStatsDtoToJSON,
    MetricStatsDtoToJSONTyped,
} from './MetricStatsDto';

/**
 * 
 * @export
 * @interface TimeframeMetricsDto
 */
export interface TimeframeMetricsDto {
    /**
     * 
     * @type {MetricStatsDto}
     * @memberof TimeframeMetricsDto
     */
    daily: MetricStatsDto;
    /**
     * 
     * @type {MetricStatsDto}
     * @memberof TimeframeMetricsDto
     */
    weekly: MetricStatsDto;
    /**
     * 
     * @type {MetricStatsDto}
     * @memberof TimeframeMetricsDto
     */
    monthly: MetricStatsDto;
    /**
     * Day-by-day breakdown for the last 30 days
     * @type {Array<DailyBreakdownDto>}
     * @memberof TimeframeMetricsDto
     */
    breakdown: Array<DailyBreakdownDto>;
}

/**
 * Check if a given object implements the TimeframeMetricsDto interface.
 */
export function instanceOfTimeframeMetricsDto(value: object): value is TimeframeMetricsDto {
    if (!('daily' in value) || value['daily'] === undefined) return false;
    if (!('weekly' in value) || value['weekly'] === undefined) return false;
    if (!('monthly' in value) || value['monthly'] === undefined) return false;
    if (!('breakdown' in value) || value['breakdown'] === undefined) return false;
    return true;
}

export function TimeframeMetricsDtoFromJSON(json: any): TimeframeMetricsDto {
    return TimeframeMetricsDtoFromJSONTyped(json, false);
}

export function TimeframeMetricsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeframeMetricsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'daily': MetricStatsDtoFromJSON(json['daily']),
        'weekly': MetricStatsDtoFromJSON(json['weekly']),
        'monthly': MetricStatsDtoFromJSON(json['monthly']),
        'breakdown': ((json['breakdown'] as Array<any>).map(DailyBreakdownDtoFromJSON)),
    };
}

export function TimeframeMetricsDtoToJSON(json: any): TimeframeMetricsDto {
    return TimeframeMetricsDtoToJSONTyped(json, false);
}

export function TimeframeMetricsDtoToJSONTyped(value?: TimeframeMetricsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'daily': MetricStatsDtoToJSON(value['daily']),
        'weekly': MetricStatsDtoToJSON(value['weekly']),
        'monthly': MetricStatsDtoToJSON(value['monthly']),
        'breakdown': ((value['breakdown'] as Array<any>).map(DailyBreakdownDtoToJSON)),
    };
}

