/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferResponseDto
 */
export interface TransferResponseDto {
    /**
     * 
     * @type {string}
     * @memberof TransferResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TransferResponseDto
     */
    merchantId: string;
    /**
     * 
     * @type {string}
     * @memberof TransferResponseDto
     */
    fromCustomerId: string;
    /**
     * 
     * @type {string}
     * @memberof TransferResponseDto
     */
    toCustomerId: string;
    /**
     * 
     * @type {number}
     * @memberof TransferResponseDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof TransferResponseDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof TransferResponseDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferResponseDto
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof TransferResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TransferResponseDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the TransferResponseDto interface.
 */
export function instanceOfTransferResponseDto(value: object): value is TransferResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('merchantId' in value) || value['merchantId'] === undefined) return false;
    if (!('fromCustomerId' in value) || value['fromCustomerId'] === undefined) return false;
    if (!('toCustomerId' in value) || value['toCustomerId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TransferResponseDtoFromJSON(json: any): TransferResponseDto {
    return TransferResponseDtoFromJSONTyped(json, false);
}

export function TransferResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'merchantId': json['merchantId'],
        'fromCustomerId': json['fromCustomerId'],
        'toCustomerId': json['toCustomerId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function TransferResponseDtoToJSON(json: any): TransferResponseDto {
    return TransferResponseDtoToJSONTyped(json, false);
}

export function TransferResponseDtoToJSONTyped(value?: TransferResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'merchantId': value['merchantId'],
        'fromCustomerId': value['fromCustomerId'],
        'toCustomerId': value['toCustomerId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'description': value['description'],
        'status': value['status'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

