/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnauthorizedResponseDto
 */
export interface UnauthorizedResponseDto {
    /**
     * HTTP status code
     * @type {number}
     * @memberof UnauthorizedResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UnauthorizedResponseDto
     */
    message: Array<string>;
    /**
     * Error type
     * @type {string}
     * @memberof UnauthorizedResponseDto
     */
    error: string;
}

/**
 * Check if a given object implements the UnauthorizedResponseDto interface.
 */
export function instanceOfUnauthorizedResponseDto(value: object): value is UnauthorizedResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function UnauthorizedResponseDtoFromJSON(json: any): UnauthorizedResponseDto {
    return UnauthorizedResponseDtoFromJSONTyped(json, false);
}

export function UnauthorizedResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnauthorizedResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'error': json['error'],
    };
}

export function UnauthorizedResponseDtoToJSON(json: any): UnauthorizedResponseDto {
    return UnauthorizedResponseDtoToJSONTyped(json, false);
}

export function UnauthorizedResponseDtoToJSONTyped(value?: UnauthorizedResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'error': value['error'],
    };
}

