/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnbanUserDto
 */
export interface UnbanUserDto {
    /**
     * The ID of the user to unban
     * @type {string}
     * @memberof UnbanUserDto
     */
    userId: string;
}

/**
 * Check if a given object implements the UnbanUserDto interface.
 */
export function instanceOfUnbanUserDto(value: object): value is UnbanUserDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UnbanUserDtoFromJSON(json: any): UnbanUserDto {
    return UnbanUserDtoFromJSONTyped(json, false);
}

export function UnbanUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnbanUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function UnbanUserDtoToJSON(json: any): UnbanUserDto {
    return UnbanUserDtoToJSONTyped(json, false);
}

export function UnbanUserDtoToJSONTyped(value?: UnbanUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

