/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnbanUserResponseDto
 */
export interface UnbanUserResponseDto {
    /**
     * User unbanned successfully
     * @type {boolean}
     * @memberof UnbanUserResponseDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the UnbanUserResponseDto interface.
 */
export function instanceOfUnbanUserResponseDto(value: object): value is UnbanUserResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function UnbanUserResponseDtoFromJSON(json: any): UnbanUserResponseDto {
    return UnbanUserResponseDtoFromJSONTyped(json, false);
}

export function UnbanUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnbanUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function UnbanUserResponseDtoToJSON(json: any): UnbanUserResponseDto {
    return UnbanUserResponseDtoToJSONTyped(json, false);
}

export function UnbanUserResponseDtoToJSONTyped(value?: UnbanUserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

