/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnlinkAccountResponseDto
 */
export interface UnlinkAccountResponseDto {
    /**
     * Social account unlinked successfully
     * @type {boolean}
     * @memberof UnlinkAccountResponseDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the UnlinkAccountResponseDto interface.
 */
export function instanceOfUnlinkAccountResponseDto(value: object): value is UnlinkAccountResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function UnlinkAccountResponseDtoFromJSON(json: any): UnlinkAccountResponseDto {
    return UnlinkAccountResponseDtoFromJSONTyped(json, false);
}

export function UnlinkAccountResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnlinkAccountResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function UnlinkAccountResponseDtoToJSON(json: any): UnlinkAccountResponseDto {
    return UnlinkAccountResponseDtoToJSONTyped(json, false);
}

export function UnlinkAccountResponseDtoToJSONTyped(value?: UnlinkAccountResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

