/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnlinkAccountDto
 */
export interface UnlinkAccountDto {
    /**
     * The social provider to unlink
     * @type {string}
     * @memberof UnlinkAccountDto
     */
    provider: string;
    /**
     * The provider account ID to unlink
     * @type {string}
     * @memberof UnlinkAccountDto
     */
    accountId: string;
}

/**
 * Check if a given object implements the UnlinkAccountDto interface.
 */
export function instanceOfUnlinkAccountDto(value: object): value is UnlinkAccountDto {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    return true;
}

export function UnlinkAccountDtoFromJSON(json: any): UnlinkAccountDto {
    return UnlinkAccountDtoFromJSONTyped(json, false);
}

export function UnlinkAccountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnlinkAccountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'accountId': json['accountId'],
    };
}

export function UnlinkAccountDtoToJSON(json: any): UnlinkAccountDto {
    return UnlinkAccountDtoToJSONTyped(json, false);
}

export function UnlinkAccountDtoToJSONTyped(value?: UnlinkAccountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'accountId': value['accountId'],
    };
}

