/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePayoutDto
 */
export interface UpdatePayoutDto {
    /**
     * 
     * @type {string}
     * @memberof UpdatePayoutDto
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePayoutDto
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdatePayoutDto
     */
    metadata: { [key: string]: any; };
}

/**
 * Check if a given object implements the UpdatePayoutDto interface.
 */
export function instanceOfUpdatePayoutDto(value: object): value is UpdatePayoutDto {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function UpdatePayoutDtoFromJSON(json: any): UpdatePayoutDto {
    return UpdatePayoutDtoFromJSONTyped(json, false);
}

export function UpdatePayoutDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePayoutDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'],
    };
}

export function UpdatePayoutDtoToJSON(json: any): UpdatePayoutDto {
    return UpdatePayoutDtoToJSONTyped(json, false);
}

export function UpdatePayoutDtoToJSONTyped(value?: UpdatePayoutDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'description': value['description'],
        'metadata': value['metadata'],
    };
}

