/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionUserDto } from './SessionUserDto';
import {
    SessionUserDtoFromJSON,
    SessionUserDtoFromJSONTyped,
    SessionUserDtoToJSON,
    SessionUserDtoToJSONTyped,
} from './SessionUserDto';

/**
 * 
 * @export
 * @interface UpdateUserResponseDto
 */
export interface UpdateUserResponseDto {
    /**
     * Updated user object
     * @type {SessionUserDto}
     * @memberof UpdateUserResponseDto
     */
    user: SessionUserDto;
}

/**
 * Check if a given object implements the UpdateUserResponseDto interface.
 */
export function instanceOfUpdateUserResponseDto(value: object): value is UpdateUserResponseDto {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function UpdateUserResponseDtoFromJSON(json: any): UpdateUserResponseDto {
    return UpdateUserResponseDtoFromJSONTyped(json, false);
}

export function UpdateUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'user': SessionUserDtoFromJSON(json['user']),
    };
}

export function UpdateUserResponseDtoToJSON(json: any): UpdateUserResponseDto {
    return UpdateUserResponseDtoToJSONTyped(json, false);
}

export function UpdateUserResponseDtoToJSONTyped(value?: UpdateUserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': SessionUserDtoToJSON(value['user']),
    };
}

