/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HostedCheckoutConfigDto } from './HostedCheckoutConfigDto';
import {
    HostedCheckoutConfigDtoFromJSON,
    HostedCheckoutConfigDtoFromJSONTyped,
    HostedCheckoutConfigDtoToJSON,
    HostedCheckoutConfigDtoToJSONTyped,
} from './HostedCheckoutConfigDto';

/**
 * 
 * @export
 * @interface UpdateCheckoutSessionDto
 */
export interface UpdateCheckoutSessionDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCheckoutSessionDto
     */
    status: string;
    /**
     * The URL to redirect to on successful payment
     * @type {string}
     * @memberof UpdateCheckoutSessionDto
     */
    successUrl?: string;
    /**
     * The URL to redirect to on failure
     * @type {string}
     * @memberof UpdateCheckoutSessionDto
     */
    failureUrl?: string;
    /**
     * The URL to redirect to on cancel
     * @type {string}
     * @memberof UpdateCheckoutSessionDto
     */
    cancelUrl?: string;
    /**
     * Optional custom metadata
     * @type {{ [key: string]: any; }}
     * @memberof UpdateCheckoutSessionDto
     */
    metadata: { [key: string]: any; };
    /**
     * Configuration for the hosted checkout page
     * @type {HostedCheckoutConfigDto}
     * @memberof UpdateCheckoutSessionDto
     */
    hostedCheckoutConfig?: HostedCheckoutConfigDto;
}

/**
 * Check if a given object implements the UpdateCheckoutSessionDto interface.
 */
export function instanceOfUpdateCheckoutSessionDto(value: object): value is UpdateCheckoutSessionDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function UpdateCheckoutSessionDtoFromJSON(json: any): UpdateCheckoutSessionDto {
    return UpdateCheckoutSessionDtoFromJSONTyped(json, false);
}

export function UpdateCheckoutSessionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCheckoutSessionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'successUrl': json['successUrl'] == null ? undefined : json['successUrl'],
        'failureUrl': json['failureUrl'] == null ? undefined : json['failureUrl'],
        'cancelUrl': json['cancelUrl'] == null ? undefined : json['cancelUrl'],
        'metadata': json['metadata'],
        'hostedCheckoutConfig': json['hostedCheckoutConfig'] == null ? undefined : HostedCheckoutConfigDtoFromJSON(json['hostedCheckoutConfig']),
    };
}

export function UpdateCheckoutSessionDtoToJSON(json: any): UpdateCheckoutSessionDto {
    return UpdateCheckoutSessionDtoToJSONTyped(json, false);
}

export function UpdateCheckoutSessionDtoToJSONTyped(value?: UpdateCheckoutSessionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'successUrl': value['successUrl'],
        'failureUrl': value['failureUrl'],
        'cancelUrl': value['cancelUrl'],
        'metadata': value['metadata'],
        'hostedCheckoutConfig': HostedCheckoutConfigDtoToJSON(value['hostedCheckoutConfig']),
    };
}

