/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProductDto
 */
export interface UpdateProductDto {
    /**
     * The name of the product
     * @type {string}
     * @memberof UpdateProductDto
     */
    name?: string;
    /**
     * A description of the product
     * @type {string}
     * @memberof UpdateProductDto
     */
    description?: string;
    /**
     * The price of the product in the smallest currency unit
     * @type {number}
     * @memberof UpdateProductDto
     */
    amount?: number;
    /**
     * Whether the product is active
     * @type {boolean}
     * @memberof UpdateProductDto
     */
    active?: boolean;
    /**
     * The ID of the product image file
     * @type {string}
     * @memberof UpdateProductDto
     */
    imageId?: string;
    /**
     * Optional custom metadata
     * @type {{ [key: string]: any; }}
     * @memberof UpdateProductDto
     */
    metadata: { [key: string]: any; };
}

/**
 * Check if a given object implements the UpdateProductDto interface.
 */
export function instanceOfUpdateProductDto(value: object): value is UpdateProductDto {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function UpdateProductDtoFromJSON(json: any): UpdateProductDto {
    return UpdateProductDtoFromJSONTyped(json, false);
}

export function UpdateProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProductDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'active': json['active'] == null ? undefined : json['active'],
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'metadata': json['metadata'],
    };
}

export function UpdateProductDtoToJSON(json: any): UpdateProductDto {
    return UpdateProductDtoToJSONTyped(json, false);
}

export function UpdateProductDtoToJSONTyped(value?: UpdateProductDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'amount': value['amount'],
        'active': value['active'],
        'imageId': value['imageId'],
        'metadata': value['metadata'],
    };
}

