/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateBalanceDto
 */
export interface UpdateBalanceDto {
    /**
     * The amount to adjust the balance by
     * @type {number}
     * @memberof UpdateBalanceDto
     */
    amount: number;
    /**
     * The currency for the balance
     * @type {string}
     * @memberof UpdateBalanceDto
     */
    currency?: string;
}

/**
 * Check if a given object implements the UpdateBalanceDto interface.
 */
export function instanceOfUpdateBalanceDto(value: object): value is UpdateBalanceDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function UpdateBalanceDtoFromJSON(json: any): UpdateBalanceDto {
    return UpdateBalanceDtoFromJSONTyped(json, false);
}

export function UpdateBalanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBalanceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function UpdateBalanceDtoToJSON(json: any): UpdateBalanceDto {
    return UpdateBalanceDtoToJSONTyped(json, false);
}

export function UpdateBalanceDtoToJSONTyped(value?: UpdateBalanceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currency': value['currency'],
    };
}

