/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyApiKeyDto
 */
export interface VerifyApiKeyDto {
    /**
     * The API key to verify
     * @type {string}
     * @memberof VerifyApiKeyDto
     */
    key: string;
}

/**
 * Check if a given object implements the VerifyApiKeyDto interface.
 */
export function instanceOfVerifyApiKeyDto(value: object): value is VerifyApiKeyDto {
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function VerifyApiKeyDtoFromJSON(json: any): VerifyApiKeyDto {
    return VerifyApiKeyDtoFromJSONTyped(json, false);
}

export function VerifyApiKeyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyApiKeyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
    };
}

export function VerifyApiKeyDtoToJSON(json: any): VerifyApiKeyDto {
    return VerifyApiKeyDtoToJSONTyped(json, false);
}

export function VerifyApiKeyDtoToJSONTyped(value?: VerifyApiKeyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
    };
}

