/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionUserDto } from './SessionUserDto';
import {
    SessionUserDtoFromJSON,
    SessionUserDtoFromJSONTyped,
    SessionUserDtoToJSON,
    SessionUserDtoToJSONTyped,
} from './SessionUserDto';

/**
 * 
 * @export
 * @interface VerifyPhoneNumberResponseDto
 */
export interface VerifyPhoneNumberResponseDto {
    /**
     * Phone verified successfully
     * @type {boolean}
     * @memberof VerifyPhoneNumberResponseDto
     */
    success: boolean;
    /**
     * User information if verification successful
     * @type {SessionUserDto}
     * @memberof VerifyPhoneNumberResponseDto
     */
    user?: SessionUserDto;
}

/**
 * Check if a given object implements the VerifyPhoneNumberResponseDto interface.
 */
export function instanceOfVerifyPhoneNumberResponseDto(value: object): value is VerifyPhoneNumberResponseDto {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function VerifyPhoneNumberResponseDtoFromJSON(json: any): VerifyPhoneNumberResponseDto {
    return VerifyPhoneNumberResponseDtoFromJSONTyped(json, false);
}

export function VerifyPhoneNumberResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyPhoneNumberResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'user': json['user'] == null ? undefined : SessionUserDtoFromJSON(json['user']),
    };
}

export function VerifyPhoneNumberResponseDtoToJSON(json: any): VerifyPhoneNumberResponseDto {
    return VerifyPhoneNumberResponseDtoToJSONTyped(json, false);
}

export function VerifyPhoneNumberResponseDtoToJSONTyped(value?: VerifyPhoneNumberResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'user': SessionUserDtoToJSON(value['user']),
    };
}

