/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyPhoneNumberDto
 */
export interface VerifyPhoneNumberDto {
    /**
     * The phone number to verify
     * @type {string}
     * @memberof VerifyPhoneNumberDto
     */
    phoneNumber: string;
    /**
     * The OTP code received
     * @type {string}
     * @memberof VerifyPhoneNumberDto
     */
    code: string;
}

/**
 * Check if a given object implements the VerifyPhoneNumberDto interface.
 */
export function instanceOfVerifyPhoneNumberDto(value: object): value is VerifyPhoneNumberDto {
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function VerifyPhoneNumberDtoFromJSON(json: any): VerifyPhoneNumberDto {
    return VerifyPhoneNumberDtoFromJSONTyped(json, false);
}

export function VerifyPhoneNumberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyPhoneNumberDto {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneNumber': json['phoneNumber'],
        'code': json['code'],
    };
}

export function VerifyPhoneNumberDtoToJSON(json: any): VerifyPhoneNumberDto {
    return VerifyPhoneNumberDtoToJSONTyped(json, false);
}

export function VerifyPhoneNumberDtoToJSONTyped(value?: VerifyPhoneNumberDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phoneNumber': value['phoneNumber'],
        'code': value['code'],
    };
}

