/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyApiKeyResponseDto
 */
export interface VerifyApiKeyResponseDto {
    /**
     * API key verification result
     * @type {boolean}
     * @memberof VerifyApiKeyResponseDto
     */
    valid: boolean;
    /**
     * API key details (without the actual key)
     * @type {object}
     * @memberof VerifyApiKeyResponseDto
     */
    key?: object;
}

/**
 * Check if a given object implements the VerifyApiKeyResponseDto interface.
 */
export function instanceOfVerifyApiKeyResponseDto(value: object): value is VerifyApiKeyResponseDto {
    if (!('valid' in value) || value['valid'] === undefined) return false;
    return true;
}

export function VerifyApiKeyResponseDtoFromJSON(json: any): VerifyApiKeyResponseDto {
    return VerifyApiKeyResponseDtoFromJSONTyped(json, false);
}

export function VerifyApiKeyResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyApiKeyResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'valid': json['valid'],
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function VerifyApiKeyResponseDtoToJSON(json: any): VerifyApiKeyResponseDto {
    return VerifyApiKeyResponseDtoToJSONTyped(json, false);
}

export function VerifyApiKeyResponseDtoToJSONTyped(value?: VerifyApiKeyResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valid': value['valid'],
        'key': value['key'],
    };
}

